### ISSUE TITLE
Custom Book On Join?

### ISSUE THREAD

**Issue by tjbruce17594** [RockinChaos/ItemJoin#1]
Is it possible to have a custom book item like Mineplex/Hypixel with colors?

Thanks very much.

**Comment by XSilverSlayerX** [comment]
Hello, sorry it is not currently possible but I will plan on adding it. This will be interesting lol.

**Comment by RockinChaos** [comment]
Sorry for such a late reply but this just hasn't been on my top priority list until now. I was busy with revamping and reducing the lag in ItemJoin which has finally been successfully done.

As of ItemJoin v2.9 this has been implemented and it will be uploaded shortly! I hope you enjoy!!
