### ISSUE TITLE
Work perfectly fine for a couple of minutes...

### ISSUE THREAD

**Issue by LudusMC** [RockinChaos/ItemJoin#10]
Greetings,

Man, i freaking LOVE the new update, fantastic work as always!
I adore the new features and the new items.yml. I even got it working on the first try!

So the main idea is for each world to have its own inventory,
I'm using Multiverse  and MultiverseInventories and your plugin for that.

I got it working in my Hub world (which has it's own MVinv group, named, you guessed it "hub") and then i decided to start woking with the inventories of the Paintball world (has it's own MVinv group, "paintball"). That's were everything regarding the inventory thingy kinda went to shit ;P
I'm quite inexperienced with MVinventories so i might have set up something wrong and such...

It worked perfectly fine at first i could use the Hub Items and the Paintball items in their worlds but then i tried to add an enchantment to the ItemFrame item in the Paintball world section and i couldn't  properly reload the items.yml.

config
http://pastebin.com/1u3QBNJc
console:
http://pastebin.com/3EaUuwfu
items.yml (without the Paintball section, because the items still don't show up):
http://pastebin.com/GVsyUmaK
MVinv groups.yml:
http://pastebin.com/eNd4iz1q
 
I have also given these permissions to the default rank:
    - ItemJoin.hub.*
    - Item.Join.get
    - ItemJoin.Use

Thanks for the time you're devoting to this amazing plugin and sorry for the hustle...
Regards

**Comment by RockinChaos** [comment]
Sorry, I am a little exhausted from working constantly on the 2.3 update lol. Could you try to explain to me again what issue you are having? 

Your config and items.yml look perfect btw. Tested and everything and I am having no problems.

Btw thanks so much, it makes me feel so great to hear that. Sometimes I feel developers are under-appreciated.

**Comment by LudusMC** [comment]
I think that you should probably get a couple days off man.
You've earned it! You did an incredible job with the update, and as i've seen, everyone loves it!

I think the problem i'm having, has to do with multiverse inventories.
I made everything from scratch, including the MVinventories groups, and i firstly added the items to my Hub world, and it worked perfectly fine. Then i added some items to my HungerGames world and they didn't show up...

I'm gonna mess around with the MVinventories plugin, 'cause i think that's what screwing things up... I'll let you know..

At the time being, get some rest, and i'll make sure to report back to you in detail of what the problem is, because i don't think it has anything to do with your plugin.

Regards

**Comment by LudusMC** [comment]
Greetings,
I got everything working, but i have found a bug.

This is my current items.yml - http://pastebin.com/BBQ7VSjK
When i changed the enchantment from KNOCKBACK to ARROW_INFINITE it broke the whole file...

If you need help, i could test all of the enchantments for you...
Just let me know.

Regards

**Comment by RockinChaos** [comment]
Thanks man, Feels to great to hear that.

So you are saying you changed the enchant from KNOCKBACK:2 to ARROW_INFINITE:2?
I am not getting this error for some reason.

If you are defining as : ARROW_INFINITE without the :2 at the end that will break the file (this is the enchantment number). This will be fixed in a later version hopefully 2.4. But if it is setup exactly as ARROW_INFINITE:2 it should be working. Do you have an error code?

Here is a picture of it working for me:
http://i.imgur.com/Puopx6e.png

**Comment by LudusMC** [comment]
No worries man, i'm just trying to help.

You are right, it seems like i forgot to add the enchantment number at the end...
Anyway i'm glad that i was wrong,
i thought it would be fun to add that enchantment to the book for some reason...
Speaking of which, i should xD

Anyway, thanks again...
Hit me up if you need to test anything or need a backup coder

Regards

**Comment by RockinChaos** [comment]
Will do! Have a fantastic day and let me know if you have any more problems!
