### ISSUE TITLE
Commands don't get called

### ISSUE THREAD

**Issue by mpivchev** [RockinChaos/ItemJoin#100]
At first, I thought it's something to do with CustomGUI, but I added a "message" command and that doesn't trigger as well. No errors in console. What's the issue?

https://pastebin.com/C44bU57G

**Comment by RockinChaos** [comment]
Just tested it and your items.yml seems to be working just fine as you can see;

![working](https://cloud.githubusercontent.com/assets/10971577/26036294/bef3d562-388f-11e7-8a1b-c95e7eea9964.png)

Are you sure you don't have any plugins that are preventing certain events from triggering such as PlayerInteractEvents?

**Comment by mpivchev** [comment]
That's odd. I'll test more and come back to you

**Comment by RockinChaos** [comment]
Its been a while since I have heard from you, are you still having this issue?
