### ISSUE TITLE
[Request] Enter WorldGuard region event or a command to give whole world's items or an API?

### ISSUE THREAD

**Issue by cwkfr** [RockinChaos/ItemJoin#101]
Since I'm not using per world inventory plugin, I need to give player their "ItemJoin" when they enter specific region, and remove it when they leave the region. Or you can give us a command like /ij gets <world> <player> to give player their join item. Thank you :D

**Comment by RockinChaos** [comment]
Hmmm interesting I can look into adding this in v4.0.

Also, you can get and remove items using ItemJoins commands. Its already been added, use /itemjoin get and /itemjoin remove. You can see it in /itemjoin help.

**Comment by cwkfr** [comment]
I mean a command for every item listed in this "world". Something like /itemjoin gets <world> [player] (notice the 's'). Then I can do 'command-on-entry" flag on my region.

**Comment by RockinChaos** [comment]
Ill look into adding a worldguard region api, so you could put under the new triggers (join, respawn, world-changed) ill add world-guard regions to it.

**Comment by RockinChaos** [comment]
I have now made it as, right besides enabled-worlds you can now set worldguard to true and list the enabled-regions per item so when you enter them you get those items and when you leave them all itemjoin items are removed but regular items will remain. The code is finished will be added in v4.0.

**Comment by cwkfr** [comment]
Can't wait for the snapshot 👍

**Comment by RockinChaos** [comment]
v4.0 has been released with this feature added!

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950
