### ISSUE TITLE
Items replacing with items from the plugin

### ISSUE THREAD

**Issue by T1MOXA** [RockinChaos/ItemJoin#109]
There is another problem.
In place where should be the Join Item will stand, let the sword, then when you log on to the server it will disappear.

**Comment by RockinChaos** [comment]
I'm having issues understanding what your trying to explain. 
Is this what you mean? : In the place of where an ItemJoin item would be placed upon joining such as the ultra-item being the diamond sword, there is a non-itemjoin item in its place and ItemJoin is overwriting / removing the non-itemjoin item from my inventory to put the custom item in the inventory?

**Comment by T1MOXA** [comment]
Yes!

**Comment by RockinChaos** [comment]
The only way to prevent it is changing the slot # to **slot: Arbitrary** which puts the items in the first available slots.

There is an option in v4.0 that prevents items from being overwritten, but that wont be out until Wednesday or Thursday.

**Comment by RockinChaos** [comment]
Merged with Issue #94
