### ISSUE TITLE
ItemJoin issue: Skull Item bugs

### ISSUE THREAD

**Issue by RedBorne007** [RockinChaos/ItemJoin#112]
I'm making a SKULL_ITEM with flags: inventory-modify, self-drops. But when I'm joined, The Skull Item can drop and can move around in my inventory. Is this some kind of bugs? [I'm using ItemJoin v.4.0]

**Comment by RockinChaos** [comment]
Looks to be a configuration issue, can you send your items.yml in a pastebin.com please.

**Comment by RedBorne007** [comment]
#// <>==<>==<> ItemJoin's Custom Items On Join, by RockinChaos <>==<>==<> //#
#// See the Documentations page for a more in-depth tutorial; https://www.spigotmc.org/wiki/itemjoin/ //#
items-Version: 6
items-Delay: 2
items-Overwrite: false
items-Spamming: false

items:
  playgame:
    id: COMPASS
    slot: 0
    name: '&aJoin the field &7(Right Click)'
    commands:
      right-click:
        - 'console: list'
    commands-type: interact
    commands-cooldown: 5
    cooldown-message: '&9[Server] &7Please wait for &c&l%timeleft% &7seconds before using this again!'
    itemflags: inventory-modify, world-changed, hide-attributes, self-drops
    triggers: join, respawn, region-enter
    permission-node: 'itemjoin.menu'
    enabled-regions: spawn
    enabled-worlds: world
  profile:
    id: SKULL_ITEM
    data-value: 3
    skull-owner: '%player%'
    slot: 4
    name: '&bProfile &7(Right Click)'
    commands:
      right-click:
        - 'console: list'
    commands-type: interact
    commands-cooldown: 5
    cooldown-message: '&9[Server] &7Please wait for &c&l%timeleft% &7seconds before using this again!'
    itemflags: inventory-modify, world-changed, hide-attributes, self-drops
    triggers: join, respawn, region-enter
    permission-node: 'itemjoin.menu'
    enabled-regions: spawn
    enabled-worlds: world
  topstats:
    id: PAPER
    slot: 7
    name: '&6Top Stats &7(Right Click)'
    commands:
      right-click:
        - 'console: list'
    commands-type: interact
    commands-cooldown: 5
    cooldown-message: '&9[Server] &7Please wait for &c&l%timeleft% &7seconds before using this again!'
    itemflags: inventory-modify, world-changed, hide-attributes, self-drops
    triggers: join, respawn, region-enter
    permission-node: 'itemjoin.menu'
    enabled-regions: spawn
    enabled-worlds: world
  shop:
    id: EMERALD
    slot: 8
    name: '&9Shops &7(Right Click)'
    commands:
      right-click:
        - 'console: list'
    commands-type: interact
    commands-cooldown: 5
    cooldown-message: '&9[Server] &7Please wait for &c&l%timeleft% &7seconds before using this again!'
    itemflags: inventory-modify, world-changed, hide-attributes, self-drops
    triggers: join, respawn, region-enter
    permission-node: 'itemjoin.menu'
    enabled-regions: spawn
    enabled-worlds: world

**Comment by RockinChaos** [comment]
lol can you post it in a pastebin.com so I can get the proper spacing please.

**Comment by RedBorne007** [comment]
https://pastebin.com/xZjmLyeE

**Comment by RockinChaos** [comment]
Just tested it on my server and I'm not having any issues, can you give me a little more information on how you are replicating this issue? Is it upon joining or entering a region?

**Comment by RedBorne007** [comment]
It's happened when I joining a server and got the ItemJoin

**Comment by RockinChaos** [comment]
You have tried clearing your inventory and rejoining correct?

**Comment by RedBorne007** [comment]
Yep. I'm tried that once. But it still have this issue

**Comment by RockinChaos** [comment]
Wait whats your minecraft version?

**Comment by RedBorne007** [comment]
Spigot 1.8.8

**Comment by RockinChaos** [comment]
Once this build is compiled in approx (6 mins) download it and try it, this should fix your skull issues until I release a bug fix tomorrow. 

http://jenkins.craftationgaming.com:8080/job/ItemJoin/17/

**Comment by RedBorne007** [comment]
I have to use ItemJoin-4.1-SNAPSHOT.jar or original-ItemJoin-4.1-SNAPSHOT.jar ?

**Comment by RockinChaos** [comment]
ItemJoin-4.1-SNAPSHOT.jar

**Comment by RedBorne007** [comment]
It fixed! Thanks for you helped!

**Comment by RedBorne007** [comment]
I'm using original-ItemJoin-4.1-SNAPSHOT.jar

**Comment by RockinChaos** [comment]
No problem. Ill post an official v4.1 update fix late tomorrow. Still have a few other things I need to work out.

The original will work its just not compressed meaning it takes a bit more space but its a minimal difference.

**Comment by RedBorne007** [comment]
Err... I found the problem again. But it's not about the skull item. It's about dropping item. It keep increasing amount of ItemJoin when I'm trying to drop the item [Happened to all ItemJoin]

**Comment by RedBorne007** [comment]
It's happened when I'm opening my own inventory

**Comment by RockinChaos** [comment]
are you in survival or creative?

**Comment by RedBorne007** [comment]
It's happened to creative mode

**Comment by RedBorne007** [comment]
Er.. Can I ask you a question?. What version of WorldGuard that can use with ItemJoin?. Because I'm using older version [WorldGuard v.5.9]

**Comment by RockinChaos** [comment]
You can use any worldguard version. There a little bug with creative mode atm that I am trying to work around. This is an issue with Mojang sadly.

**Comment by RedBorne007** [comment]
How to make the ItemJoin give in only specific region and when walking out of that region. ItemJoin will gone?. Because I'm trying to do that. But it doesn't work

**Comment by RedBorne007** [comment]
When I'm cleared my inventory in other region and rejoin, ItemJoin has been given. How to fix this?

**Comment by RedBorne007** [comment]
Oh. And I found another bug. When you make Prevent-Pickups: false in config.yml. Every item that has been used in ItemJoin can't picked up

**Comment by RockinChaos** [comment]
You have to set WorldGuard to true and set enabled-regions: (region name). Then set region-enter to your triggers.

Little confused what you mean by prevent-pickups. If its set to false you can pickup items?

**Comment by RedBorne007** [comment]
Sorry, If you make Prevent-Pickups set to true and in item.yml have the COMPASS item as the ItemJoin. When I'm join the game and drop normal compass, I can't picked it up

**Comment by RedBorne007** [comment]
I've already set WorldGuard in config.yml to true, add enabled-regions, add trigger: region-enter. But it still no use...

**Comment by RockinChaos** [comment]
That is intended thats what the feature is suppose to do. It prevents the picking up of items. Its enabled by default for ItemJoin items, some people just wanted the option for all items so I added prevent-pickups.

**Comment by RockinChaos** [comment]
So once you walk into that region under enabled-regions you dont get the itemjoin items?

**Comment by RedBorne007** [comment]
Er.. What should i say.. Er... I have set trigger: join, respawn, region-enter | enabled-regions: spawn. When I'm in other region [I'll say as "A" region] instead of "spawn" region. I'm trying to clear my inventory and rejoin the server. It still give me the ItemJoin in "A" region. How do i fixed this?

**Comment by RockinChaos** [comment]
can you send your current items.yml in pastebin.com

**Comment by RockinChaos** [comment]
Ohhhh!! Your re-joinning the server in the "A" region. You have the join trigger on which means items will be given on join. if you dont want to receive items on join then remove the join trigger.

**Comment by RockinChaos** [comment]
The enabled-regions only apply to walking in and out of the regions, or joining in the region. Once in the region you will be given the item. Once leaving you will lose the item, however if the join trigger and or world-changed and or respawn trigger is used it will be given anywhere.

**Comment by RedBorne007** [comment]
If it still can't fix. I will use ItemJoin for per world instead..

**Comment by RedBorne007** [comment]
Well. When I'm walking in the "spawn" region. It didn't give me any ItemJoin

**Comment by RedBorne007** [comment]
OK. It doesn't give any ItemJoin when I'm joined now. But I still don't get any item when entering "spawn" region or rejoin in "spawn" region.

**Comment by RedBorne007** [comment]
I want it like.... When I'm in "spawn" region or die and respawn or rejoin in "spawn" region. It will give the ItemJoin. but when I leaving the region and playing in "A" region or rejoin in "A" region. It will took all ItemJoin out of my inventory

**Comment by RedBorne007** [comment]
But If that can't fix. I will use ItemJoin in per world instead. So all the problem will be gone.

**Comment by RockinChaos** [comment]
Send your items.yml in a pastebin.com Ill configure it for you, its just a config issue.

**Comment by RockinChaos** [comment]
All you have to do is set enabled-regions to spawn and triggers to region-enter. Then when you enter spawn, respawn into spawn, or join the server to spawn it will be given to you since you are in the regions spawn.

**Comment by RockinChaos** [comment]
I might have just fixed the issue you are having, try http://jenkins.craftationgaming.com:8080/job/ItemJoin/18/

I join and get the items only when in the region as well as respawning.
It works **just using the trigger region-enter.**

Let me know if this worked for you. Sorry for the hassle its really late for me and my mind is going dumb lol.

**Comment by RedBorne007** [comment]
I will try that and will tell you a result soon. (Sorry for let you waiting for a long day, I'm very busy since that day)

**Comment by RockinChaos** [comment]
Its all good I know the feeling. I just started summer quarter of college so I been busy as well.

**Comment by RedBorne007** [comment]
I've tried to add a trigger: region-enter, respawn ¦ enable-region: spawn in item.yml. When I'm leaving spawn region, It still don't remove ItemJoin. Am I doing something wrong? (I will give you a item.yml file later, I'm busy today)

**Comment by RockinChaos** [comment]
Make sure its
Triggers:

Not
Trigger:

Defiantly send your items.yml when you can I feel like there is a typo somewhere.

**Comment by RedBorne007** [comment]
OK. I will check it out soon. Thanks for quick replying :)
