### ISSUE TITLE
Give all.

### ISSUE THREAD

**Issue by BrettplayMC** [RockinChaos/ItemJoin#115]
I think /itemjoin give all should be added to give ALL of the items to that player no matter the world or conditions.  I also this there should be /itemjoin remove all to undo this effect. :)

**Comment by RockinChaos** [comment]
I will look into adding this, the only problem is I would have to figure a way to block users from naming their items identifier to all. Such as ultra-item being all instead of ultra-item. 

I will keep you posted with my progression on this.

**Comment by BrettplayMC** [comment]
Ok.  Also, a way to silence giving and removing items from players inventories would be AMAZING!

**Comment by RockinChaos** [comment]
You mean the message being sent in chat right? You can just remove the whole line in the en-lang.yml and it wont send a message or leave it blank and it wont send.

**Comment by BrettplayMC** [comment]
oo

**Comment by BrettplayMC** [comment]
But it still sends the prefix. :(
http://prntscr.com/fujatk
givenToYou: ''
givenToPlayer: ''

**Comment by BrettplayMC** [comment]
OHHHHH

**Comment by BrettplayMC** [comment]
Lol fixed.  I read your message wrong. xD
tysm.

**Comment by RockinChaos** [comment]
Lol I have no idea how you fixed it cus I getting console errors on my end LOL. I found a bug on it that I will have to patch. Setting it to '' should not send a blank message. But as well as fully removing it for me sends a console error which apparently I have to fix.

**Comment by BrettplayMC** [comment]
ok. :D 
I don't use PWP any more <333

**Comment by RockinChaos** [comment]
Yeah.. Its been really hard to maintain PWP because it doesn't get regular updates. I wish I could drop it but its still used pretty universally.

**Comment by BrettplayMC** [comment]
Ahhh.  Well can't wait for the update!  Do you know what else will be added?

**Comment by BrettplayMC** [comment]
Also I highly suggest making a resource Discord. :P

**Comment by RockinChaos** [comment]
Hopefully within the next day or two.

Also what do you mean by resource Discord?

**Comment by BrettplayMC** [comment]
I found it. x)
I meant a support discord but you have one :D

**Comment by RockinChaos** [comment]
derrp lol

**Comment by RockinChaos** [comment]
I have added the commands;

/ItemJoin getAll
/ItemJoin getAll <Player>
/ItemJoin removeAll
/ItemJoin removeAll <Player>

v4.2 Should be released tomorrow containing these changes.

**Comment by BrettplayMC** [comment]
Ok! :D

**Comment by RockinChaos** [comment]
Released you can get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=171839
