### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by KechuFonzo** [RockinChaos/ItemJoin#119]
I'm having a new issue I don't know why is happening but please help me. And when I install the v 4.2 players start to lost treir inventories. I'm using multiinv If you know what is going on tell me.
https://pastebin.com/WPsyDKUY

Sorry for no description xD

**Comment by RockinChaos** [comment]
Uhm theres no description lol

**Comment by RockinChaos** [comment]
can you send your items.yml and config.yml it looks like you have something incorrectly configured.

Your players are losing their inventories correct?

**Comment by KechuFonzo** [comment]
I fixed it its seem that I delete this line Clear-Items: All, I thought that this line was the problem of the Inventories but maybe its other plugin sorry. If that line clear items on all world, I have to put the world that I want that item bee clear or I just do not touch it?

**Comment by RockinChaos** [comment]
Yeah it has to be another plugin, as long as you didnt set the two below it.

Clear-On-Join: false
Clear-On-WorldChanged: false

the only way to clear inventories is to set those to true.

Just dont touch it would be the best bet. All means clear all items. You can also change it to Clear-Items: ItemJoin and it would only clear itemjoin items and leave any other items alone.

**Comment by KechuFonzo** [comment]
Okay thanks for your time I will try to fix the inventories lost. Closed
