### ISSUE TITLE
Question/Issue about Items.yml Commands

### ISSUE THREAD

**Issue by Zenoxez** [RockinChaos/ItemJoin#12]
Hello,

I know you may not want to be bothered with this, as it only partially has to do with your plugin. However, I am completely stumped here and I think my problem may have something to do with ItemJoin.

So, I am using ItemJoin V 2.3. I am also using a plugin called [CustomPermissionMessages](https://www.spigotmc.org/resources/custom-permission-messages.1009/).

CustomPermissionMessages allows me to change the message a player gets when he is denied access to a command. Currently, when you type /fly, and you do not have permission for the command, a custom message is displayed. I have an ItemJoin Item (Slot 1) set up to execute the command /fly by the player. However, when you click on the item, the custom message is not displayed, the default one is.

This is very confusing to me as I figured executing a command by a player with ItemJoin would be just like the player typing /fly themselves. However, it can't be as I'm getting different responses.

**Here are some of my files:**

[ItemJoin Config.yml](http://pastebin.com/XcE4MXv5)
[ItemJoin Items.yml](http://pastebin.com/bp7kF9fu)
[CustomPermissionMessages Config](http://pastebin.com/f19epuac)

If you can't or won't help, I understand. 

Thanks a lot,

- Zenoxe

**Comment by RockinChaos** [comment]
Sorry, but I am not understanding. So what you are saying is the player is executing /fly and is not having permissions? If you want it to bypass permissions issue you use console: fly %player%

This would make console execute /fly RockinChaos

Is this what you are looking for? Meh sorry I am a little confused. By the way I am always happy to help!

**Comment by Zenoxez** [comment]
Thanks for the reply.

I want the player to basically execute the /fly command themselves when they click on the item.

**Comment by Zenoxez** [comment]
This is how the Items.yml looks:

      commands:
        - 'player: fly'

When the player clicks the item does the exact same thing happen as if they were actually typing /fly?

**Comment by RockinChaos** [comment]
yes. 100% correct ;)

**Comment by RockinChaos** [comment]
the executor (player: and console:) are represented as how they will be ran. player: forces the player to run the command. console: forces the console to run the command. That's why there are variables such as %player% so console can find said player. So console could execute /fly %player% === RockinChaos.

**Comment by RockinChaos** [comment]
Also I noticed you closed a ticket that had something to do with world names. Can you go more in-depth on that? I recently changed something to do with world names so if its a bug I would love to know so I can fix it.

**Comment by Zenoxez** [comment]
Sure. I have a world names "Hub". I originally, in the items.yml, had the world as "Hub" which worked fine before the update. Then, after the update, it wouldn't work until I changed it to "hub" without the Capital "H".

Here:

==========
world-list: #// This is the list of worlds that have custom items on join. //#
**  - hub**

#// For every world listed in the world-list, you need to make a section for it. //#
**hub:**
  items:
    1:
      id: COMPASS
      data-value: 0
      name: '&6&lServer Selector'
      lore:
        - '&7Right Click to Open'
      commands-cooldown: 5
      cooldown-message: '&7You must wait 5 seconds between uses!'
    9:
      id: FEATHER
      data-value: 0
      name: '&4&lFlight'
      lore:
        - '&7Right Click to Toggle'
      commands:
        - 'player: fly'
      commands-cooldown: 5
      cooldown-message: '&7You must wait 5 seconds between uses!'
=========================

And I'm still trying to figure out my issue.

**Comment by RockinChaos** [comment]
Thanks, I will look into this bug and fix it prompt! It should make the worlds non-case sensitive but apparently that failed lol.

For your issue. You are trying to see if the player is executing the command correct? If you set it so the player executes /fly it would need to be 'player: fly'

The player will need the essentials fly permission. Which would allow them to execute /fly even without the item.

the 'console: fly %player%' would allow the player to NOT have the essentials fly permission and only be able to fly using the item.

**Comment by RockinChaos** [comment]
The world name case sensitivity issue has been fixed as of version 2.4. This will be released in the next few days!
