### ISSUE TITLE
MyWorlds dependency.

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#121]
Alternative to Multiverse for multi-world support since Multiverse currently breaks custom advancements from loading. Possible to add it as another optional dependency?

https://www.spigotmc.org/resources/myworlds.39594/

**Comment by RockinChaos** [comment]
Will do, Ill add it to the plugin however ItemJoin is already compatible with any multi worlds plugin so far. I will officially add my world to ItemJoin though.

**Comment by RockinChaos** [comment]
This has been added and released in v4.3
You can get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=176180
