### ISSUE TITLE
Players can drop items

### ISSUE THREAD

**Issue by FrankHeijden** [RockinChaos/ItemJoin#122]
Heya, players can drop items, i have only set this flag:

`    itemflags: unbreakable`

**Comment by RockinChaos** [comment]
How do I set custom itemflags on an item?
Itemflags allow HUGE modifications to the items. All you have to do to add itemflags to an item, is add the itemflags identifier to the item as shown below.

These are custom itemflags, all itemflags with description are listed below, Itemflags are always being updated an added onto so check back here for updates!

Current available itemflags:
first-join - This will only give the item when joining the server for the first time, to get the item every time you join just remove this itemflag.
unbreakable - Set the item as INDESTRUCTIBLE!
hide-attributes - Hides ALL attributes, such as firework color, damage the item does, enchantments. (Hides everything from lore except the custom lore).
hide-durability - Hides the durability bar from the item.
placement - Prevents this item from being placed if it is a BLOCK.
inventory-modify - Prevents this item from being moved, stored, or switched to offhand in the players inventory.
cancel-events - Prevents player from opening a chest while this item is in hand or any open-able items. Useful for canceling the event of opening a book to set custom book items.
count-lock - Prevents the player from using all of the item. If the item is set to count: 32 then each time the player places the block item the stack will be refreshed back to 32.
death-drops - Clears this item if it is dropped on the ground when the player dies.
self-drops - Prevents the player from dropping this item, either clicking it out of inventory or using the drop key, usually (q).
disposable - If a command is ran from the item it will remove x1 of the item from the players inventory.
AllowOpBypass - This would allow the user IF THEIR OP to bypass most of these itemflags. It will work on ALL non item modifying flags. This would NOT work on unbreakable, hide-attributes, stuff like that.
CreativeBypass - This would allow the user IF THEIR IN CREATIVE MODE to bypass most of these itemflags. It will work on ALL non item modifying flags. This would NOT work on unbreakable, hide-attributes, stuff like that.


You should have; `itemflags: unbreakable, death-drops, self-drops`
