### ISSUE TITLE
itemjoin error

### ISSUE THREAD

**Issue by remustodk** [RockinChaos/ItemJoin#126]
[ItemJoin] Plugin ItemJoin v4.2 has failed to register events for class me.RockinChaos.itemjoin.listeners.SwapHands because org/bukkit/event/player/PlayerSwapHandItemsEvent does not exist.

HELP PLEASE!

**Comment by RockinChaos** [comment]
This is because you are using and outdated version of v1.9 when the swap hands was implemented. Try updating to a later build of v1.9 and it will work. There is no way for me to detect what build of v1.9.0 you are using and spigot really screwed up when releasing that broken early build.

**Comment by RockinChaos** [comment]
Im not saying update your mc version. Im saying update to a later version of v1.9.0 that was released the same day as the first build.

**Comment by RockinChaos** [comment]
I have found a way to make it so it wont register the event if it doesnt exist in the certain version. Will be released soon.

**Comment by RockinChaos** [comment]
Issue has been fixed and released in v4.3
You can get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=176180
