### ISSUE TITLE
Head Does not Take the Shape of the Player

### ISSUE THREAD

**Issue by Techno3600** [RockinChaos/ItemJoin#127]
Hello,

On my server the player head that I have in slot 7 of the inventory that players get on join does not take the shape of the player, instead it is the form on Steve. 

Here is the head's config

world:
  items:
    skull-item:
      id: SKULL_ITEM
      slot: 8
      itemflags:
        - 'unbreakable'
        - 'inventory-modify'
        - 'respawn'
        - 'inventory-modify'
        - 'world-changed'
        - 'placement'
        - 'self-drops'
        - 'AllowOpBypass'
      name: '&aServer Menu'
      skull-owner: '%player%'
      data-value: 3
      lore:
        - '&7This is the menu, click on it'
        - '&7report any problems by doing /ticket or /mail!'
      commands:
      - 'player: cc open server_menu.yml'

Thanks
Techno3600

**Comment by RockinChaos** [comment]
If you are using ItemJoin v4.2 there is nothing more I can do this is an issue with mojang not being able to accept some connections to their servers to retrieve the players skin. I would suggest opening a bug request to mojang but its doubtful they will care.

**Comment by Techno3600** [comment]
Okay, I'll see what I can do.

**Comment by RockinChaos** [comment]
Sorry, I tried submitting a bug report to them but since they are owned by Microsoft now they just told me to piss off.

**Comment by Techno3600** [comment]
Wow, that's rude.
