### ISSUE TITLE
MysqlInventoryBridge support?

### ISSUE THREAD

**Issue by fickyu** [RockinChaos/ItemJoin#128]
plugin gives items but they instantly replaces with MysqlInventoryBridge inventory content

**Comment by RockinChaos** [comment]
So ItemJoin items are getting replaced by MySQLInventoryBridge? If this is true, its something you would have to take up with the developer. I cannot find any API allowing me to hook into the plugin so they might have to add support for ItemJoin.

**Comment by fickyu** [comment]
Yes

**Comment by RockinChaos** [comment]
Just a thought as I am looking to see how I can add support for this plugin, Have you tried setting the items-delay in the items.yml of ItemJoin higher in seconds? If you were to do that it would be possible to give the items after the MySQLInventoryBridge gives the items.

**Comment by brunyman** [comment]
A delay will be fine, I can create a sync complete event if you need.

**Comment by RockinChaos** [comment]
Holy biscuits this is an old ticket, not sure how you even came across it lol.

If you wanted to add a sync complete event that would be amazing, then I could add support for your plugin.
