### ISSUE TITLE
language.yml

### ISSUE THREAD

**Issue by jettrainz** [RockinChaos/ItemJoin#13]
Hello. I was wondering if you could add a way for us users to change the messages that ItemJoin sends to the player for different things, such as no perms, receiving an item, etc.

Not that I don't want to discredit you, but I don't like the message- for the setup I have going on.

Thanks!

**Comment by RockinChaos** [comment]
Sounds perfect! This is something I have been meaning to add for some time now but I just haven't gotten around to it yet. 

This is fairly simple to do, I will have this finished for version 2.5. I will double check it but if I miss any messages to add to the lang.yml file please let me know. I have a tendency to forget some things lol.

**Comment by RockinChaos** [comment]
I have just finished this for version 2.5. Once 2.5 has been released I will let you know!

**Comment by jettrainz** [comment]
Sounds great! Thank you.

**Comment by jettrainz** [comment]
Oh, one more thing. In language.yml, can you make it so if I don't provide a message (e.g.: kit-receive: '') it doesn't send the message? I'd greatly appreciate it!

**Comment by RockinChaos** [comment]
Yes! This is something I made sure was added. I always prefer the option to not have a message :)

**Comment by jettrainz** [comment]
Thank you.

**Comment by RockinChaos** [comment]
This has just been uploaded as of ItemJoin v2.5. The language file is incomplete yet I had it upload it anyways due to the CraftBukkit/Spigot 1.9 release. Do with it as you wish but it will become more configurable in the future. (ItemJoin v2.6).

**Comment by jettrainz** [comment]
Awesome! It works perfectly. Thank you.

**Comment by jettrainz** [comment]
Actually. I just found a bug. So I'm using WGRegionCommands (this may not be your error- but it doesn't happen with other plugins that don't provide a message), and having the server give the player an item when they enter that region (I tried reversing it and having the player enter the command (player-enter-command), and it didn't work). It gives me one of the two items, and throws a large error in console. I can provide logs if you need.

**Comment by RockinChaos** [comment]
It seems like its WGRegionCommands causing the error. Can you provide logs please? I will be able to give you an official answer with them.

**Comment by jettrainz** [comment]
Sorry for the late response. Here it is: http://pastebin.com/dS7XtkkP

**Comment by RockinChaos** [comment]
Yeah its WGRegionCommands. You would have to talk to the developer about this. It references ItemJoin only once but that is because it failed to dispatch a command due to,

**[19:01:03 ERROR]: Could not pass event RegionLeftEvent to WGRegionCommands v0.1**

There should be no compatability issues.

EDIT: Just checked and yeah.. That plugin is WAY outdated. I see so many errors in it. Understandable why there are some null errors xD.
