### ISSUE TITLE
[Feature Request] Execute as OP

### ISSUE THREAD

**Issue by altrisi** [RockinChaos/ItemJoin#131]
Basically, to be able to execute a command as op (or with all perms/perm "*"). Only for the specified command.

**Comment by RockinChaos** [comment]
Already almost finished implementing this. It should be out in the next update!

**Comment by altrisi** [comment]
Thanks!

**Comment by RockinChaos** [comment]
Added as of v4.5 you can get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=185550
Just simply put the **executor as op:** (instead of server: or player:) if you are still confused, see the executor examples on the documentation page located under Getting Started.
