### ISSUE TITLE
Issue that causes ItemJoin to be impossible to use

### ISSUE THREAD

**Issue by Brancy10** [RockinChaos/ItemJoin#132]
I need help - whenever I launch the server, during the launch it gives me this in the console:

**[ItemJoin] Your items.yml is out of date and new options are available, generating a new one!**
[ItemJoin] Checking for updates...
[ItemJoin] You are up to date!
[ItemJoin] has been Enabled!

When it generates the new items.yml, it takes the old one (which has been edited to what I want to be given on join), renames it to something like items35095.yml and creates the default items.yml in place of the one I edited. This means that when you log on, it gives you the default items instead of the ones that I changed it to.

Server is CraftBukkit 1.12.1 running the following plugins:
ChatLogger
ChestCommands
ControlTPA
GameMode Changer
HomeSpawnWarp
MultiWorld
PerWorldInventory (I set this to true in the config.yml)
SimpleMail
SkyWars
ViaVersion and ViaBackwards (Enables players to join from 1.9 - 1.12.1)
WorldCommand
and of course, ItemJoin

Any idea what's causing the issue?

**Comment by RockinChaos** [comment]
This is due to a user error in the items.yml configuration. Please send your items.yml in a pastebin.com (that you try to create) and ill tell you whats wrong.

**Comment by Brancy10** [comment]
Here it is:
https://pastebin.com/4m0QQZwa

**Comment by Brancy10** [comment]
I put the code into a YAML parser and it gave me this error:
```
ERROR:

mapping values are not allowed here
  in "<unicode string>", line 9, column 9:
        slot: 0
```
I have no clue what this means.

**Comment by RockinChaos** [comment]
The items are not setup correctly. The spacings are messed up. See the default generated config. I cant fix it on my phone and I am at school atm so if you dont get it spaced correctly by the time I get home I will fix it.

That error is a general error by Bukkit when any yaml file is incorrectly setup. All plugins have the same YAML formatting.

**Comment by Brancy10** [comment]
Ahh I see.
I fixed the spacing, I'm launching the server now.

**Comment by Brancy10** [comment]
Hmm, it still gave me the error

**Comment by Brancy10** [comment]
Thanks so much! I was able to get it to world properly.
