### ISSUE TITLE
Delay in command section

### ISSUE THREAD

**Issue by RedBorne007** [RockinChaos/ItemJoin#133]
Can you add delay (20 ticks = 1 second) in command section?

Example

commands:
   right-click:
      - 'message: Teleport in 5 seconds...'
      - 'delay: 100'
      - 'console: spawn %player%'
      - 'message: Teleport to spawn!'

**Comment by RockinChaos** [comment]
Should be pretty easy. Thanks for the suggestion.

**Comment by RockinChaos** [comment]
Added as of v4.5 and it has been released here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=185550
It works exactly how you requested, just simply put delay: #ofticks such as delay: 10 or delay: 100.
