### ISSUE TITLE
Commands without permission to execute in Help page index

### ISSUE THREAD

**Issue by Kitaro-74** [RockinChaos/ItemJoin#135]
Hello, 
I just installed the plugin on my server. So far i figured out how permission work to give items to non-op players. 
I have a problem that bothers me.
When a non-op player type "/help" he gets 4 pages with /ij and /ItemJoin commands, but he has permission to execute only /itemjoin permissions and /ij permissions. The rest of the commands show the error message "[ItemJoin] You do not have the permission to use that command"
It is possible to hide from help menu the commands that he don't have permission to execute?

Thanks.

**Comment by RockinChaos** [comment]
You are talking about the /help menu not the /ij help right? If so this is not a part of ItemJoin. It is how bukkit/spigot setup their help menu. Its possible to install a plugin to modify this to what your desired outcome is though.

**Comment by Kitaro-74** [comment]
Yes I'm talking about the /help menu. As a regular player I can see only the help for commands i have permissionon from the other plugins. But from ItemJoin i can see as a regular player all the commands even if i don't have permission for them. Do you know what plugin i can use to hide commands from help menu? Thanks

**Comment by RockinChaos** [comment]
Thats really weird because ItemJoin's permissions are setup the same way as other plugins are. At the moment I am not sure what plugin it is that you can use, I am not home at the moment but I will send it once I get home.

**Comment by RockinChaos** [comment]
Fixed as of v4.5 and it has been released here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=185550
