### ISSUE TITLE
trigger: on world change

### ISSUE THREAD

**Issue by Someone-NEW** [RockinChaos/ItemJoin#136]
i have one problem that ItemJoin items wont be correct removed when player change world. Example:
I have using per world inventory with xInventories and i have One SkyBlock world and there are sb-lobby "lobby world" ASkyBlock etc. and all this worlds have the same inventory and when player go to their Island that are different world but the same inventory "ItemJoin" items do not want be removed i dont want to be all plaers inventory removed but that ItemJoin will on changed-world will delete their items, but currently are buggy.

**Comment by RockinChaos** [comment]
hmm Sounds like a config issue. Can you post your items.yml in a pastebin.com please?

**Comment by Someone-NEW** [comment]
I have all correct setup like on examples etc. just not work idk why

**Comment by RockinChaos** [comment]
You have clear items enabled in the config.yml correct?

**Comment by Someone-NEW** [comment]
hmm no i think i have before some problem when i set this to true are all cleared so in that case i have this set up back to false https://pastebin.com/fg7Epf9j

**Comment by RockinChaos** [comment]
Little confused on what the problem is. You are trying to clear only ItemJoin items upon changing worlds correct? There for you set clear-items to ItemJoin and Clear-On-WorldChanged to true?

**Comment by Someone-NEW** [comment]
I thinki am solved fornow this, like you say thiscleared only ItemJoin items thats all i need tnx
