### ISSUE TITLE
Firework Charges

### ISSUE THREAD

**Issue by evanmcclan** [RockinChaos/ItemJoin#137]
can you please add a way in the configuration to modify the NBT tags of firework charges (also known as firework stars) just like how you can alter fireworks themselves in the item-join config. I'd like to be able to have them be displayed as different colors in the inventory menu. 

Thanks so much, I love this plugin so much, keep up the great work!
~Sincerely Evan_McClan

**Comment by RockinChaos** [comment]
Added as of v4.5 and it has been released here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=185550
Just simply create an item called FIREWORK_CHARGE and add charge-color: BLUE (or whatever color you want just an example). If you are still confused on how to do it see the example on the documentation page of ItemJoin located under Getting Started.
