### ISSUE TITLE
Custom Heads Textures

### ISSUE THREAD

**Issue by PinoyLifeCraft** [RockinChaos/ItemJoin#139]
Hello there,

It would be nice if you add Custom Heads Textures, as well as support for HeadDataBase, here are the things that I like 😜 

[This would be a great TIPS 🙂 ](https://www.spigotmc.org/resources/deluxemenus.11734/update?update=174476)

**Comment by RockinChaos** [comment]
Thanks for the idea I will look into adding this in the future, probably v4.6.

**Comment by RockinChaos** [comment]
Okay so! I have added this feature for v4.6 as well now. Snapshot will be out soon if you are interested.

My system mainly works off of http://minecraft-heads.com, however it will work for any URL as long as its encoded in Base64, as shown in the screenshots minecraft-heads.com already supplies the needed texture for you so not many people will have to worry about it.

All I have done is added skull-texture to skull items so as shown below you just have to copy the texture value from minecraft-heads.com into the skull-texture on the skull item.

(Random head from minecraft-heads.com)
Copy the code supplied from them)
<a href="https://imgur.com/eJxbOZ5"><img src="https://i.imgur.com/eJxbOZ5.png" title="source: imgur.com" /></a>

(This is the code I copied all spaced out so you can see what everything is).
<a href="https://imgur.com/F2sDvsi"><img src="https://i.imgur.com/F2sDvsi.png" title="source: imgur.com" /></a>

(This is what you need from the code highlighted in red). 
(Copy this).
<a href="https://imgur.com/gG4o5CK"><img src="https://i.imgur.com/gG4o5CK.png" title="source: imgur.com" /></a>

(Paste the code as shown below into the skull-texture).
<a href="https://imgur.com/nQuiyv0"><img src="https://i.imgur.com/nQuiyv0.png" title="source: imgur.com" /></a>


(Shown working with the Cauldron as well as another random skull texture I found).
<a href="https://imgur.com/yTvEfkr"><img src="https://i.imgur.com/yTvEfkr.png" title="source: imgur.com" /></a>

**Comment by PinoyLifeCraft** [comment]
Hello there @RockinChaos ,

How about HeadDataBase support? The thing that I requested 😂

To use the Head Database hook, HDB must be enabled on your server and then all you will need to do is set the material to this format:

`    material: 'hdb-<head id>'
ex:
    material: 'hdb-4320'`

**Comment by RockinChaos** [comment]
Do you mean support for the actual hdb plugin or the website? I just bypassed the need for the premium plugin and just added the website that it grabs the heads from.

I can easily add support for the hdb plugin though its just one line of code but I cannot check if it works or not considering its a premium plugin.

**Comment by RockinChaos** [comment]
Added HeadDatabase support in the latest snapshot.

It works as such;
`skull-texture: 'hdb-<head id>'
ex:
skull-texture: 'hdb-4320'`

**Comment by DarkFort** [comment]
It works: 
skull-texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTM2ZTk0ZjZjMzRhMzU0NjVmY2U0YTkwZjJlMjU5NzYzODllYjk3MDlhMTIyNzM1NzRmZjcwZmQ0ZGFhNjg1MiJ9fX0='

 And this is not:
skull-texture: 'hdb-2003'

**Comment by RockinChaos** [comment]
@DarkFort Make sure you are using the latest snapshot. Tested as of now and it is working.

http://ci.craftationgaming.com/job/ItemJoin/74/

**Comment by RockinChaos** [comment]
Added as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
