### ISSUE TITLE
Firework Rockets Item?

### ISSUE THREAD

**Issue by MatsCraft1** [RockinChaos/ItemJoin#14]
Hi how would look an example item for a Firework?

**Comment by RockinChaos** [comment]
I'm not sure what you are going for, but I am assuming you are trying to get a firework?

The ID would be FIREWORK

There are a list of ID's here
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

**Comment by MatsCraft1** [comment]
I mean how can I add the effects like a Creeper Face explosion

**Comment by RockinChaos** [comment]
At the moment you cant. This feature is not implemented in Bukkit so I will have to figure out an alternative way to add effects for itemjoin. I will see if this is possible and let you know.

**Comment by MatsCraft1** [comment]
Thank you!

**Comment by RockinChaos** [comment]
Great news! This has been added as of ItemJoin v3.1 and will be uploaded soon! Sorry for such a late reply.

**Comment by RockinChaos** [comment]
Version 3.1 has been released! Enjoy!
http://dev.bukkit.org/bukkit-plugins/itemjoin/files/26-item-join-v3-1/
