### ISSUE TITLE
Custom Banner Pattern

### ISSUE THREAD

**Issue by PinoyLifeCraft** [RockinChaos/ItemJoin#140]
Hello there,

I've noticed your wiki there such nothing about banner 🙂  which is so sad so I decided to suggest it here.

Now what I want to happen is we can place a customizable banner pattern at the items.yml
So here's what I saw in the other plugin 😉....

`     banner_meta: (this is used if you want to display a custom banner with specific patterns)
     - <dyecolor>;<PatternType> (more information on where to find DyeColor and PatternType names below)
     - 'RED;BASE'
     - 'WHITE;CREEPER'`
courtesy : DeluxeMenus Update ([click me](https://www.spigotmc.org/resources/deluxemenus.11734/update?update=45082))
Valid Pattern Types: [Me](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/banner/PatternType.html)

**Comment by RockinChaos** [comment]
Should be easy to add, will try to have this done for v4.6. Thanks for the great feature requests its been a while since something major like this was requested.

**Comment by RockinChaos** [comment]
<a href="https://imgur.com/RGSlM4G"><img src="https://i.imgur.com/RGSlM4G.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/76GKmj6"><img src="https://i.imgur.com/76GKmj6.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/VFpHNG7"><img src="https://i.imgur.com/VFpHNG7.png" title="source: imgur.com" /></a>

I have added;

`banner-meta: RED:HALF_HORIZONTAL, BLACK:RHOMBUS_MIDDLE, RED:STRIPE_TOP, WHITE:STRIPE_BOTTOM, BLACK:STRIPE_MIDDLE, WHITE:CIRCLE_MIDDLE`

banner-meta was added to the items.yml for the banner item and support these types and colors;
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/banner/PatternType.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html

This will be added in v4.6 however I will be pushing a snapshot with this feature added here soon if you are interested.

Thanks for requesting this feature!

**Comment by RockinChaos** [comment]
Added as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
