### ISSUE TITLE
Ticking Player

### ISSUE THREAD

**Issue by PinoyLifeCraft** [RockinChaos/ItemJoin#141]
Story Time! xD

I woke up early to play on my Server ( 6:00 AM ) then 9:00 AM I go bath and ganna go fast! xD but 1:00 PM I go home then check the server...
The server's looking good but I've noticed my server's file I saw a **crash-reports** so I've checked it and saw this message...

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 9/21/17 9:49 PM
Description: Ticking player

So this is my error file ([click me](https://hastebin.com/eziwoqofuw.hs))
And this is my log file ([click me](https://hastebin.com/elacuzubew.vbs))

**Comment by RockinChaos** [comment]
Can you send me your items.yml in a paste/haste bin please.

**Comment by PinoyLifeCraft** [comment]
What the 😮  am I dreaming? I assumed you're an American that in my time you are currently sleeping xD God... You're so active, anyways here's my **items.yml**

https://hastebin.com/pehopovoqi.pl

**Comment by RockinChaos** [comment]
Yeah, its midnight where I am now, Keep in mind I have full-time college as well so yea.... I am very active for everything I do. I treat my projects as if they were my actual jobs, even though I don't get paid haha.

Your items.yml looks to be properly set up.
If you wouldn't mind, could you send me your servertip.png? You don't have to if you don't want to, I am trying to see if its 128x128 pixels. Also, your servertip.png is located under /plugins/ItemJoin/ right? Like in the ItemJoin folder itself with the YAML / Config files?

**Comment by PinoyLifeCraft** [comment]
And this is my picture that I am using on my offhand map located at Server/plugins/ItemJoin
Size : 12x128
![servertip](https://user-images.githubusercontent.com/13610530/30682828-e5781d0c-9e5f-11e7-8514-14c3d6c52e9b.png)

**Comment by RockinChaos** [comment]
That timing haha

**Comment by PinoyLifeCraft** [comment]
Yes, I was shocked I thought my comment will not be posted xD cuz it hang and freeze the site. but I was wrong :3

**Comment by PinoyLifeCraft** [comment]
Yes, sir!

I am using ItemJoin v4.5
Spigot 1.12.1

`21.09 03:21:17 [Server] INFO This server is running CraftBukkit version git-Spigot-edd0396-2a927e8 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT) 21.09 03:21:17 [Server] INFO Checking version, please wait... 21.09 03:21:17 [Server] INFO You are 25 version(s) behind`

**Comment by RockinChaos** [comment]
Hmm, something must have changed in spigot 1.12.1 that I did not catch. I will continue to look into this and post back within 12 hours with my results. Either way, the "bug" with crashing was resolved I just want to know if I can prevent it and if the image being null is a latency issue which allows the map to continue to stay rendered and is not a problem to worry about... Hmm.. 

Anyways Ill post back soon with my findings, and once I do I will compile a v4.6 snapshot and post it to the Jenkins server for ItemJoin. (See Jenkins server here; http://ci.craftationgaming.com/job/ItemJoin/)

**Comment by RockinChaos** [comment]
Looks to have been an error with Bukkit/Spigot, all I had to do was make it check if the image was null or not and to not continue the code if it isn't. 

Seems to be working great for me now you can get the fixed snapshot here; http://ci.craftationgaming.com/job/ItemJoin/lastSuccessfulBuild/artifact/target/ItemJoin-4.6-SNAPSHOT.jar

**Comment by PinoyLifeCraft** [comment]
Hello there @RockinChaos ,

Ahm I am not using your snapshot plugin cuz I don't want to use snapshot xD or maybe their are other reason xD but I reply here cuz of this >

When I stay at my server hub where the MAP (ItemJoin) is their and I stay at that world for something or what ever after a min. the map will become empty or empty map it's look like that I am holding a map with no picture xD ..

**Comment by RockinChaos** [comment]
This is without using the snapshot correct?
If it's without the snapshot its still throwing the errors when the map goes blank?

**Comment by PinoyLifeCraft** [comment]
Yes, and here is the latest that I notice ....

In that time I am the only one in that world but after a player join the Map picture works but sometimes it disappear and back to normal xD

**Comment by RockinChaos** [comment]
Since you're not using the snapshot that error is still going to occur.

**Comment by PinoyLifeCraft** [comment]
It's because I'm scared to crash or something what will happen xD

**SNAPSHOT use this at your own risk** 🙁 

But anyways maybe it can help after the map picture back when a player go to the other world the pic will disappear again xD that's why it's 
_Disappear and back to normal and disappear and back to normal xD_

**Comment by RockinChaos** [comment]
If I tell you to use a snapshot its completely safe as I have programmed them. The only difference between v4.5 and v4.6-snapshot is the name as well as the minor bug fix.

As of testing, it looks that the map disappear bug is fixed in the snapshot.

**Comment by RockinChaos** [comment]
Added as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
