### ISSUE TITLE
ItemJoin WorldGuard bug

### ISSUE THREAD

**Issue by DesandNate** [RockinChaos/ItemJoin#142]
Hey, fantastic plugin!
I have an issue that stems from the 'region-enter' part of the item I am trying to give.
essentially, I want a player to receive a book every time they enter my HUNGERGAMES hub to explain the game-type, and then remove it as soon as the player leaves the region. THIS WORKS, HOWEVER: it also is removing the 3 other 'ItemJoin Items' when leaving the region. not sure if maybe theres a work-around for this, but let me know!

**Comment by RockinChaos** [comment]
Would you mind posting your items.yml in a pastebin.com and sending me the link, please? I want to use the config you are using to test it.

**Comment by DesandNate** [comment]
Yes, thanks for the quick response. Here it is: https://pastebin.com/VcBKUafz

**Comment by RockinChaos** [comment]
Sweet I will begin bug testing this and I will report back once I have more information

**Comment by DesandNate** [comment]
Great! im not even really convinced its a bug, I might just be overlooking something, but I've tried almost every work around I can imagine. Thanks again

**Comment by RockinChaos** [comment]
Can confirm this looks to be a bug. I will have a bug patch out soon for it.

**Comment by RockinChaos** [comment]
Fixed and waiting for the update, if you want to get the fix now you can download the snapshot or wait for v4.6 to be released.

If you want the snapshot it is located here on our Jenkins repo; http://ci.craftationgaming.com/job/ItemJoin/54/

**Comment by RockinChaos** [comment]
Fixed as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
