### ISSUE TITLE
Issue: PlaceHolderAPI Bug, doesnt work.

### ISSUE THREAD

**Issue by tom2090** [RockinChaos/ItemJoin#144]
Hello, i've got a 1.9.4 minecraft server running on spigot, and when i'm trying to do a item with some PAPI variables, it doesnt work.
Screen: https://image.noelshack.com/fichiers/2017/41/3/1507733218-2017-10-11-16-45-44.png

Code:

stats2:
    id: SKULL_ITEM
    name: '&6&nStatistiques'
    skull-owner: '%player%'
    data-value: 3
    lore:
      - '&7Temps joué: &b%playtime_time%'
      - '&7Joueurs tués: &a%killstats_kills%'
      - '&7Morts: &c%killstats_deaths%'
      - '&7K/D: &a%killstats_kdr%'
      - '&7Rang global : &e%killstats_kdrrank%'
      - '&7'
      - '&7Tokens: &e%tm_tokens%'
    slot: 9
    itemflags: item-store, unbreakable, hide-attributes, death-drops, self-drops, inventory-modify
    triggers: respawn, world-change
    permission-node: 'itemjoin.ultra'
    enabled-worlds: Skypvpmap

Help !

**Comment by RockinChaos** [comment]
Make sure placeholderapi is set to true in the config.yml 

Also you could be seeing this issue because you need to download vault-extention from the cloud, you can do this by typing /papi ecloud download Vault. PlaceholderAPI will then download this extension and you will need to restart your server for this to take effect, now any vault placeholders will work!

If you need other extensions just look through the list /papi ecloud list all.

**Comment by tom2090** [comment]
It works, thanks you.

BUt there's another problem you need to fix (if u can)

TokenManager doesnt apply its variables. It doesnt work.

**Comment by RockinChaos** [comment]
You mean into the lore correct? %tm_token%?

**Comment by tom2090** [comment]
Yes

**Comment by RockinChaos** [comment]
Can you link me to where you are getting %tm_token% from? This isn't an ItemJoin issue its a config issue on one of the other plugins.

**Comment by tom2090** [comment]
https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/

Anyways, if there's no solution, I change the token system, the variable doesnt work with DeluxeMenus too. Problem from the dev of tokenmanager.

**Comment by RockinChaos** [comment]
Makesure you did /papi ecloud download TokenManager

If it still doesn't work then its definitely the dev's issue.

**Comment by tom2090** [comment]
Yea i did

**Comment by tom2090** [comment]
i

**Comment by tom2090** [comment]
I cant find any plugins like tokenmanager supporting placeholder :(

**Comment by RockinChaos** [comment]
Then its definitely a TokenManager problem. I could only suggest contacting the dev.

**Comment by tom2090** [comment]
Okay i will do it right now thks.
