### ISSUE TITLE
"Placement" flag broke

### ISSUE THREAD

**Issue by Lizardz** [RockinChaos/ItemJoin#147]
The flag "placement" to where people can't place the item, isn't working. 
Here's my items.yml: https://hastebin.com/utohuvidom.php

**Comment by RockinChaos** [comment]
This is known to be buggy on skulls at the moment, its an issue with Mojang. However, a bug fix was released in 1.12.2 Minecraft that implemented a new skull method thanks to spigot! I have added this new skull method into ItemJoin v4.6-SNAPSHOT so if you are looking for an immediate fix you can use a snapshot of ItemJoin. 

This bug also occurred in later versions of Minecraft, however, this implemented fix obviously didn't get to those versions of Minecraft so I added a small workaround to prevent skulls from being placed in those versions as well using the old method.

**Comment by RockinChaos** [comment]
Fixed as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
