### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Luky584** [RockinChaos/ItemJoin#148]
Hello, i sometimes have this error in console when player joins. 

ItemJoin version 4.5 
CraftBukkit version git-Spigot-7d78b81-d5e7885 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) 
Configs: 
https://pastebin.com/HXgDbiBd
https://pastebin.com/0LxQuzSX
error: https://pastebin.com/E2TDt0nx

**Comment by RockinChaos** [comment]
Thanks for the report! This bug has been fixed and will be available once ItemJoin v4.6 is released.

**Comment by Luky584** [comment]
Thanks! Plugin works fine, just that keeps spamming my console. (I have already deleted it with ChatControl)

**Comment by RockinChaos** [comment]
Fixed as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
