### ISSUE TITLE
Cooldown on fireworks? [Question]

### ISSUE THREAD

**Issue by Nesseley** [RockinChaos/ItemJoin#150]
How do I make a cooldown on a firework? As it is not a command I dont think the "commands-cooldown" works for this

What I want to happen: The player can send 1 firework ever 1 seconds.
What happens: the player can spam as many fireworks as he likes.

https://pastebin.com/0fxx2q2k is my items.yml for the firework

**Comment by RockinChaos** [comment]
There is currently no feature that allows you to modify the usage of an item's default abilities. I will look into trying to add this, I am not sure how long it will take though as I am pretty sure I will not be able to implement this using an already created structure in ItemJoin, it will end up becoming a new code structure in and of itself.

**Comment by RockinChaos** [comment]
I have added this to the latest snapshot and will be available when v4.6 is released, It is an option you can put on an item called use-cooldown. The time is calculated in seconds.

Example;
`use-cooldown: 3`

The example shown was a 3 second cooldown and the players will have to wait 3 seconds to use the item again.

**Comment by RockinChaos** [comment]
Added as of ItemJoin v4.6 and it has been released!
Get it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202495

Please read the changelog as the documentation has not been updated yet; https://www.spigotmc.org/wiki/recent-changes
