### ISSUE TITLE
Items equipping when rightclicked.

### ISSUE THREAD

**Issue by Nesseley** [RockinChaos/ItemJoin#152]
Version of ItemJoin: 4.6
Spigot: 1.12.2

If I use a iron-boot as a item, when right clicking they will put the item on their feet, same with elytra. How can I do so right clicking only does the command and not equippes the item?
They loose the item completly when rightclicking as the items goes on as armour.

**Comment by RockinChaos** [comment]
Using the itemflag **cancel-event**s seems to work nicely.

cancel-events - Prevents player from opening a chest while this item is in hand or any open-able items. Useful for canceling the event of opening a book to set custom book items, or even to prevent specific item movement.

**Comment by Nesseley** [comment]
I still equip the elytra when right clicking. Am i doing something wrong?
https://pastebin.com/MdM1MNiu

I tried adding count-lock and count:1 but the elytra still dissapears

**Comment by RockinChaos** [comment]
Lol I got the email but I presume you fixed it as I dont see the comment. You were putting it under command-type instead of itemflags.

**Comment by Nesseley** [comment]
Yes, i noticed haha! Thanks anyway ^^
