### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by joeymaeuslp** [RockinChaos/ItemJoin#156]
Could not pass event PlayerJoinEvent to ItemJoin v4.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.PlayerList.onPlayerJoin(PlayerList.java:296) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.PlayerList.a(PlayerList.java:156) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.LoginListener.b(LoginListener.java:144) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.LoginListener.c(LoginListener.java:54) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:231) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.ServerConnection.c(ServerConnection.java:148) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:811) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot1-8-8.jar:git-Spigot-870264a-0a645a2]

**Comment by RockinChaos** [comment]
Please update your ItemJoin, v4.0 has several bugs that were patched in later versions.

We are now on v4.7; https://www.spigotmc.org/resources/itemjoin.12661/download?version=202738

**Comment by joeymaeuslp** [comment]
great support i will test it

**Comment by joeymaeuslp** [comment]
ok plugin works perfectly thank you

**Comment by RockinChaos** [comment]
Np. Thanks for contacting me first and not leaving your issue in the review, it means a lot!

**Comment by joeymaeuslp** [comment]
i have a next error

**Comment by joeymaeuslp** [comment]
it is from my own plugin sorry

**Comment by RockinChaos** [comment]
oh okay. I'm always here if you need me. Feel free to open another bug report if you have any other issues. :)

**Comment by joeymaeuslp** [comment]
I'm also a developer writing plugins and Pc programs can test my plugins synonymous times https://www.spigotmc.org/resources/bansticks.51784/

I think you are cool you have good support your plugins are made with love something I am glad if one of its plugins also offers free to help server owners I also offer my plugins for free to the best excuse that my English is not so good come from Germany

**Comment by RockinChaos** [comment]
Thanks for the kind words, I try to provide a quick and helpful support as I can. I try to give a premium resource experience to a free resource if that makes any sense xD

**Comment by joeymaeuslp** [comment]
I think it's good that there are also people like you and me who are just so fun at coding

**Comment by joeymaeuslp** [comment]
i have a question what is the command type interact

**Comment by RockinChaos** [comment]
Interact = left click / right click air & blocks.
Inventory - Any inventory actions / clicks.

**Comment by joeymaeuslp** [comment]
ok nice

**Comment by joeymaeuslp** [comment]
can i make i item for all worlds?

**Comment by RockinChaos** [comment]
Yes, you can define one item, then under enabled-worlds put All or Global.

`enabled-worlds: All`
or
`enabled-worlds: Global`

You can even just define every specific world.

`enabled-worlds: world, world_nether, world_the_end`

**Comment by joeymaeuslp** [comment]
ok thanks

**Comment by joeymaeuslp** [comment]
your plugin is verry verry advanced :)

**Comment by joeymaeuslp** [comment]
is it in Seconds or in ticks ? delay: 10

**Comment by RockinChaos** [comment]
Yeah, I am planning in the next update to create a GUI that opens up via /itemjoin menu
To allow users to create items in-game. Showing all available options so its a lot more user-friendly. 
It will contain everything to the point that you won't ever need to open the items.yml

The delay is time in **seconds** until the items are given.

**Comment by joeymaeuslp** [comment]
ok with a gui is the plugin unique makes the best so that you can also set the flags in the gui so you have better config options and one more question can you change the no permissio message for items?

**Comment by RockinChaos** [comment]
All of the options that are available to be put in the items.yml will appear in the GUI once it is created. So literally every itemflag, trigger, command, etc.

You can change any messages that ItemJoin outputs in the en-lang.yml. You can even remove it by just removing the text for the identifier.

**Comment by joeymaeuslp** [comment]
ok that with the gui sounds interesting and complicated if you need help doing so I can help you I program but only 3 years ago

**Comment by RockinChaos** [comment]
I have the GUI mostly finished. Just working on polishing it. And trust me... it is so.. complicated xD
But it looks really nice on the user's end.

**Comment by joeymaeuslp** [comment]
that sounds good only to fix small errors that fix is ​​always the most work xd

**Comment by joeymaeuslp** [comment]
have you a minecraft server?

**Comment by RockinChaos** [comment]
Yeah, I also host mc servers.

**Comment by joeymaeuslp** [comment]
can i have the ip-adress please

**Comment by RockinChaos** [comment]
Its a still in-development server but the ip is play.planetcraftation.com

**Comment by joeymaeuslp** [comment]
ok i will join now

**Comment by RockinChaos** [comment]
I'm not home atm so I wont be on.

**Comment by joeymaeuslp** [comment]
ok then i come over another time and see if you are on my ingame name is JoeyPlayzTV

**Comment by RockinChaos** [comment]
Ah okay, got it :)

**Comment by joeymaeuslp** [comment]
my Minecraft server is proxysocke.net I use this server to gamble and to test my plugins it is a public citybuild server I have download plugins on it which is not bad
