### ISSUE TITLE
How can i use Sub ids

### ISSUE THREAD

**Issue by joeymaeuslp** [RockinChaos/ItemJoin#159]
how can I use subids for items like ID: 123 SubID: 22 to have colored wool, for example

**Comment by RockinChaos** [comment]
Example;
`items:
  ultra-item:
    id: 123
    slot: 0
    data-value: 22`

Simply add data-value to your item and specify the SubID.

You can read more about how this works here; https://www.spigotmc.org/wiki/itemjoin-getting-started/

**Comment by joeymaeuslp** [comment]
ok thanks
