### ISSUE TITLE
ItemJoin w'ont open ChestCommands menu

### ISSUE THREAD

**Issue by FaNt4zMa** [RockinChaos/ItemJoin#16]
Hi, the problem is when I right click my items, it says Unknow command... How to fix please ? ItemJoin is way better than CustomJoinItems and I d'ont want to come back to it... Sorry for my bad english, I'm french canadian :x

**Comment by FaNt4zMa** [comment]
Hi, i found the problem... Instead of using the command to open the ChestCommands menu, (eg. ur menu is called games and the command to open it is /games) use the following command: cc open <Menu_name>. Hope this helps, I searched 30 minutes for this little issue... xP

**Comment by RockinChaos** [comment]
Sorry for the late reply, (personal problems). Yeah that's something I dislike about ChestCommands. Later into the future I will be creating my own ItemsGUI plugin, but until then I have to deal with ChestCommands.
