### ISSUE TITLE
Multiverse invernories console spam problem

### ISSUE THREAD

**Issue by Luky584** [RockinChaos/ItemJoin#160]
I have spam in my console when players joins, I know, its problem of multiverse, but it is possible to change way of saving itemflags?
I dont know about any problems with it. I have just spam in my console.
This happens only when i have itemflags on items.

Thanks for your awesome support.

ItemJoin 4.6
Multiverse-Inventories version 1.4 

CraftBukkit version git-Spigot-7d78b81-d5e7885 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) 

3.) What is the problem that you are having?
Errors: https://pastebin.com/Fj0MigiD
Config: https://pastebin.com/x2uDKfSe

**Comment by RockinChaos** [comment]
This error has nothing to do with ItemJoin, if a player gets certain items in their inventory it will throw those errors regardless of ItemJoin being installed or not.

Multiverse-Inventories as of MC 1.10 has become unsupported. I would suggest moving to PerWorldInventory. https://www.spigotmc.org/resources/per-world-inventory.4482/

**Comment by Luky584** [comment]
Ok, thanks.

**Comment by RockinChaos** [comment]
Sorry, also there is no way of me changing how itemflags are handled because its all done through bukkit/spigot's API.

**Comment by Luky584** [comment]
Ok, no problem :)
