### ISSUE TITLE
ItemJoin compass 1.8

### ISSUE THREAD

**Issue by Divinsens** [RockinChaos/ItemJoin#168]
1.)  v4.7
2.) PaperSpigot 1.7-1.8
3.) When i join in the server it give me a unknown block instead of the compass. This only happens in 1.8, in 1.7.10 gives me the compass.
4.) ITEMS: https://pastebin.com/EVz6QJ9y                  CONFIG: https://pastebin.com/i4E4VXWj
5.) No errors

**Comment by RockinChaos** [comment]
Remove     data-value: 1

Compass's do not have a data value. That will fix it. Sorry for the late reply, I am without internet for a few days.
