### ISSUE TITLE
ItemJoin only works when player is an Op

### ISSUE THREAD

**Issue by doublespaces** [RockinChaos/ItemJoin#17]
So I have gotten the mod figured out. I can make the items I want appear in the slots I want. The issue, is that it only works for Ops and I have no idea where any of the permission commands are used, there is no file, they aren't recognized as commands, etc. Please help, Thanks a lot!

**Comment by RockinChaos** [comment]
I'm a little confused on what you mean, "mod"?

For permissions see: http://dev.bukkit.org/bukkit-plugins/itemjoin/pages/commands-and-permissions/

For more help see: http://dev.bukkit.org/bukkit-plugins/itemjoin/pages/documentation/

The permissions for players to get the items would be
itemjoin.YOURWORLDNAMEHERE.* <--- To get ALL items defined for the world. Hense the *.
or
itemjoin.YOURWORLDNAMEHERE.# <-- # being the slot number item you want to get. You would have to add this permission with the number for each slot you want to get.

**Comment by doublespaces** [comment]
I don't understand what that is. These permissions, where are they supposed
to be used? Typed? Saved? If you are assuming I have console access, I
don't. I running ubuntu server with spigot running as a service so I don't
have console access.

**Comment by RockinChaos** [comment]
Okay now you lost me. Do you not have a permissions plugin?? This is essential for literally ANY plugin to work.

http://dev.bukkit.org/bukkit-plugins/bpermissions/

Use the videos on the page for help setting it up but in essence under a group you need to define the items permissions.

**Comment by doublespaces** [comment]
I installed PermissionsEX and removed it since I didn't fully understand
it, but I"ll install this plugin and go from there. That makes a bit more
sense now since I had no idea how to use those permissions before.

**Comment by doublespaces** [comment]
Wow, so that bPermissions plugin open a whole can of worms. You can't just
install one plugin can you? So I've since moved away from
bPermissions(Because I didn't realize that you had to delete all the
whitespace when editing YAML files) and i've also switched to PEX and
things are finally starting to move along. Thank you for pointing me to the
permissions concept/plugins as I was completely lost on that one. What are
your thoughts on the Sponge/Spigot situation? Are you intending on making
that transition? Thank you for your time as a developer. My son and his
friends have been enjoying this server greatly.

**Comment by RockinChaos** [comment]
Yep but is 100% necessary. PEX will work just fine. No problem. Hope you get things figured out okay. ItemJoin works 100% on spigot and should work on Sponge, there is no reason it shouldn't, if that's what you are meaning. You have a fantastic day!
