### ISSUE TITLE
Help Me Please

### ISSUE THREAD

**Issue by saeedalsnfawy** [RockinChaos/ItemJoin#170]
1.) v4.7
2.) Spigot 1.8.8
3.) https://imgur.com/a/La7AR
4.) https://pastebin.com/uq9zA8vd

**Comment by RockinChaos** [comment]
Please use the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/107/artifact/target/ItemJoin-4.8-SNAPSHOT.jar

This should fix your issue, **if it does not** please post your items.yml and config.yml in a pastebin.com and send me the link.

**Comment by RockinChaos** [comment]
ItemJoin v4.8 has been officially released containing this bug fix for official usage.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=223327

Please read the changelog as the documentation has not been updated yet; 
https://www.spigotmc.org/wiki/recent-changes
