### ISSUE TITLE
[bug] Can't prevent placing skull & put item into item-frame

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#178]
ItemJoin version: 4.8
Server Type: Spigot
Server Version: CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[Bug]
1. Can't prevent placing skull by using item flags "placement".
2. Can't prevent putting item into item-frame by using item flags "placement" and "inventory-modify".

**Comment by RockinChaos** [comment]
Already fixed in the latest snapshots; http://ci.craftationgaming.com/job/ItemJoin/129/

**Comment by RockinChaos** [comment]
ItemJoin v4.9 has been officially released containing this bug fix for official usage.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=233044

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
