### ISSUE TITLE
First Join Not Giving Items If PlayerUUID.dat Does not exist.

### ISSUE THREAD

**Issue by kugick** [RockinChaos/ItemJoin#18]
Hi,
I am having a problem when I wanna give the items to a new player (who connect for the first time on the server). So this is what's happening. When a player join, the server want to know where to spawn the player. By default it use the default world (in server.properties) and when I set the first spawn in the default world, everything work fine. But the problem is that my spawn world isn't the default world. So when the player join, my Essentials spawn teleport the new player in the Spawn world and then the player need to log back in to have the ItemJoin items.

I think this is due to when the player join it create a file (playerdata folder) in the default world and just because I am spawning in another world, the server doesn't understand. 

I can do a short video if you don't understand.

Thx.

**Comment by RockinChaos** [comment]
Yeah, I am a little confused on what you mean.

So, are you trying to get items in a different world than the one you joined in?
If so you can add a modifier for each item that is set to First-Join-Item: true and you would enable first-join in the global.

So it would be like this:

Global-Settings: #// Global Settings, for each world listed under world-list. These will take effect in them. //#
  First-Join:
    FirstJoin-Mode-Enabled: **true**
**
Hub**:
  items:
    1: #// This is the slot, 1 is first slot in hot bar, 36 is bottom right in inventory, 100-103 are the armor slots, 100 being the boots and 103 being the helmet. //#
      id: WOOD_SWORD
      data-value: 0
      name: '&3Junk Sword'
      lore:
        - '&7Yay First ITEM!'
      **First-Join-Item: true**
**      give-on-modifiers:
        - 'world-changed'**
    2:
      id: WOOD_AXE
      data-value: 0
      name: '&5Mr.Axe'
      lore:
        - '&7FIRST JOIN ITEM'
      **First-Join-Item: true**
**      give-on-modifiers:
        - 'world-changed'**

The world-changed modifier allows the first-join-item to be given in that world.
Meaning this is how it would work: Say you spawn in world WORLD (DEFAULT) and you switch to world (HUB) it would give you the items if you have never visited the world HUB.

Hopefully this helped! If I am completely off or you are confused let me know! lol.

**Comment by kugick** [comment]
I have made the changes you proposed to me and this is the result. Sorry for my accent, I am french :)
http://kugick.net/downloads/storages/videos/2016_02_27_15_51_35-ses.mp4

**Comment by RockinChaos** [comment]
Hmmm... Interesting. So when you say you are deleting the file are you deleting the playeruuid.dat? Under the world?

**Comment by kugick** [comment]
In the folder 'playerdata' yes.

**Comment by RockinChaos** [comment]
Okay I will look into this and get back to you.

**Comment by RockinChaos** [comment]
This has officially been fixed as of ItemJoin v2.7. I have done EXTENSIVE testing on this. All I had to do is add a delay to giving the items lol.

**I plan to release ItemJoin v2.7 tomorrow so look out for it!**
