### ISSUE TITLE
[Bug] flags - disposable

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#180]
ItemJoin version: 4.9
Server Type: Spigot
Server Version: CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
------------------------
[Bug] flags - disposable
1. When a item only has left-click command, right-click will remove one of the item.
2. Record + command(right-click) --> right-click a Jukebox --> free command & Jukebox(with Record)

**Comment by RockinChaos** [comment]
Can you please post your items.yml in a pastebin.com link? It would greatly speed up the process of me debugging this issue.

**Comment by momoservertw** [comment]
[https://pastebin.com/ytFbhAQc](url)

**Comment by RockinChaos** [comment]
I have fixed these issues, as well as I found another random disposable bug that has been fixed. You can get the fixed jar file here; http://ci.craftationgaming.com/job/ItemJoin/143/

**Comment by RockinChaos** [comment]
This issue has been officially fixed in the release of ItemJoin v5.0.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=254085

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
