### ISSUE TITLE
bungeecord item

### ISSUE THREAD

**Issue by JoelDeadMach** [RockinChaos/ItemJoin#182]
Hello, i tried to make a join item to a specific server, but it doesn send me. I tried everything, can i have some help with this?

  changepassword:
    id: SKULL_ITEM
    slot: 7
    skull-texture: 'hdb-4010'
    count: 1
    name: '&a&lChange &2&lPassword'
    lore:
      - '&aClick &7To change your password.'
    commands:
      multi-click:
      - 'server: TBL1'
    commands-type: interact
    commands-sound: NOTE_PLING
    itemflags: item-store, death-drops, self-drops, inventory-modify, placement, death-drops, self-drops
    triggers: join, respawn, world-change
    enabled-worlds: 'world'

**Comment by RockinChaos** [comment]
Already resolved in the latest snapshot;
http://ci.craftationgaming.com/job/ItemJoin/144/

**Comment by RockinChaos** [comment]
This issue has been officially fixed in the release of ItemJoin v5.0.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=254085

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
