### ISSUE TITLE
Offhand Item Support

### ISSUE THREAD

**Issue by zocmoc57** [RockinChaos/ItemJoin#19]
Hey for your good awesome plugin can you add offhand issue, when a item are in offhand the command now work, and can you made new slot giving in offhand ? thanks !

**Comment by RockinChaos** [comment]
No idea why its doing that for a command it shouldn't. I have not added support for this and it will be added in ItemJoin v2.6

**Comment by RockinChaos** [comment]
Support for offhand has been added!
