### ISSUE TITLE
not sending players to servers

### ISSUE THREAD

**Issue by DailyStruggle** [RockinChaos/ItemJoin#193]
1.) v4.9
2.) Spigot 1.12.2
3.) Itemjoin is not sending players to servers
4.) https://pastebin.com/QFetxeMA  ,   https://pastebin.com/EhVE0VXD
names of servers are "Survival" and "Skyblock" in  bungeecord config

5.) there are no error codes

plugin dump:
AdvancedBan v2.1.4-RELEASE
AsyncWorldEdit v3.5.4
AsyncWorldEditInjector v3.5.2
AutoSaveWorld v4.15
BannerMaker v1.8.0
BungeePortals v1.2
ChatControl v5.6.8
ConsoleSpamFix v1.5.0
CoreProtect v2.14.2
DecoHeads v1.4
EditableSign v3.3.0
Essentials v2.0.1-b488
HideStream v3.8
ItemJoin v4.9
KeepChunks v1.4.4
LockettePro v2.9.0
LuckPerms v4.0.80
MyCommand v5.3.4
PlugMan v2.1.5
ProtocolLib v4.3.0
Spawntp v2.0.0
SuperVanish v5.10.0
Vault v1.7.1-b91
ViaBackwards v2.3.1
ViaRewind v1.3.13
ViaVersion v1.6.0
VoidGenerator v1.2.0
WorldEdit v6.1.8-SNAPSHOT;cd4729f
WorldGuard v6.2.1;84bc322

**Comment by RockinChaos** [comment]
Already a known issue please update ItemJoin to the latest version.
(v5.0.0) contains this fix; https://www.spigotmc.org/resources/itemjoin.12661/download?version=254090

**Comment by DailyStruggle** [comment]
thanks for the fast response

**Comment by RockinChaos** [comment]
No problem, I will be closing this issue since it is resolved and a duplicate.
Feel free to reopen if you still have an issue!
