### ISSUE TITLE
Unlimited things

### ISSUE THREAD

**Issue by Coolpics127** [RockinChaos/ItemJoin#194]
Hello. How i can add to inventory unlimited items (for example, unlimited snowballs)?

**Comment by RockinChaos** [comment]
https://www.spigotmc.org/wiki/itemjoin-getting-started/

![image](https://user-images.githubusercontent.com/10971577/50708541-88641d00-1019-11e9-8d1a-c6fe2f3a19a5.png)

Simply add the count-lock itemflag to your item.

itemflags: count-lock

**Comment by Coolpics127** [comment]
Alright, thank you)
