### ISSUE TITLE
[Bug] Disposable item will be consumed even if the action is empty

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#196]
Video
https://www.youtube.com/watch?v=BMUSHZipK7g&index=7&list=PLdb2DzWz3uEgL2RjXZTXZaAkk3NV-R4J4&t=0s

config.yml
https://pastebin.com/KfDd3EY0

  test_item:
    id: STONE
    slot: Arbitrary
    name: 'Test Item'
    commands:
      left-click:
        - 'message: &fleft &a✔'
    commands-type: interact, inventory
    itemflags: disposable
    triggers: disabled
    permission-node: 'itemjoin.test_item'
    enabled-worlds: All

ItemJoin version: 5.0.1
Spigot version: git-Spigot-19c3c5a-5932f8a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) (2 version(s) behind)

**Comment by RockinChaos** [comment]
Thanks for the fantastic bug report, it actually makes me happy to see your reports as it is so easy to follow and already set up for testing :D

I got tired of the old ItemCommand pre-requisite check system so I completely rewrote it this time so let's see if it holds up :)

Tested an seems to be fixed, here is a fixed snapshot; http://ci.craftationgaming.com/job/ItemJoin/186/

**Comment by RockinChaos** [comment]
This issue has been officially fixed in the release of ItemJoin v5.0.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=258611

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
