### ISSUE TITLE
[Bug] The item on hand will be disappear after run inventory commands on a disposable item

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#197]
- The items on your hand will disappear (also run commands)
- After the item on the hand disappears, the item on the offhand will disappear.

Video
https://www.youtube.com/watch?v=2ZA_IWjNoqc&t=0s&list=PLdb2DzWz3uEgL2RjXZTXZaAkk3NV-R4J4&index=8

config.yml
https://pastebin.com/KCd4SfYy

  test_item2:
    id: STONE
    slot: Arbitrary
    name: 'Test Item2'
    lore:  
      - 'disposable'
      - 'inventory commands'
    commands:
      inventory:
        - 'message: &finventory click &a✔'
    commands-type: inventory
    itemflags: disposable
    triggers: disabled
    permission-node: 'itemjoin.test_item2'
    enabled-worlds: All
  test_item3:
    id: GLASS
    slot: Offhand
    name: 'Test Item3'
    lore:
      - 'offhand'
      - 'disposable'
      - 'inventory commands'
    commands:
      inventory:
        - 'message: &finventory click &a✔'
    commands-type: inventory
    itemflags: disposable
    triggers: disabled
    permission-node: 'itemjoin.test_item3'
    enabled-worlds: All

ItemJoin version: 5.0.1
Spigot version: git-Spigot-19c3c5a-5932f8a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) (2 version(s) behind)

**Comment by RockinChaos** [comment]
Might I say you a really clever when finding these bugs haha, some things I would have never thought of.

Also tested an seems to be fixed, in the latest snapshot (along with the other bug post); http://ci.craftationgaming.com/job/ItemJoin/186/

**Comment by RockinChaos** [comment]
This issue has been officially fixed in the release of ItemJoin v5.0.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=258611

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
