### ISSUE TITLE
Feature request: Timestamp for first_join items

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#199]
Please add a timestamp for each first_join item, so we can tell when they were granted.

**Comment by RockinChaos** [comment]
Okay, so I think I implemented it how you asked.
I simply used the default Java SQL Timestamp format.

This applies to first-join, first-world, and ip-limit items as well as first-commanded players.

Should see this take effect in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/207/

Note: that obviously I cannot go back in time and put the missing timestamps so the ones that were given before this snapshot will be marked as NULL while others will be given the text timestamp as they are given.

**Comment by SlimeDog** [comment]
excellent. 👍 
I'll test it soonest.

**Comment by SlimeDog** [comment]
Spigot 1.13.2 latest
ItemJoin 5.0.3-b207

Nice! Thanks.
