### ISSUE TITLE
Feature request: softdepend Multiverse-Core

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#201]
Spigot 1.13.2 latest
ItemJoin 5.0.3-b197

Please add Multiverse-Core to softdependencies in plugin.yml:
```
softdepend: [Vault, Multiverse, Multiverse-Inventories, xInventories, PlaceholderAPI, PerWorldPlugins, PerWorldInventory, AuthMe, MyWorlds, TokenEnchant, WorldGuard]
```
Multiverse-Core != Multiverse

**Comment by RockinChaos** [comment]
This feature request has been officially added in the release of ItemJoin v5.0.3.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=262715

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
