### ISSUE TITLE
Add a user definable clear-items delay.

### ISSUE THREAD

**Issue by FakAWg** [RockinChaos/ItemJoin#202]
1.) ItemJoin v5.0.2
2.) Spigot 1.10
3.) When changing the world, it does not eliminate the inventory item, it only does it if the user enters the server
4.) config: https://pastebin.com/NymKV3Uk
    items: https://pastebin.com/0Lp9xM3C

**Comment by RockinChaos** [comment]
You are only trying to clear ItemJoin items correct?

**Comment by FakAWg** [comment]
Yes, and this happened when updating from 5.0.1

**Comment by RockinChaos** [comment]
Not quite sure what you got going on here but the config files you sent me were really messed up.

Try using these files and let me know if it resolved your issues;
Items; https://pastebin.com/giSJBp9g
Config; https://pastebin.com/UkJgr7YD

**Comment by FakAWg** [comment]
Copy the files and reset the server and follow the problem. If I change the "Clear-Items:" to "all" and the same thing happens. When you change the world, it is still there but when you enter, it is eliminated

**Comment by FakAWg** [comment]
Copy the files and reset the server and follow the problem. If I change the "Clear-Items:" to "all" and the same thing happens. When you change the world, it is still there but when you enter, it is eliminated

start: https://i.imgur.com/VAt3A7v.png

**Comment by FakAWg** [comment]
Copy the files and reset the server and follow the problem. If I change the "Clear-Items:" to "all" and the same thing happens. When you change the world, it is still there but when you enter, it is eliminated

start: https://i.imgur.com/VAt3A7v.png
step 1: https://i.imgur.com/u4GTJf9.png
Changing to another world: https://i.imgur.com/Qqz4BdO.png
Returning to the lobby: https://i.imgur.com/aMiL4h6.png
join:  https://i.imgur.com/okIgPTs.png

**Comment by FakAWg** [comment]
I tried the plugin alone and it works well, there must be another plugin interfering, which I imagine surpasses his knowledge

**Comment by RockinChaos** [comment]
So based off the screenshots you provided it looks like a plugin is sterilizing the ItemJoin items causing them to "no longer be recognized". I have seen this once before but I forget what plugin it was, it was as simple as changing a config value to false to stop item sterilization.


EDIT: Ah, didn't see the post above yeah, then its definitely another plugin. An easy way to test this is to use a plugin like (plugman) and disable each plugin one by one until the issue goes away, and then you will know which plugin is causing the issue which then you can edit the config file for that plugin to prevent item sterilization. All it does is prevent plugins from giving players custom items, which I am not sure why that is a feature in some plugins but it is.

**Comment by FakAWg** [comment]
I was deleting plugins hahaha
I found that the error with "perworldinventory" I am using the version "perworldinventory-kt-2.2.2-legacy"

**Comment by RockinChaos** [comment]
Interesting.. I wonder if there is some delay from PerWorldInventory that is causing this.. I will continue testing this, it is possible I might have to add a customizable delay to the clear-items section so ItemJoin can be delayed to clear the inv after PerWorldInventories restores the inventory.

**Comment by FakAWg** [comment]
I hope it can be solved, for the moment I will activate the items-Overwrite.
Tip: Can you create an itemflags to activate Overwrite for item?

**Comment by RockinChaos** [comment]
Okay so after a lot of messing around, I have added a temporary "soft delay" to the clear items.
This is temporary because once the rewrite of the config.yml is done I will add a user-definable that will be the default "soft delay" unless it is changed by the user.

Snapshot; http://ci.craftationgaming.com/job/ItemJoin/201/
Please let me know if it continues to be an issue!

As for the itemflags for specific item-overwriting that is entirely possible, I will put it on my todo list.

**Comment by FakAWg** [comment]
No, sorry

The version of config and item is still 6? since the language change to 7.
I tried and directly does not erase the items or when entering.
I deleted the inventoryperword and nothing changed
Photo: https://i.imgur.com/y49yzd6.png

**Comment by RockinChaos** [comment]
Wait so it still doesn't clear correct even with PerWorldInventory disabled?

**Comment by FakAWg** [comment]
Hi, thanks for fixit it out.
Right now is working perfectly, you really are amazing.

**Comment by RockinChaos** [comment]
This feature request has been officially added in the release of ItemJoin v5.0.3.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=262715

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
