### ISSUE TITLE
Version 7 configuration data not updated

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#203]
Spigot 1.13.2 latest
ItemJoin 5.0.3-b209

I skipped b208, in favor of b209. I manually updated the configuration, and it seems fine. Automatic configuration update does not pick up non-default values. :(

**Comment by SlimeDog** [comment]
I assume that the version 7 config.yml will be clearly documented. I wasn't sure exactly what to do in some cases, so took what looked to be the correct routes.

**Comment by RockinChaos** [comment]
Yeah, it will be clearly documented.

What do you mean by "Automatic configuration update does not pick up non-default values."?
You are saying that if you change a value in the new config it doesn't register?

**Comment by SlimeDog** [comment]
I mean that as a test, I let the plugin convert my version configuration to version 7. T he values I had changed from defaults in version 6 configuration where not transferred to the automatically-updated version 7 configuration.

In my other test, I manually transferred the changes.

**Comment by RockinChaos** [comment]
Ohhh yeah, the version change doesn't transfer the values from the old config file.
I went back and forth on this deciding if it is the right call and I am still kind of debating it. The thing is it leaves open a few security issues with the old configuration data and I don't want to risk data corruption.

I'm still open to suggestions it just becomes the issue of seeming really redundant.

**Comment by SlimeDog** [comment]
Once we see full documentation of the version 7 nodes, it should be fine. I had to make a few guesses, but I'll revisit them when the documentation is posted.

**Comment by RockinChaos** [comment]
ItemJoin v5.0.3 has officially been released.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=262715

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes


You will now see that the changes have been reflected here; https://www.spigotmc.org/wiki/configurations/

If you have anymore questions regarding this please re-open this issue.

**Comment by SlimeDog** [comment]
Thanks. All good.
