### ISSUE TITLE
[Bug] Disposable item's command will run more than one time

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#204]
If server is lagged, the reward command will run more than one time while using a disposable item.
This problem did not happen in old version before (v5.0.1-SNAPSHOT).
Thank you : )

config.yml
https://pastebin.com/0SdjVcD6

video
https://youtu.be/NP00qOG202E

ItemJoin version: 5.0.3-SNAPSHOT (latest, #211)
Paper version: git-Paper-521 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)(latest)

**Comment by RockinChaos** [comment]
Added a "checker" to change the bool value once the item has officially been detected as removed from the inventory.
Tested as functioning properly now; http://ci.craftationgaming.com/job/ItemJoin/212/

**Comment by momoservertw** [comment]
OK, I'll test the new version a little later. : )

**Comment by momoservertw** [comment]
This issue has been fixed in the latest development version, thank you <3

**Comment by RockinChaos** [comment]
This issue has been officially fixed in the release of ItemJoin v5.0.3.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=262715

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
