### ISSUE TITLE
[Bug] Item on hand will disappear if custom item has flags "inventory-modify & disposable" 

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#205]
Only happens when the custom item has both flag "inventory-modify and disposable".
Thank you : )

config.yml
https://pastebin.com/0SdjVcD6

video
https://youtu.be/PQ8eJ0OMFWw

ItemJoin version: 5.0.3-SNAPSHOT (latest, #211)
Paper version: git-Paper-521 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)(latest)

**Comment by RockinChaos** [comment]
My bad was working on some bug fixes for 1.8.8 and I accidentally forgot to add a version switch.
Tested as resolved; http://ci.craftationgaming.com/job/ItemJoin/212/

**Comment by momoservertw** [comment]
OK, I'll test the new version a little later. : )

**Comment by momoservertw** [comment]
This issue has been fixed in the latest development version, thank you <3

**Comment by RockinChaos** [comment]
This issue has been officially fixed in the release of ItemJoin v5.0.3.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=262715

Please read the changelog as the documentation has not been updated yet;
https://www.spigotmc.org/wiki/recent-changes
