### ISSUE TITLE
Item files reseting

### ISSUE THREAD

**Issue by CommanderRE** [RockinChaos/ItemJoin#207]
Hello i am trying to make a minehut server but when I try to edit the original items.yml file it pushes it aside and creates a new original file with all the starting stuff.  It then renames the file to items(random numbers like25428).yml i have no clue why because at first it was working but then I tried making a book and it is now like this.  And it only gives items in the original items.yml file.  By the way I am not very good at scripting.  Thanks in advance.

**Comment by RockinChaos** [comment]
The config files only reset when there are yaml spacing issues. 
If you can post your items.yml (with the number) I can fix it and tell you what is wrong.

OR paste your items.yml (with the numbers) into this link; https://codebeautify.org/yaml-validator
And click Validate. Then it will tell you exactly where the error is.

**Comment by CommanderRE** [comment]
Awesome the codebeautify web page worked thanks!
