### ISSUE TITLE
Player Head

### ISSUE THREAD

**Issue by Toorastic** [RockinChaos/ItemJoin#21]
Hi RockinChaos,

Really love the plugin, find it a lot better then all of the inactive authors that have similar plugins out there.

Just found two slight issues, one I think is just a general 1.9 issue and that is the off-hand slot. People are able to move items around in there inventory by pressing F (or another key bind to place items into off-hand slot). Then pressing F again on another slot to essentially move the item. 

If you could please look into this, it would be much appreciated. It's not a big issue just a bit of OCD with myself that would like the items all where I had planned them to be.

The other issue is with player heads. I do realise that you have put where the download link is in bukkit. That there is a lag issue with players heads. But what I'm finding is that the RIGHT_CLICK_BLOCK for the command actions doesn't seem to work, when trying to run a command from a players skull. 

If you could please look into these two issues for me would be much appreciated, like I said the first one is just a bit of OCD. They can't actually remove items nor duplicate them using this and it goes back to normal after a relog.

Thanks,
Toorastic.

**Comment by RockinChaos** [comment]
Yes I will be looking into all these soon! Sorry for the late reply! Personal issues... I will get you know as I progress on this!

**Comment by RockinChaos** [comment]
Fixed as of ItemJoin v2.6.
