### ISSUE TITLE
[HELP/(?)BUG] Not giving items properly

### ISSUE THREAD

**Issue by insanegyros** [RockinChaos/ItemJoin#215]
Version: 5.0.3
Spigot: 1.13_R2
Problem: Different Item on login is given, but not functioning and also chat message "Failed to give you 1 item..." is showing up all the time. My defined item is Ender eye, but I am given Blazefury with no commands. Also when i move the item, while I have movement disabled, i can move it and when I place it back, it simply disappears.
Settings: https://pastebin.com/ZHrpKWc1
Console output: None

**Comment by RockinChaos** [comment]
I apologise for the delayed reply, I didn't get a notification for some reason.

The issue with item movement was resolved in a snapshot, I would recommend using the latest snapshot as it has been tested and safe to use; http://ci.craftationgaming.com/job/ItemJoin/248/

As for the different item issue, it sounds like the items.yml may have not been saved and /itemjoin reloaded. 

Please let me know if this still continues in the latest snapshot.
