### ISSUE TITLE
Bug: Startup error

### ISSUE THREAD

**Issue by madtomic** [RockinChaos/ItemJoin#216]
I turn on debug to see what error this plugin might have. Here is one on startup.
[19:34:29] [Server thread/INFO]: [ItemJoin] Enabling ItemJoin v5.0.3
https://pastebin.com/n5wzYrap

**Comment by RockinChaos** [comment]
I am 99.9% sure that this is resolved in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/255/

Let me know!

**Comment by madtomic** [comment]
I will report if this issue is not fix.
