### ISSUE TITLE
ItemJoin v2.6 error.

### ISSUE THREAD

**Issue by Toorastic** [RockinChaos/ItemJoin#22]
I'm having this error whenever I try to load it and none of the items are being placed in players inventory on join.

[Server] ERROR Plugin ItemJoin v2.6 has failed to register events for class me.RockinChaos.itemjoin.utils.Listeners because org/bukkit/event/player/PlayerSwapHandItemsEvent does not exist.

**Comment by RockinChaos** [comment]
This is because you have an outdated spigot.

Please run the buildtools.jar again and get the new spigot 1.9 with the commit for the new event. It's because it was litterally added like a day ago.

I assume you are using spigot 1.9?

**Comment by RockinChaos** [comment]
You can also check how outdated your spigot version is by logging onto your server and typing /version

**Comment by Toorastic** [comment]
Yeah, okay thanks will have to contact my server host and ask them to update there spigot.
