### ISSUE TITLE
After login in my server i don't get the items.

### ISSUE THREAD

**Issue by SnakeAmazing** [RockinChaos/ItemJoin#220]
**Once the following information is provided I will reply to you as quick as possible!**
Version 5.0.3
Spigot 1.8
After loging in i don't recive the items.
Config --> https://pastebin.com/iwkQLJWw
items --> https://pastebin.com/P38sib1N
There isn't any errors on the console.

Note: I think that the issue is with my login plugin but i'm not sure. Actually I'm using nLogin.

**Comment by RockinChaos** [comment]
The issue being nLogin would be correct. ItemJoin currently only supports AuthMe which is essentially the same as nLogin. Taking a look at nLogin's page I do not see an available API for me to use which will then give the items (AFTER) you log in via nLogin.

I will do some more digging but I wouldn't be very hopeful in there being a resolution to this. Its probably going to be likely that the author of nLogin will need to implement an API for this.

**Comment by SnakeAmazing** [comment]
Ok, but I tryed to switch to authme but when I run the server I can't talk and I can't place commands to.
Do you know why this happens?

**Comment by RockinChaos** [comment]
That is because you actually have to authenticate yourself. Once you are authenticated it will allow you to talk on the server and execute commands. I would double-check that you setup everything properly via an authme tutorial.
