### ISSUE TITLE
[Request] Drop the items on the ground if the player's inventory is full

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#221]
Hi~ RockinChaos,
Can you add a feature for that?
Because some of my players will complain that the rewards are not getting. ><
Thank you!

<pre><code>
Example.
                    if (player.getInventory().firstEmpty() != -1) {
                        player.getInventory().setItem(player.getInventory().firstEmpty(), item);
                    } else {
                        player.getWorld().dropItem(player.getLocation(), item);
                    }
</code></pre>

**Comment by RockinChaos** [comment]
Sounds like a great idea! I will add this in the next snapshot.

I just need to figure out how to implement it, most likely will become an itemflag.

**Comment by RockinChaos** [comment]
Officially added in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/285/

Works with any defined slot including Arbitrary. Simply add the itemflag drop-full itemflag to the item!

**Comment by RockinChaos** [comment]
This feature request has been officially added in the release of ItemJoin v5.0.4.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=295178

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
