### ISSUE TITLE
Written books show *Invalid book tag*

### ISSUE THREAD

**Issue by ultramizer** [RockinChaos/ItemJoin#222]
**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource.
I'm not sure what the Resource is, i downloaded the latest Version of ItemJoin yesterday.

2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
Latest Spigot Update running 1.14.4

3.) What is the problem that you are having?
I have programmed the items.yml so that every player gets a written book upon joining the server for the first time. This works nicely, However, this book only shows *Invalid book tag* when opening it. The Name and Lore work fine, but not the content of the book. I have not used JSON formatting or any special stuff. Even if i use the default book that comes as an example in the items.yml or the one from the ItemJoin written book documentation, it shows *Invalid book tag*. I have tried searching through old issues on here but didnt find one regarding this. I have googled and have only found issues regarding missing author or not using formatting correctly, but none of those have helped.

4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
Here is the config.yml:
https://pastebin.com/RBKbei0b
Here is the items.yml:
https://pastebin.com/vFRfQy7L
Here's a screenshot of the error in the book:
https://imgur.com/fZ5j336

5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.
There is nothing in the server console!

**Comment by RockinChaos** [comment]
Already resolved over a month ago in the latest snapshot, http://ci.craftationgaming.com/job/ItemJoin/266/

Please reopen this issue if the problem persists.

**Comment by ultramizer** [comment]
Thanks for the link! It works great, sorry for opening the issue!

**Comment by mccarthy995** [comment]
Hello RockinChaos,

The link is not working and I have the same issue. Can you please fix the link, 

Thanks
Tom
