### ISSUE TITLE
Invalid Book Tag for written books 1.14.4

### ISSUE THREAD

**Issue by mccarthy995** [RockinChaos/ItemJoin#223]
https://github.com/RockinChaos/ItemJoin/issues/222

Hi RockinChaos,

Can you repair the link for the latest snapshot please?

I cannot download it to fix the same issue in the link above. 

Thanks
Tom

**Comment by RockinChaos** [comment]
Issue with host, should be back up with in next 24 hours. I will post back as soon as it goes live.

**Comment by RockinChaos** [comment]
Link is live; http://ci.craftationgaming.com/job/ItemJoin/266/

Idk for how long though.. Host pc is on its way out the door, working on getting some funds together to build a fresh one :P

**Comment by mccarthy995** [comment]
Hi RockinChaos,

I got your message, the link has already gone down 😅

Is there another way to download the file? 

Thanks 
Tom

**Comment by RockinChaos** [comment]
Nope, I was trying to snag the file before it went down. If I had a copy of it I could just dropbox it but it died pretty fast. It's built directly off of the github repo though, I am going to pull the drive over the next hour or so and rebuild the jenkins repo on my main computer until I have a reliable server pc.

**Comment by mccarthy995** [comment]
Ok no problem. Good luck, hopefully it goes easy for you.

Good luck, I'll keep an eye out 

Thanks 
Tom

**Comment by RockinChaos** [comment]
Okay, link is live now, it will be up permanently.
http://ci.craftationgaming.com/job/ItemJoin/266/
