### ISSUE TITLE
Invalid Book Tag

### ISSUE THREAD

**Issue by millermx** [RockinChaos/ItemJoin#224]
**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource.
 Latest #266
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
Latest
3.) What is the problem that you are having?
Same problem, invalid book tag #222

**Comment by RockinChaos** [comment]
Confirmed as working in the latest snapshot.

Can you please provide your items.yml in a pastebin.com link.

**Comment by millermx** [comment]
Yes absolutely! 

https://pastebin.com/pqmVQVVe

**Comment by RockinChaos** [comment]
I did some testing and I can confirm that the first book-item is working properly.

However, your Questbook does not have any pages defined so it will always have an invalid book tag unless you define some pages or add the cancel-events itemflag which will prevent the book from being opened -- useful for making it a command executing book via interaction.

**Comment by millermx** [comment]
Ok! Thank you so much for looking into it.

**Comment by RockinChaos** [comment]
Not sure if I am looking at the right quests plugin but it looks like there is an executable command via the quests plugin to open the journal. Which you could simply bind to the Questbook ItemJoin item and it will give it the functionality you are looking for. You'll also need to add the cancel-events itemflag.

**Comment by millermx** [comment]
After a lot of playing around I finally got it. Thank you for all the help. The support has been amazing.
