### ISSUE TITLE
In the tab completer should be included only the main command

### ISSUE THREAD

**Issue by Leonardo-DGS** [RockinChaos/ItemJoin#228]
1.) Vesion: 5.0.4-SNAPSHOT.
2.) Spigot 1.14.4.
3.) In the tab completer, when you type /itemjoin are shown all the subcommands, it's very annoying. It should only include the main command, and once you have typed the space after /itemjoin, you should see the sub commands in the tab completer.

**Comment by RockinChaos** [comment]
*5.0.5-SNAPSHOT doesn't exist.

I'll see what I can do about the tab completion, its an issue on the spigot side not properly listing them so ill likely have to rewrite their tab-completion class.

**Comment by RockinChaos** [comment]
This has been added in the latest snapshot, please let me know if there are any issues.
http://ci.craftationgaming.com/job/ItemJoin/

**Comment by Leonardo-DGS** [comment]
@RockinChaos There is still the issue.
![ItemJoin Bug Screenshot](https://user-images.githubusercontent.com/17832817/65366342-de6a0680-dc22-11e9-8065-fc15ecb7e032.PNG)

**Comment by RockinChaos** [comment]
Doesn't seem to be reflected on my end, can you send me a screenshot of the `/itemjoin` output.

**Comment by Leonardo-DGS** [comment]
@RockinChaos What? That's the problem, subcommands should only compare when you type a space after /itemjoin command

**Comment by Leonardo-DGS** [comment]
![ItemJoin Screenshot](https://user-images.githubusercontent.com/17832817/65373341-85c75780-dc7c-11e9-9742-92aa8e8c1784.PNG)

**Comment by RockinChaos** [comment]
I was asking for you to physically type /itemjoin and hit enter so I could see the version you are running.

The beginning when typing `/itemjoin` is not a part of the tab completion until you hit space after `/itemjoin` the part you are having issues with is the spigot parser. I have simply removed the secondary commands from the plugin.yml so let me know if this change reflects what you are intending; http://ci.craftationgaming.com/job/ItemJoin/300/

**Comment by Leonardo-DGS** [comment]
![ItemJoin Screenshot](https://user-images.githubusercontent.com/17832817/65378861-f55e3680-dcbe-11e9-8106-e261ca6b472e.PNG)

**Comment by RockinChaos** [comment]
Is it working as you are expecting in b300 now? That is a new snapshot from this morning when I changed some command information in the plugin.yml.

**Comment by RockinChaos** [comment]
Okay, this should be resolved now in the latest b301; http://ci.craftationgaming.com/job/ItemJoin/301/
Not quite sure why I couldn't get it to reflect the same way on my end but regardless it seems to be fixed.

**Comment by Leonardo-DGS** [comment]
Yes, now it's fixed, thank you, but you can tab-complete and show the command help even if you don't have permission.

**Comment by RockinChaos** [comment]
Resolved the permission issues; http://ci.craftationgaming.com/job/ItemJoin/302/
I have added each individual permission for each tab-complete & sub commands

**Comment by Leonardo-DGS** [comment]
@RockinChaos There should be a permission even for showing /itemjoin help and /itemjoin command output, and in that case the /itemjoin tab completer should be completely disabled.

**Comment by RockinChaos** [comment]
That would be `itemjoin.use` which is enabled for all players by default.
-- `/itemjoin permissions` is also enabled by default `itemjoin.permissions`

You would have to set the note to false in the permissions plugin for the player groups that you don't want to have access to it.

For example, in LuckPerms the default player group can have the permission `itemjoin.use: false` and `itemjoin.permissions: false` so the permissions are not given to those players.

**Comment by Leonardo-DGS** [comment]
Thank you.
