### ISSUE TITLE
Could not pass event InventoryCreativeEvent to ItemJoin v5.0.5-RELEASE-b324

### ISSUE THREAD

**Issue by joshuasuperboy** [RockinChaos/ItemJoin#235]
1.) Version of the resource is: ItemJoin v5.0.5

2.) Version of Craftbukkit is: craftbukkit-1.14.4-R0.1-SNAPSHOT

3.) Ok so when i try and use the itemjoin configs menu it gives me a null exception. You can see it in the logs of the minecraft server. When i try and use "some" options in the menu it basicly breaks its self. I tried to use version: ItemJoin v5.0.4 and the problem went away. So i know its this plguin that causes it. It said nothing else except for all errors coming from version: ItemJoin v5.0.5. When i tried to use version: ItemJoin v5.0.4 everything then worked fine. My YAML files is provided below along with the log files specifically with the error and the entire logs. For right now i will be using version: ItemJoin v5.0.4 till it gets fixed. The reason why is because version: ItemJoin v5.0.5 breaks its self when using some functions. The thing is every function works great in version: ItemJoin v5.0.4 but not in version: ItemJoin v5.0.5 when only a few functions work and some just flat out breaks the plugin. It only does this with the /itemjoin menu GUI to setup configs on items. When i use version: ItemJoin v5.0.4 however everything works great.

4.) Ok this is all the YAML configs for the Plugin ItemJoin. https://pastebin.com/uhJjE46k

5.) Ok this is all the logs for this error i got from this plugin. https://pastebin.com/XWv0BMPW

**Comment by RockinChaos** [comment]
Sorry about the issue! I did a little digging and noticed it had something to do with modifying items specifically. I was unable to replicate this but I took the given logs you provided and used them to track down the bug.

I am 99% sure that it is fixed in the latest snapshot so please let me know!
http://ci.craftationgaming.com/job/ItemJoin/333/

(If this issue is not resolved) Please provide a detailed example of how you got this error to occur (via steps) Such as; I typed this, then I clicked this, then the error appeared.

**Comment by joshuasuperboy** [comment]
Thank you

**Comment by joshuasuperboy** [comment]
It still breaks its self. Ok this is how to replicate it starting from step one.
1. Go into the ItemJoin Menu GUI by typing /itemjoin menu or just /ij menu.
2. Click Create to make a new item
3. Select a item of your choice it can be any kind.
4. Now that you selected your item of your choice now Click single Slot or Multiple Slots it does this on both.
4. After you have picked Single Slot or Multiple Slot now select a inventory spot to put the item at.
5. Now that you did that now select Animation Settings.
6. Now since you selected that just select Material.
7. Then after you selected that then select New Material.
8. Then after you selected new Material then select any material you want.
9. Then after you do that then select any Duration you want to set.
10. Then lastly click the Return button then you noticed you can then drag around the Return button and everytime you click that button it will show that error. Then what i do is then just close out the inventory then its still broken so then i will have to leave and rejoin back to fix it then reload the plugin.

**Comment by RockinChaos** [comment]
Awesome the provided replication method works perfectly. So the reason this is occurring in v5.0.5+ and not v5.0.4 is because I added backward compatibility support for versions of MC using numerical values. For some reason, the parse method is broken.

I am working on a rewrite of this method and will have a fixed version for you with in the next 24 hours.

**Comment by joshuasuperboy** [comment]
Ok thanks you

**Comment by joshuasuperboy** [comment]
i do have a minecraft server to run and i dont want my players to see my server as a glitchy and buggy one.

**Comment by RockinChaos** [comment]
Okay, this is now fixed in the latest snapshot;
http://ci.craftationgaming.com/job/ItemJoin/334/

I did test it and the error that I got when following your steps has been resolved.

**Comment by joshuasuperboy** [comment]
Ok i tested it and its now working completely fine now.

**Comment by joshuasuperboy** [comment]
I will let you know if i find anything else that broke when you fixed that because normally when you fix things sometimes new problems come up.

**Comment by joshuasuperboy** [comment]
Ok its now stable i tested every single menu feature and everything works now.

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
