### ISSUE TITLE
Как мне ограничить выдачу предмета всем , кроме одного или нескольких людей ? (Админа Сервера) 

### ISSUE THREAD

**Issue by frikiki1** [RockinChaos/ItemJoin#237]
permission всего то запрещает использовать этот предмет но он выдается всем даже игрокам .
А мне нужно что бы группе admin он только выдавался

**Comment by RockinChaos** [comment]
You have to enable in the config.yml Permissions.Obtain-Item to TRUE.
Then it will require permissions for players to get the items.
See; https://github.com/RockinChaos/ItemJoin/wiki/Permissions#itemjoinworlditem
