### ISSUE TITLE
Items always added on Join

### ISSUE THREAD

**Issue by PrivatePrius** [RockinChaos/ItemJoin#24]
I have a list of items set up to give on first-join and respawn event. If a player uses some of these items, then re-connects the items will all be replenished.

Ex: 10 steak on first-join and respawn
I eat 3 steak, reconnect, and then it will give me back the three steak.

Is there an event that has to be disabled to stop it from giving the items on login?

Thank you!

**Comment by RockinChaos** [comment]
Okay first off your global settings look like this right?

Global-Settings:
  First-Join:
    FirstJoin-Mode-Enabled: true
**
Under each item do you have       First-Join-Item: true ?**

Example:

world:
  items:
    first-item:
      id: WOOD_SWORD
      slot: 1
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR
      commands-cooldown: 5
**      First-Join-Item: true**

If you are still having problems please post your config.yml and items.yml in a pastebin.com and link it to me.

**Comment by PrivatePrius** [comment]
Yes, all items have first-join as true

http://pastebin.com/KNPVzg97
http://pastebin.com/tdJC4mYf

**Comment by RockinChaos** [comment]
Hmm weird. Not sure how you are producing this. I literally copied and pasted your config and items.yml into mine and it works fine. 

Are you using spigot 1.9? If you are you fully up to date? Check with /version

Otherwise I will continue to look into this. So weird.. lol I have never seen this before.

**Comment by PrivatePrius** [comment]
Hmm I am on Spigot 1.9, but a few versions behind. Ill let you know if it fixes it when I update.

Thanks!

**Comment by RockinChaos** [comment]
Also please make sure a file called FirstJoin.yml is being created and players names are being stored in it perworld. If you are using linux there could be a permission issue with ItemJoin writing to said .yml file. Just a hunch though. Not really sure lol.

**Comment by RockinChaos** [comment]
Has this issue been fixed for you?

**Comment by RockinChaos** [comment]
If you are still having this issue please download ItemJoin v2.8 and reopen this if you are still experiencing these problems.. Thanks!
