### ISSUE TITLE
How to stop item join from clearing inventories from other plugins.

### ISSUE THREAD

**Issue by orlaaando** [RockinChaos/ItemJoin#240]
## Thanks for taking the time to open a feature/bug request!

**[ Resource Questions / Help and Support ]**
If you have a question or are seeking support for one of my Resources, please make
sure you reply with the proper formatting shown below.

**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource. **I am using v5.0.5**
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC. **Paper 1.14.4**
3.) What is the problem that you are having? **ItemJoin is conflicting with other plugins. Basically I have an anvil GUI being displayed to the user and itemjoin is clearing the pre-set items in the GUI. I would like to know if there is a configuration open to disable clearing of other GUI inventories from other plugins. The way the plugin works is that it sets the items in the GUI inventory after the GUI is opened, and when it does so, it just gets cleared by itemjoin**

**Comment by RockinChaos** [comment]
A screenshot of this would be super helpful if possible. ItemJoin should not be clearing any GUI inventories period. The only events that trigger clearing are join/world change so I am unsure how simply opening a menu would clear the items. I will be bug testing this an report back when I can replicate this.

**Comment by RockinChaos** [comment]
Resolved via Discord.

Snapshot fix; http://ci.craftationgaming.com/job/ItemJoin/351/
Bug; Issues with Crafting Items.

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
