### ISSUE TITLE
[BUG] Could not pass event InventoryClickEvent to ItemJoin v5.0.6-SNAPSHOT-b356

### ISSUE THREAD

**Issue by brnxx** [RockinChaos/ItemJoin#242]
ItemJoin Version : ItemJoin 5.0.6-SNAPSHOT-b356

Version: Paperspigot 1.15.1-R0.1-SNAPSHOT

When trying to click on an item's options in the gui menu

![image](https://user-images.githubusercontent.com/49076883/72922129-3fb5f980-3d2b-11ea-8039-039f235afba2.png)
It also happened when I went to create an item through the MENU.

Link: https://pastebin.com/d3KLzkJ8

**Comment by RockinChaos** [comment]
Sorry for the late response to this,
I was unable to replicate this issue but I think I have formulated a fix for this,
Please try this snapshot and let me know if this resolves your issues: http://ci.craftationgaming.com/job/ItemJoin/358/

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
