### ISSUE TITLE
USE ENDERPEARL

### ISSUE THREAD

**Issue by Infogame** [RockinChaos/ItemJoin#243]
I have a problem is that I have an item with the id ENDER_PEARL and when I go to the server and I do a right click it opens the menu I do with chestcommands and in addition it launches the ender pearl and send me to the targeted place and I would like that when I do a right click it does not launch the ender pearl

**Comment by RockinChaos** [comment]
This should be what you are looking for;
https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#currently-available-itemflags

**cancel-events** - Prevents the player from opening a chest while this item is in hand or any open-able items. Useful for canceling the event of opening a book to set custom book items.

Set `itemflags: cancel-events` to your item to cancel the ender pearl launch event.

**Comment by Infogame** [comment]
Thank you

**Comment by Infogame** [comment]
And also I have another problem is that I cannot do so that we cannot move the item in the inventory

**Comment by RockinChaos** [comment]
Little confused by your question so I am going to interpret it as best as I can.

Inventory-Modify itemflag prevents players from moving the item.
`itemflags: inventory-modify`

or if you have it globally enabled in the config.yml
`Prevent:
  itemMovement: true`

If you are wanting to ALLOW movement simply set the config.yml setting to `false` and remove the inventory-modify itemflag from the items.
