### ISSUE TITLE
Trouble enabling the plugin

### ISSUE THREAD

**Issue by tram2684** [RockinChaos/ItemJoin#244]
I'm using ItemJoin v5.0.5
Using paper 1.12.2
So whenever I try to run the plugin, the console will return with having trouble enabling the file or something.

items.yml: https://pastebin.com/euWwmeBN
config.yml: https://pastebin.com/2SYyDUMN
en-lang.yml: https://pastebin.com/CYN1hZdL

console message: https://pastebin.com/DsRkcgQ5

**Comment by RockinChaos** [comment]
Interesting.. everything looks to be proper.

Can you try the latest snapshot and let me know if this resolves your issue, please?
Link; http://ci.craftationgaming.com/job/ItemJoin/361/

**Comment by tram2684** [comment]
Used the latest snapshot, still doesnt work :/ Console returns with the same error message.

**Comment by RockinChaos** [comment]
Using the exact same version as you;
`This server is running Paper version git-Paper-1617 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

And I cannot seem to replicate this error. Either it is something specific with your server configuration or something is corrupt with your server jar file.

You don't have multiple ItemJoin.jar files in your plugins folder correct?

**Comment by tram2684** [comment]
correct

**Comment by RockinChaos** [comment]
Okay, so I think I am starting to narrow things down. Does this error message occur on START or are you executing an ItemJoin command from the console window that causes this error to occur? If you are trying to execute a command, can you list it, please.

**Comment by tram2684** [comment]
Occurs on start.

**Comment by RockinChaos** [comment]
Okay, so a couple of things.

1.) Try the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/366/
2.) If the error still continues please send me a startup log file so I can see the process in which the error occurs.

3.) (If the error is still occurring); I did some talking with other developers and this error does not seem normal. There is definitely something missing and it looks to be the bukkit library that PaperSpigot imports. It is highly likely that your downloaded jar file of paperspigot is corrupt. Just double-checking with a fresh jar download wouldn't hurt; https://papermc.io/ci/job/Paper/1618/


Let me know!

**Comment by RockinChaos** [comment]
Hey I haven't heard from you in a while, was this issue resolved?

**Comment by RockinChaos** [comment]
Hey I haven't heard from you in a while, was this issue resolved?

**Comment by RockinChaos** [comment]
Marking this as inactive, please reopen this if the issue persists.

ItemJoin v5.0.6 has been officially released.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
