### ISSUE TITLE
Invalid book tag

### ISSUE THREAD

**Issue by ZandercraftGames** [RockinChaos/ItemJoin#245]
**[ Resource Questions / Help and Support ]**

1.) The version of the Resource.
5.0.5-RELEASE-b324
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
git-Paper-105 (MC: 1.15.2) Implementing API version 1.15.2-R0.1-SNAPSHOT
3.) What is the problem that you are having?
Getting `* invalid book tag *` whenever the plugin creates a written book, even using the wiki's example.
4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
https://pastebin.com/M1wuHmsU

**Comment by RockinChaos** [comment]
Already resolved in the latest snapshot a month or so ago.
Link; http://ci.craftationgaming.com/job/ItemJoin/361/

**Comment by ZandercraftGames** [comment]
Thanks :D

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
