### ISSUE TITLE
Jenkins all builds RSS build link error

### ISSUE THREAD

**Issue by rautamiekka** [RockinChaos/ItemJoin#246]
Whenever an RSS (http://ci.craftationgaming.com/job/ItemJoin/rssAll) notification comes in from the Jenkins the address points to an IP on a LAN, making the address useless.

Build 363:
* Wrong: http://192.168.1.201:8180/jenkins/job/ItemJoin/363/
* Right: http://ci.craftationgaming.com/job/ItemJoin/363/

**Comment by RockinChaos** [comment]
Hey, thanks for letting me know. I have resolved the issue (I believe) for me the rssAll appears correctly now. 

Please let me know!

**Comment by rautamiekka** [comment]
How will I check if it works before Jenkins sends another notification ?

**Comment by RockinChaos** [comment]
It should have sent another notification by now as I have pushed a snapshot.

**Comment by rautamiekka** [comment]
> It should have sent another notification by now as I have pushed a snapshot.

Confirmed, works as expected.
