### ISSUE TITLE
Plugin failed to check for updates

### ISSUE THREAD

**Issue by Frusi22** [RockinChaos/ItemJoin#249]
ij updates=> [21:36:34 INFO]: [ItemJoin] CONSOLE has requested to check for updates!
[21:36:34 INFO]: [ItemJoin] Checking for updates...
[21:36:34 INFO]: [ItemJoin] An error has occured when checking the plugin version!
[21:36:34 INFO]: [ItemJoin] Please contact the plugin developer!
[21:36:34 INFO]: [ItemJoin] You are up to date!

help

**Comment by RockinChaos** [comment]
Already resolved in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/363/

Spigot decided to secretly remove their API webpage for checking updates on plugins so I had to resolve the update API.

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
