### ISSUE TITLE
give-on-modifier "spawn" not working

### ISSUE THREAD

**Issue by JackSlacks** [RockinChaos/ItemJoin#25]
Hello!

The give-on-modifier "respawn" does not seem to work with armor and offhand slot. They all go to slot 0.

Also it does not give the right amount of items back you have in a slot depending on count, If you already have the item in the slot, it does not reset count.

**Comment by RockinChaos** [comment]
The give-on-modifier
- respawn
- changedworld

and the count issue have been fixed as of version 2.8 and will be released soon!

**Comment by RockinChaos** [comment]
Fixed and uploaded ItemJoin v2.8. Enjoy!
