### ISSUE TITLE
[Suggestion (Ported from Discord to keep track)] Descriptive Ingame flags

### ISSUE THREAD

**Issue by TheRobLP** [RockinChaos/ItemJoin#252]
Small Quality of Life suggestion for the ingame editors flag selector:

It would be nice to read in the lore what exactly happens when you set a flag, for example

death-drops

True: The item will be destroyed on death
False: The item will drop to the floor on death

**Comment by RockinChaos** [comment]
Hmm in looking into this, doesn't it technically already state what it does when it is enabled in the lore?

![image](https://user-images.githubusercontent.com/10971577/75604618-75b76d80-5a8f-11ea-8c28-2ff6ecdb3f31.png)


Maybe I am missing what you are saying.

**Comment by TheRobLP** [comment]
Technically, yes. But I´ve seen some people (including me at times) getting confused by the states (true/false). For example death-drops : I often confuse the function since logic tells me that if it´s enabled it does drop the item, but in reality the opposite is the case: Destroying the item.

**Comment by RockinChaos** [comment]
Okay try the latest snapshot and let me know what you think;
http://ci.craftationgaming.com/job/ItemJoin/365/

**Comment by TheRobLP** [comment]
Added in #365 and refined in #368. Closing feature request
