### ISSUE TITLE
[Suggestion (Ported from Discord too)] Skript Support and Custom Blocks

### ISSUE THREAD

**Issue by TheRobLP** [RockinChaos/ItemJoin#253]
I have a suggestion for ItemJoin. Tough, its a bit abstract and Im not sure if it would fit for ItemJoin. The ability to create custom blocks with custom effects (commands, potion effects, Skript support, etc.). Also, another idea which I thought about for a while now. I think it would be cool if Items with ItemJoin could have Skript support. This would make it really fun for Players, because of Skripts insanely powerfull abilities.

**Comment by RockinChaos** [comment]
Already "Kind of" a requested feature. I will reference this ticket and the other ticket so that I know to look at them both. See; #236
