### ISSUE TITLE
[Suggestion] "Other Settings" 2.0

### ISSUE THREAD

**Issue by TheRobLP** [RockinChaos/ItemJoin#254]
What I mean by that: More NBT options. For example set a chest to locked, or add items into it with the "Other Settings" option. Or something which is a bit more complex, but a really cool idea: Custom spawn eggs (this may be helpfull if you decide to look into the spawn egg idea:
 https://minecraft.gamepedia.com/Chunk_format#Entity_format ) Adding NBT to custom items would make it much more customizable in my opinion. Thanks for reading :-)

**Comment by RockinChaos** [comment]
Hmm probably should mark this as completed as I implemented this a while ago for a prior ticket on discord.

Snapshot; https://ci.craftationgaming.com/job/ItemJoin/603/

Simply add `properties: 'TranslatableDisplayName:&aUltra &cItem, Slot:33'` to your item for example.
Format; Identifier:Value

See devlog; https://github.com/RockinChaos/ItemJoin/wiki/DevLog

**Comment by RockinChaos** [comment]
This feature has been officially added in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
