### ISSUE TITLE
AuthMe API Error

### ISSUE THREAD

**Issue by brnxx** [RockinChaos/ItemJoin#255]
**Version PaperSpigot:**
![image](https://user-images.githubusercontent.com/49076883/75612001-4d1a8c80-5afe-11ea-9bc8-aed96b340c39.png)
**Version ItemJoin (DevBuilds):**
ItemJoin-5.0.6-SNAPSHOT-b363

**Console Error:**
https://pastebin.com/67NEiwRL
**API AuthME:**
![image](https://user-images.githubusercontent.com/49076883/75612047-d631c380-5afe-11ea-9bfb-5d99374961e5.png)
In the image it says: "Plugin to use nLogin to hook other plugins."

My Login system (nLogin) supports the AuthMe API. But when I activate it, ItemJoin keeps generating this error, sending many messages on the console

**Comment by RockinChaos** [comment]
Okay so I am a little confused how you are running AuthMe v1.2 but you are also running MC 1.15.2.
The latest AuthMe version is 5.6.0; https://www.spigotmc.org/resources/authmereloaded.6269/

If I am misunderstanding it might be helpful to upload the AuthMe jar file you are using here for me to test.

**Comment by brnxx** [comment]
This is my login system .jar (nLogin) 
**Spigot plugin:** https://www.spigotmc.org/resources/nlogin-1-7x-1-15x.57272
**Jar AuthmeAPI:** https://drive.google.com/file/d/1B1lOFOLCFzOjPoX5Ws7K1aIYczd6rvLa/view

If the problem is with the login system plugin, I can contact their support.

**Comment by NickUltracraft** [comment]
@brnxx your nLogin is out of date. Please, update your version: https://www.nickuc.com/#gratuitos

**Comment by brnxx** [comment]
Thank you guys!

**Comment by RockinChaos** [comment]
Haha, I just figured that out. I was wondering why I wasn't getting that error message xD.
