### ISSUE TITLE
Vanilla-control not working

### ISSUE THREAD

**Issue by SeruhioX** [RockinChaos/ItemJoin#258]
1.) The version of the Resource. 5.0.5-RELEASE-b324

2.) Version of the Spigot / Craftbukkit / Cauldron / ETC. PaperSpigot 1.13.2  #624

3.) What is the problem that you are having? Items with the "vanilla-control" flag don't work and show an error, I have also tried in the latest dev build

If the plugin is reloaded with "itemjoin reload" it works correctly.

4.) Post all your YAML / Configuration files, please include a Pastebin.com link.

https://pastebin.com/B3V4FjiT   config
https://pastebin.com/x5WyEQzf  items

5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.

https://pastebin.com/ZmwpnTFF

**Comment by RockinChaos** [comment]
Okay, so I am 99% sure this is already resolved in the latest snapshot.

Let me know; http://ci.craftationgaming.com/job/ItemJoin/373/

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
