### ISSUE TITLE
Inventory-modify numeric key bug

### ISSUE THREAD

**Issue by TheRobLP** [RockinChaos/ItemJoin#259]
ItemJoin version: http://ci.craftationgaming.com/job/ItemJoin/372/

Server software: Paper Spigot 1.15.2 

The problem:

An item with the inventory-modify flag can be placed into any hotbar slot where an item without this flag is persistent, by using the number keys inside the inventory window. Example:

There is a vanilla item in slot 0, let´s say cobblestone. Slot 3 has an ItemJoin item in it, lets say a compass. This compass has the flag inventory-modify on it. By hovering over the compass inside the inventory and pressing 1, it will switch places with this item. However it will NOT switch places with items which also have the inventory-modify flag on it.

I hope I could make it understandable.

Credit for finding this bug goes to "LifeDoesntMatter#0241" on Discord

**Comment by RockinChaos** [comment]
Wow, that's a tricky bug lol.

Resolved in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/373/

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
