### ISSUE TITLE
Hoppers and the Wall O´error

### ISSUE THREAD

**Issue by TheRobLP** [RockinChaos/ItemJoin#260]
## Thanks for taking the time to open a feature/bug request!

**[ Resource Questions / Help and Support ]**
If you have a question or are seeking support for one of my Resources, please make
sure you reply with the proper formatting shown below.

**Once the following information is provided I will reply to you as quick as possible!**

1.) The version of the Resource:  dev version #172

2.) Server Software: Paper 1.15.2

3.) What is the problem that you are having?

Hoppers are broken. I dont really know why, but I do have an error when placing it.

4.) YAML / Configuration: Default generated configs

5.) Error codes: https://pastebin.com/pgb9GG1f

Credit for finding this bug goes to sian2005#9113 on Discord

**Comment by RockinChaos** [comment]
Has nothing to do with hoppers. It is actually a bug resulting from adding the on-equip, un-equip command identifiers in the previous snapshot.

Resolved in the latest; http://ci.craftationgaming.com/job/ItemJoin/373/

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.6.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
