### ISSUE TITLE
Move items

### ISSUE THREAD

**Issue by 3Lord3** [RockinChaos/ItemJoin#261]
1.) ItemJoin-v5.0.5-RELEASE

2.) CraftBukkit version get-Spigot-800b93f-8160e29; API version 1.15.2-RO.1-SNAPSHOT (But I also used the server with PaperMC, there's the same problem)

3.) I used this plugin to lock down the equipment slots. I kind of put in all the necessary flags for the items so that the players can't do anything. But I found a way to move them. If you use the numbers on the keyboard, the item will move to the hotbar, but it doesn't work the other way around. To return the object to its place, you have to die. Is it a bug, or did I not write some flag to the items? Video: https://youtu.be/W9vdC9dhSd8
(There may be errors in the text. I used a translator) 

4.) https://pastebin.com/RzvC3i8v (I didn't change the rest of the files)
5.) https://pastebin.com/zmiM3TjH

**Comment by 3Lord3** [comment]
Ah, I've already figured out that there's a theme to this problem, and it's solved in snapshot

**Comment by RockinChaos** [comment]
Yes, sorry for the runaround, the release of v5.0.6 will be coming out soon.
