### ISSUE TITLE
Dupelication Glitch

### ISSUE THREAD

**Issue by Dziaod** [RockinChaos/ItemJoin#262]
**Once the following information is provided I will reply to you as quick as possible!**
1.) ItemJoin v5.0.5
2.) Paper-235
3.) Inventory Duplication
4.) [config.yml](https://pastebin.com/72WBEYeX) and [items.yml](https://pastebin.com/rMNkRMuF)
5.) None

When a player takes an item and lays out a crafting recipe in the 2x2 inventory crafting table, but doesnt craft the timen and presses esc/e the layed out recipe will be crafted and the player keeps the items.

**Comment by RockinChaos** [comment]
99% sure this is already resolved in a snapshot in the commit e238201 ; http://ci.craftationgaming.com/job/ItemJoin/379/

**Comment by RockinChaos** [comment]
Marking this as answered, please reopen this if the issue persists.

ItemJoin v5.0.6 has been officially released.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
