### ISSUE TITLE
Making written books dynamic breaks click/hover events when the book updates

### ISSUE THREAD

**Issue by resindrake** [RockinChaos/ItemJoin#266]
Using:  ItemJoin `v5.0.6-RELEASE-b395` with Paper `git-paper-143`
When making a dynamic book with click/hover text, the hover text will not appear and the text will not be clickable after the book updates itself. If I give myself a fresh book, the hover/click text will work fine until the book updates.

- [items.yml](https://pastebin.com/iv4KerFM)
- [config.yml (unmodified)](https://pastebin.com/KT7fLyzs)

(No errors in console)

**Comment by RockinChaos** [comment]
Okay so I think this is resolved in the latest snapshot now; http://ci.craftationgaming.com/job/ItemJoin/397/

I was able to replicate this and develop a fix, seems to be working on my end now.

Please let me know, and thanks for reporting this!

**Comment by resindrake** [comment]
Works perfectly now, thanks!
