### ISSUE TITLE
[Support] Missing things from config

### ISSUE THREAD

**Issue by cookieman27** [RockinChaos/ItemJoin#267]
1.) v5.0.6-release-b395
2.) CraftBukkit version git-bukkit-a81f6ed (mc 1.15.2)
3.) There is no option in the config file to enable PlaceHolder api, Multiverse-core/inv and all the other things 
4.) https://pastebin.com/KiS3dENC
5.) nope

**Comment by RockinChaos** [comment]
This is intended, it is automatically enabled when PlaceholderAPI + any other plugin is detected. You will see that it has been successfully enabled on startup.

**Comment by cookieman27** [comment]
Thank you
