### ISSUE TITLE
uninstall item join

### ISSUE THREAD

**Issue by unknown12345678** [RockinChaos/ItemJoin#270]
I was using ItemJoin but then I didn't need it so I deleted the files in plugins but it still gives me the items when I join?

**Comment by RockinChaos** [comment]
Sounds like you still have ItemJoin on your server then.
You need to delete the ItemJoin.jar file or if you are wanting to keep the jar file but disable items being given you need to remove them from the plugins/ItemJoin/items.yml or set each items triggers to DISABLED.

If you are trying to remove the jar file you can confirm if you did this properly as it will not appear when you type `/plugins` in-game. Make sure you also restart your server after making these changes.

**Comment by unknown12345678** [comment]
yea I check the plugins folder the item join file I deleted the folder and jar checked my world with /plugins it says it is still there I have checked the folder while the server was running and item join was not there but I still get the items so I was also wondering if there is a different file some where else or what?

**Comment by RockinChaos** [comment]
Nope, it should be the same jar name unless it was renamed. I am unsure of how your server is hosted so it could be that your host provider changed the name automatically. Considering you can't find it in your plugins folder, it is likely that it has been renamed or hidden. If this is hosted locally make sure you have hidden files enabled in your folder options.

Stupid question but you did /stop and /start your server after removing it correct?
