### ISSUE TITLE
Color codes aren't working.

### ISSUE THREAD

**Issue by JackOUT04** [RockinChaos/ItemJoin#271]
## Thanks for taking the time to open a feature/bug request!

**[ Resource Questions / Help and Support ]**
If you have a question or are seeking support for one of my Resources, please make
sure you reply with the proper formatting shown below.

**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource.
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
3.) What is the problem that you are having?
4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link.

**Comment by JackOUT04** [comment]
1) v5.0.6
2) 1.14.4
3) The color codes aren't working even though they were working before for almost a week.
4) Pastebin link: https://pastebin.com/mkep2sxn
5)

**Comment by JackOUT04** [comment]
I only enabled the items in two worlds, the items work in one world but not the other.

**Comment by JackOUT04** [comment]
Oh no it actually doesn't work in both worlds

**Comment by RockinChaos** [comment]
Since I responded to you in discord I am going to close this issue so I don't keep getting confused about why I haven't responded to this.

If needed please ping me on discord or re-open this issue.
