### ISSUE TITLE
Sometime one of my item stops (player head)

### ISSUE THREAD

**Issue by diamkil** [RockinChaos/ItemJoin#273]
## Thanks for taking the time to open a feature/bug request!

**[ Resource Questions / Help and Support ]**
If you have a question or are seeking support for one of my Resources, please make
sure you reply with the proper formatting shown below.

**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource. v5.0.5_RELEASE-b324
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC. git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
3.) What is the problem that you are having? Sometimes my player head item stops working (executing command) but when disconnecting and reconnecting (getting item again) it works
4.) Post all your YAML / Configuration files, please include a Pastebin.com link. https://pastebin.com/qA50ZdYp
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link. no errors

I got to precise it only happens with the head item and not the others

**Comment by RockinChaos** [comment]
Can you please try downloading the latest version of ItemJoin. I have fixed a lot of bugs in the current update relating to skull-items.
Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427
Recent Changes; https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes

**Comment by diamkil** [comment]
Welp I didn't get chat message for it so I thought it was on latest, I'll test

**Comment by RockinChaos** [comment]
Yeah MD_5 removed the api that checks for updates so I had to switch to a new API handler in the latest update. If the bug still continues can you please post a pastebin of your items.yml

**Comment by diamkil** [comment]
item no longer works at all

**Comment by diamkil** [comment]
Well it works actually but it still sometimes doesn't work

**Comment by RockinChaos** [comment]
Can you pastebin me your items.yml so I can test the item please. The previous pastebin only contains your config.yml that you provided.

**Comment by diamkil** [comment]
https://pastebin.com/5ezvR9XH
and they work on login most of the times, they only but some times

**Comment by RockinChaos** [comment]
I am actually wondering if it was the usage of the %player_name% variable instead of the %player% variable. Also in newer versions aka greater than MC 1.13 the durability 3 does not need to be set as PLAYER_HEAD has that built-in now in the spigot API.

Try this items.yml and let me know if it works; https://pastebin.com/t5cKWiaz

This will break any previously given skull-items so you will need to re-get them but it will be useful to see if that was the issue.

**Comment by diamkil** [comment]
I applied it a few hours ago and no problems since

**Comment by RockinChaos** [comment]
Sweet, let me know if the issue reappears. I will be closing this issue so feel free to re-open it if needed.
