### ISSUE TITLE
ItemJoin when change worlds and multiple itemjoin items

### ISSUE THREAD

**Issue by TheChemist123** [RockinChaos/ItemJoin#277]
v5.0.6-RELEASE-b395

Hi, i am trying to create a minecraft server with multiple worlds, a hub world and a kitpvp world. I have got it so that when i join i get spawned into the hub world i spawn with a compass that when clicked open a navigation GUI made by the CommandPanels Plugin, is there any way to make it so that when i teleport to the kitpvp i can have another item appear in my inventory alongside the compass, the other item would be used as a kit selector so would again be used to open a GUI for kit selecting. Then is it also possible to have it so that once i am in the kitpvp world and have both compass and the kit selector in my inventory to make it so that if i tp back to the hub world that only the compass item appears in my inventory. I assume that this would be very complicated to do so i am really hoping that there is indeed a possible way to do this :/ 

I am also having an issue that when i join the server and have both the kitselector and compass in my inventory they do not seem to respond to the command assigned to them? 

Here is my current code
Kit Pvp world is called " pvp "
Hub world is called " rss "
The tool to open the navigator is the compass 
The tool for the kit selector is the diamond sword

https://pastebin.com/QCuAjjss

Any help on this would be greatly appreciated, i know that it will be hard to do and i really appreciated the time that people put into helping others. I hope that you are all safe and well! Thank you!

**Comment by RockinChaos** [comment]
Thanks for the kind words! Sorry for the slow replies.

There is a way to do this that is a lot simpler.
Start by adding the itemflags `auto-remove` to each item. This way when the item appears in a world it is NOT allowed in, it will be REMOVED automagically.

Then put the enabled-worlds for the compass item that it is allowed in, not what you want to be given in. So it sounds like compass should be allowed in rss and pvp. Then do the same for the kitpvp item but only put it for the pvp.

Lastly, add the following triggers to each item; `triggers: join, world-switch, respawn` (remove respawn if you don't want it given on respawn, only the first two triggers are required).


PS: I would do this for you but we have changed the pastebin items so much I am unsure what they look like for you now.


Examples;
`itemflags: auto-remove`
`triggers: join, world-switch, respawn`
`enabled-worlds: pvp, rss`
