### ISSUE TITLE
Written Books Broken With Latest Update

### ISSUE THREAD

**Issue by ZandercraftGames** [RockinChaos/ItemJoin#278]
1.) The version of the Resource.
5.0.6-RELEASE-b395

2.) Version of the Spigot / Craftbukkit / Cauldron / ETC.
git-Paper-201 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

3.) What is the problem that you are having?
Books are broken even with normal text and display the following image after the latest update: And yes I have cleared my inventory and rejoined.
![image](https://user-images.githubusercontent.com/28664144/79702705-db94ca00-8274-11ea-955f-3c4db3085bcc.png)

4.) Post all your YAML / Configuration files, please include a Pastebin.com link.
Config.yml - https://pastebin.com/25FJLVEm
Items.yml - https://pastebin.com/e3y7W9bF

**Comment by RockinChaos** [comment]
See; https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes

You are using the old method for defining JSON events. These have changed to support new events in the latest update. The link above states this at the beginning and points to the bottom of the page for proper formatting.

Here is the proper formatting (now);
* JSON Books have been re-coded and reformatted.
  * Old JSON Books prior to this update will BREAK unless you add the dynamic itemflag to the item.
  * New JSON formatting is `<TYPE:VALUE>`
  * Current types are `open_url`, `run_command`, `show_text`, and `text`.
  * Replace value with the value of your intention such as a text to be shown or a command to be executed.
  * Example; `<text:I am a clickable hover text component><show_text:Visit the website! \nAnyone is welcome.><open_url:https://www.craftationgaming.com>`



Let me know if you need any help and if this resolved your issue.

**Comment by ZandercraftGames** [comment]
@RockinChaos That was the new config. I deleted mine and let it re-load... I used it based on the new config and customized it based on how the new config was formatted.

**Comment by ZandercraftGames** [comment]
Mkay. Thanks.
