### ISSUE TITLE
Command events

### ISSUE THREAD

**Issue by ThijsSlop** [RockinChaos/ItemJoin#28]
Hey,
Can you add support for command events? e.g. from DeluxeCommands or MyCommand?
Thank you in advance!

**Comment by ThijsSlop** [comment]
And also a feature that items don't drop if you get killed

**Comment by RockinChaos** [comment]
The prevent drops feature has already been added. Its called a prevent-modifier. Its exact name would be **death-drops** and you would set this under each item as such:

      prevent-modifiers: // Prevent players from doing these actions. //
        - death-drops // Prevents players from dropping this item on death. //

Please see http://dev.bukkit.org/bukkit-plugins/itemjoin/pages/documentation/ for more into on prevent modifiers. Its towards the bottom of the page.
 
As for DeluxeCommand and MyCommand, can you be more specific? ItemJoin can already make players execute commands itself and if you define "create" a command under DeluxeCommand or MyCommand just make it so the player runs it on ItemJoin. This is what I did for my server:

Under item one (My compass):

      commands:
        - 'player: compnav'

compnav cmd is a defined command under MyCommand for me that executes another command bossShop open navmenu. (Opens inventory menu)

This can work for anything defined under DeluxeCommand and MyCommand. Even as console! Just use the %player% variable "placeholder".

**Did I answer your questions/requests or did I completely miss what you were saying?**

**Comment by RockinChaos** [comment]
Hey did this resolve your feature request/questions?

**Comment by ThijsSlop** [comment]
Oh yea they're solved now! Thank you!
