### ISSUE TITLE
I cant pickup item. Pls help me

### ISSUE THREAD

**Issue by JackHPGaming** [RockinChaos/ItemJoin#283]
![image](https://user-images.githubusercontent.com/47698119/80784925-d6a31500-8ba8-11ea-8f88-7320369befe0.png)

**Comment by RockinChaos** [comment]
Sounds like you have Prevent.Pickups enabled in the config.yml. Check that it is disabled, that's the only way items cannot be picked up.

If this is still an issue please send your config.yml and items.yml in a pastebin.com link.

**Comment by JackHPGaming** [comment]
its here https://pastebin.com/AMVTZwRh

**Comment by JackHPGaming** [comment]
i turned on but not working

**Comment by RockinChaos** [comment]
Prevent = Not allowed
Pickups = Not allowed pickups.

So you want to disable that not enable it.

https://pastebin.com/Q7yc6Y4X


If that still doesn't work then ItemJoin is not the plugin blocking pickups, it would be another plugin that you could find out by using a plugin like PlugMan and disabling each plugin one-by-one until you can pick up again. Then modify that plugins config.
