### ISSUE TITLE
[Bug] GUI Intended items stop working after opening inventory.

### ISSUE THREAD

**Issue by Gamerexde** [RockinChaos/ItemJoin#286]
Helo,

So I have a small issue, I have 2 Items that opens a GUI, one is for the server selector and another one is the player profile. This works fine until you press E to open your inventory, when you do that your inventory opens, but quickly switches to the GUI, not a big deal you might say just close the inventory, wrong. 

Everything seems fine until you press the item to open again the inventory, the items no longer works (any items that opens the GUI). Strangely it only works for items that opens a GUI, the rest are items that execute commands, and they work fine.

The GUI for server selection is from DeluxeMenus, and the profile GUI is a custom plugin created by me.

I don't know if this is a bug or a misconfiguration issue, but I've never experience this with older  versions of ItemJoin. 

PD: If you think is my custom plugin who is creating the issue, well I disabled the plugin and the bug still happens, so I discart that a bug in my code can be causing the issue.

Thanks!

Server & Plugin Info:

Server Base: Spigot 1.8.8-R0.1-SNAPSHOT (Latest build)
ItemJoin: v5.0.6-RELEASE-b395

Config File for items: https://pastebin.com/baeqhfPe

**Comment by Gamerexde** [comment]
Video with the bug in more detail.
https://www.youtube.com/watch?v=00beHKEQwDo

**Comment by RockinChaos** [comment]
Okay so, I have done some extensive bug testing with this and I was able to replicate it in b395 (v5.0.6 release). As of the latest snapshot, I cannot seem to replicate it anymore. 

If you feel comfortable doing so, I would suggest testing it so I can confirm this resolution.
Snapshot; http://ci.craftationgaming.com/job/ItemJoin/411/

Also, I did notice some config issues (missing spaces) in the Pastebin you provided. It was specific to the MAP item, PAPER item, and SKULL item commands. It is possible this happened by simply copy/paste into Pastebin. Regardless here is a fixed items.yml if you still have that issue; https://pastebin.com/jQfgJnn7
Also, an easy way to test this is to paste your config into here and wait for errors; http://yaml-online-parser.appspot.com/

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
