### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Tomigames** [RockinChaos/ItemJoin#291]
Hi I am running into the following issue, 
https://hastebin.com/tosugefuhe.bash

**Comment by RockinChaos** [comment]
I think you are the same person from the discord, I am going to add a try/catch to send a console message for admins to remove the RANDOM or ALL commands-sequence when both are defined.

**Comment by RockinChaos** [comment]
Okay, so I have pushed a snapshot that addresses this issue.

Something I didn't notice is that you defined both ALL and RANDOM which caused the bug, something I forgot to note is that ALL is not a valid commands-sequence. 

The available sequences are; SEQUENTIAL, RANDOM_SINGLE, RANDOM_LIST, RANDOM.

Sequential is the one I meant to tell you to set it to. If you define a command without a commands-sequence, this is the default sequence selected.

The snapshot that addresses this issue; http://ci.craftationgaming.com/job/ItemJoin/415/

**Comment by Tomigames** [comment]
Thank you, After you responded on discord that I was able to make it work.
