### ISSUE TITLE
Please add Russian localization.

### ISSUE THREAD

**Issue by s-pavel77** [RockinChaos/ItemJoin#293]
## Please add Russian localization.

If you have the opportunity, do it. At least add to the plans. Thank you.

**Comment by RockinChaos** [comment]
I would be happy to add this, however, the localizations that are being added to ItemJoin are translated by people who actually speak the language natively. So I will have to wait or try to find someone who understands Russian to translate the whole en-lang.yml so I can add it to the localization.

**Comment by s-pavel77** [comment]
If you imagine that there is a native speaker who will translate the text. What needs to be done so that the translation file is included in the plugin repository?

**Comment by RockinChaos** [comment]
Haha, all that needs to be done is the message text for each of the messages in the en-lang.yml needs to be translated. The "Nodes" stay in English text so that they can be easily fetched by the plugin. 

This is what needs to be translated; https://github.com/RockinChaos/ItemJoin/blob/master/files/locales/en-lang.yml

By node for example, I mean `failedOverwrite` stays as an English text, but the message following that gets translated. Hopefully, that makes sense let me know if it doesn't.

**Comment by Hacker220** [comment]
Hello, I translated the plugin into Russian. But crooked. Here is the link: http://surl.li/dnrf
Sorry, but I didn’t figure out how to change the language in the plugin
Sorry, but I don't speak English very well
-----------------------------------------------------------------------------------
Здравствуйте, я перевел плагин на русский язык, но немного криво. Вот ссылка: http://surl.li/dnrf
Простите, но я не разобрался как поменять язык в плагине

**Comment by s-pavel77** [comment]
> ## Здравствуйте, я перевел плагин на русский. Но криво. Вот ссылка: http://surl.li/dnrf
> Извините, но я не понял, как изменить язык в плагине
> Извините, но я не очень хорошо говорю по-английски
> Здравствуйте, я перевел плагин на русский язык, но немного криво. Вот ссылка: http://surl.li/dnrf
> Простите, но я не разобрался как поменять язык в плагине

"Что то там с предметом"
This translation is very rude. He is in urgent need of updating.

**Comment by s-pavel77** [comment]
> ## Hello, I translated the plugin into Russian. But crooked. Here is the link: http://surl.li/dnrf
> Sorry, but I didn’t figure out how to change the language in the plugin
> Sorry, but I don't speak English very well
> Здравствуйте, я перевел плагин на русский язык, но немного криво. Вот ссылка: http://surl.li/dnrf
> Простите, но я не разобрался как поменять язык в плагине

`itemWarming: '&aЧто то там с предметом [%item%&a] произойдет за &2%timeleft%&a секунд.'`
This translation is very rude. He is in urgent need of updating.

**Comment by Hacker220** [comment]
> > ## Hello, I translated the plugin into Russian. But crooked. Here is the link: http://surl.li/dnrf
> > Sorry, but I didn’t figure out how to change the language in the plugin
> > Sorry, but I don't speak English very well
> > Здравствуйте, я перевел плагин на русский язык, но немного криво. Вот ссылка: http://surl.li/dnrf
> > Простите, но я не разобрался как поменять язык в плагине
> 
> `itemWarming: '&aЧто то там с предметом [%item%&a] произойдет за &2%timeleft%&a секунд.'`
> This translation is very rude. He is in urgent need of updating.

I know

**Comment by RockinChaos** [comment]
Added in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/430/
See the ru-lang.yml here; https://github.com/RockinChaos/ItemJoin/blob/master/files/locales/ru-lang.yml

I have passed this through a couple of translators so some things have changed, let me know if either of you notices an issue with the translation.

Simply install the snapshot, remove your old ItemJoin.jar, and set the Language in the config.yml to `ru-lang.yml` and the new lang file will be generated.

**Comment by RockinChaos** [comment]
This feature has been officially added to the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
