### ISSUE TITLE
Hello I need to when changing the world and when the player is in world_the_end and when writing /spawn he cleared the inventory and gave items from iremjoin

### ISSUE THREAD

**Issue by FALSHION** [RockinChaos/ItemJoin#294]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
A clear and concise description of what the problem is. Ex. I need help creating a custom item that is given to the player on join. I want it to be a Diamond Sword and [...]

**Pastebin**
Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links. This way if we need to help you modify any of these configuration files we will already have them handy.

**Please complete the following information:**
 - Resource Version and Build Number: [e.g. 5.0.6-b364]
 - Server Version [e.g. Spigot-1.15.2]

**Additional context**

**Comment by RockinChaos** [comment]
Accidental Duplicate #295.
