### ISSUE TITLE
Help me plz

### ISSUE THREAD

**Issue by FALSHION** [RockinChaos/ItemJoin#295]
Hello I need to when changing the world and when the player is in world_the_end and when writing /spawn he cleared the inventory and gave items from iremjoin

**Comment by RockinChaos** [comment]
So its a bit hard to understand what you are wanting.

To me it sounds like you want:
1.) The player's inventory to clear when switching worlds, this can be done via the config.yml under the `Clear-Items` section. Change the type to `ALL` to clear all items or leave it as `ITEMJOIN` for only ItemJoin items. Then set `World-Switch` to true or define the list of worlds you want their inventory cleared in separated by a comma. Example; `World-Switch: world, world_the_nether, world_the_end`. Do note: `Bypass` is enabled for OP players by default so it won't clear their inventory. Set this to `DISABLED` if you want all players to have their inventories cleared. Also, `Options` has `PROTECT` enabled which prevents the clearing of first-join or first-world items. Set this to `DISABLED` if you wish for those to be cleared.

What you should now have looks like this (you can tweak further settings);
```
Clear-Items:
  Type: ALL
  Delay-Tick: 2
  Join: DISABLED
  World-Switch: true
  Region-Enter: DISABLED
  Options: PROTECT
  Bypass: DISABLED
```

2.) The player to be re-given the ItemJoin items. Simply make sure each item has `world-switch` defined for the `triggers` of each item. Example; `triggers: join, world-switch`


Please let me know if this did/didn't answer your issue.
