### ISSUE TITLE
IJ item fails to trigger action

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#297]
## Thanks for taking the time to open a bug report!

**Describe the bug**
ItemJoin menu item fails to trigger configured action. No changes to configuration or other server components.

**To Reproduce**
1. Update to ItemJoin 5.0.7-b427
2. Right-click on IJ item
3. Nothing happens
4. No errors in-game or in console/log

**Expected behavior**
IJ item is configured to open DeluxedMenus menu. It works fine prior to b427. For now, we have reverted to b426.

**Please complete the following information:**
 - Resource Version and Build Number: 5.0.7-b427
 - Server Version: Spigot-1.15.2

**Comment by RockinChaos** [comment]
Should now be resolved in b428: http://ci.craftationgaming.com/job/ItemJoin/428/

**Comment by SlimeDog** [comment]
Confirmed fixed in b428. Thanks.
