### ISSUE TITLE
Item disappearing when player moves?

### ISSUE THREAD

**Issue by devapple** [RockinChaos/ItemJoin#299]
Howdy, my item is being removed when joining a new world, it appears, and as soon as the player moves at all, it disappears. any help?

Rejoining the server will allow the item to stay in the players inventory.

config: https://pastebin.com/VRLnCNgB
items.yml: https://pastebin.com/CAke6E8L

 - Resource Version and Build Number: 5.0.6-b395
 - Server Version Paper-1.15.2

**Comment by RockinChaos** [comment]
99% sure this is because you incorrectly configured the Enabled-Regions.
Try this pastebin; https://pastebin.com/nuZbUCcT

What I did;
removed the `enabled-regions`
remove the itemflags: `region-enter, region-remove`

Let me know if this fixes your issue.
