### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ThijsSlop** [RockinChaos/ItemJoin#30]
Hey there! Sometimes if I click an item the server will crash. It's happening every 2 days or something. 
I reported it to Spigot but they said it's an issue of the plugin. A spigot developer said: "This is generally caused by a plugin doing something async it shouldn't. Not a easy thing to track down"

Crash log: http://pastebin.com/rbzRiwNd (there were no errors before this crash)

 I hope you can fix it.

**Comment by RockinChaos** [comment]
Can you send me your full error log at : This crash report has been saved to: /home/minecraft/multicraft/servers/server10/./crash-reports/crash-2016-04-10_17.42.32-server.txt

Please also send me your items, config, and en-lang.yml. Also what version of ItemJoin are you using? Is it v2.9?

**Comment by ThijsSlop** [comment]
Crash report: http://pastebin.com/pJsrWrQQ
items.yml: http://pastebin.com/FZ03c2Th
config.yml: http://pastebin.com/vZWEi4e8
en-lang.yml: http://pastebin.com/SSk7iDFq

Yes, I always use the latest version of every plugin ;)

It did not happen before I installed this plugin so yea... I hope you can fix it!

**Comment by RockinChaos** [comment]
Can you try ItemJoin v2.8 and tell me if this issue persists.

http://dev.bukkit.org/bukkit-plugins/itemjoin/files/23-item-join-v2-8/

If this issue continues try to remove ItemJoin and test it, if it still crashes please let me know. The crash report is useless since it is not saying the "real" cause for crashing. Meaning it is not pointing to any specific plugin.

**Comment by RockinChaos** [comment]
Something that has been brought to my attention is that there has been some bad spigot versions lately. You should try rebuilding with today's new version using buildtools.jar --Rev 1.9 and let me know if these crashes still occur.

**Comment by ThijsSlop** [comment]
Nope, still not fixed. I think it's just a Spigot bug but they said it's not. weird...

**Comment by RockinChaos** [comment]
You might be right, but I'm going to look around and see if it a bug with my plugin and get back to you about it.

**Comment by RockinChaos** [comment]
If this is still a problem please try the v3.0-SNAPSHOT of ItemJoin and let me know if this fixes your issues.

https://www.mediafire.com/?bf6ee5qbq35bqbs
