### ISSUE TITLE
Здравствуйте, вопросик по плагину itemJoin.

### ISSUE THREAD

**Issue by Stasok2013rus** [RockinChaos/ItemJoin#300]
Как сделать чтобы предмет (itemJoin) появлялся только после авторизации на сервере ?

**Comment by RockinChaos** [comment]
Hi, sorry if I misunderstand this. I do not speak Russian so I had to use a translator to English.

For me it says: 
How to make an item (itemJoin) appear only after authorization on the server?

By authorization do you mean permissions such as `itemjoin.world.ultra-item` in a permissions plugin? Or are you talking about a plugin like AuthMe where you have to login via `/login <password>`?

If you are talking about plugin permissions please see this link; https://github.com/RockinChaos/ItemJoin/wiki/Permissions#itemjoinworlditem

It tells you exactly how to setup permissions. If it is something else please let me know. I apologize for the difficulties in our language barrier.

**Comment by Stasok2013rus** [comment]
Большое спасибо.
