### ISSUE TITLE
ItemJoin problem with slots

### ISSUE THREAD

**Issue by DaRvASs** [RockinChaos/ItemJoin#305]
## Thanks for taking the time to open a bug report!

**Describe the bug**
The items is not placed in the slots that I need and set it in order, but I set other slots

**Screenshots**
![image](https://user-images.githubusercontent.com/63353763/86512749-7aa97680-be0d-11ea-9103-f59711c20e35.png)
 The bow is from other plugin

**Pastebin**
https://pastebin.com/u/DaRv4S

**Please complete the following information:**
 - Resource Version and Build Number: [e.g. 5.0.6-b364]
 - Server Version [e.g. Spigot-1.16.1]

**Comment by RockinChaos** [comment]
So some things to note;
1.) The release version of ItemJoin doesn't support 1.16. Please try the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/472/
2.) There were A LOT of notable issues early on in the first version of spigot 1.16 so please try to compile the latest version using BuildTools.jar.
3.) See if both the newly compiled spigot and latest ItemJoin snapshot work.

Also is this what you are wanting the hot bar slots to look like?
![image](https://user-images.githubusercontent.com/10971577/87000679-81681e80-c16a-11ea-9117-47d43fb56174.png)

If not you need to subtract 1 from your `slot` as slot 1 is actually 0 and slot 9 is actually 8. (This is specified by Mojang and cannot be changed).


Please let me know.

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
