### ISSUE TITLE
ItemJoin Item Prevents Sub-Menus from Being Opened with Some Other Plugins

### ISSUE THREAD

**Issue by meowsome** [RockinChaos/ItemJoin#307]
Hi,

I am using the GadgetsMenu plugin alongside ItemJoin. When I click on the ItemJoin item, the GadgetsMenu main menu opens perfectly fine. However, when I try and click on any option to go into a sub-menu when the ItemJoin item is in my hand, it opens for a brief moment and then triggers the ItemJoin item to run the command again that opens the main menu.

This bug happens any time the ItemJoin item is in my hand, even when accessing the GadgetsMenu main menu from the command /gmenu main. I noticed that when opening the menu without the item in my hand, this bug does not appear.

Apologies if this is not a bug and simply me being stupid.

**To Reproduce**
1. Create an item with any flags with GadgetsMenu latest version installed
2. Add the command "gmenu main" to the item
3. In game, click the ItemJoin item
4. Try and open any sub-menu in the GadgetsMenu main menu

or
1. Create an item with any flags with GadgetsMenu latest version installed
2. Add the command "gmenu main" to the item
3. In game, have the ItemJoin item in your hand
4. Type /gmenu main, and try and open any sub-menu

**Expected behavior**
I should be able to go into any sub-menu in the GadgetsMenu

**Screenshots**
https://drive.google.com/file/d/1LX8YJqPsPbWTHBEGuaRa-VDjWtNwBqAH/view?usp=sharing

**Pastebin**
config.yml: https://pastebin.com/XRa9tt0J
items.yml: https://pastebin.com/LZ3ijwXK

**Please complete the following information:**
 - Resource Version and Build Number: 5.0.7 snapshot b470 and 5.0.6 release on spigot website
 - Server Version Paper 79

**Comment by RockinChaos** [comment]
Very strange behavior, I was able to replicate it but it doesn't seem normal for the player's hand to be swinging when opening a menu. I tested using DeluxeMenus and this doesn't happen, the hand stays fully stationary. For some reason, the plugin is forcing the player to punch the air.

I formulated a fix for this that simply stops all left-click commands from being executed when the player has an inventory open.

Snapshot; http://ci.craftationgaming.com/job/ItemJoin/472/

**Comment by meowsome** [comment]
That's fixed it. That's weird that the other plugin is forcing the hand to swing, I'm not sure why it would need to do that. Thanks so much!

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
