### ISSUE TITLE
Vanilla Map IDs

### ISSUE THREAD

**Issue by TheClowner** [RockinChaos/ItemJoin#310]
## Thanks for taking the time to open a feature request!

**Is your feature request related to a problem? Please describe.**
I'd like to be able to use a vanilla map id for an item join map, so for example, you could hold a map that tracks your position to then run commands. In my case, a map that tracks position could open a warps menu, then as I go to other parts of the world I see where I am on the map. 

**Describe the solution you'd like**
To define a map id for filled_map items, that gives that exact map from vanilla

**Describe alternatives you've considered**
Could also define tracking/map centre within ItemJoin to then overlay the tracking on a custom image.

**Comment by RockinChaos** [comment]
This feature has been officially added in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
