### ISSUE TITLE
Menu Plugin Support Issues

### ISSUE THREAD

**Issue by SuperRonanCraft** [RockinChaos/ItemJoin#314]
I have ItemJoin Installed on my server, it works great, but when I use the "left-click" and/or "right-click" command triggers, when I use the menu plugin AdvancedCustomMenu, it seems to open back up the page the item is supposed to open, but I don't click the item, nor do I have the "commands-type" set to "inventory". So I'm very confused on why when I click any item in the menu plugin, it kicks back to the same page the item in my hand is supposed to open. Could I get some help on this.

**Comment by RockinChaos** [comment]
Sounds similar to an issue that I already resolved in the latest snapshot, can you please try it and let me know if it fixes your issue; http://ci.craftationgaming.com/job/ItemJoin/472/

**Comment by SuperRonanCraft** [comment]
Oh awesome! Seems like this snapshot fixes my issue. Thank you very much :)
