### ISSUE TITLE
Plugin asks for title, does nothing after.

### ISSUE THREAD

**Issue by BiggestPotato111** [RockinChaos/ItemJoin#316]
When the plugin asks me to set a name and lore, I say it in chat and it doesn't do anything. No errors.

 - v5.0.6-RELEASE-b395
 - Spigot 1.8.8

**Comment by RockinChaos** [comment]
So to start with I would recommend using the latest snapshot as there has been a lot of UI changes/fixes since the release version.
Link; http://ci.craftationgaming.com/job/ItemJoin/480/

If the issue still continues can you send me a screenshot / or gif of you typing in chat?

**Comment by BiggestPotato111** [comment]
![notworking](https://user-images.githubusercontent.com/68661186/88235704-6c4ebd80-cc49-11ea-8ee9-bcaa73e1718d.gif)

**Comment by RockinChaos** [comment]
That is very very weird, are you using any chat plugins?
If so, can you list them?

Chat plugins include ones that monitor chat such as anti-spam, anti-cursing, and custom prefixes, etc.

**Comment by BiggestPotato111** [comment]
BungeeChat for the chat format, anti-spam, anti-cursing, and LuckPerms for the prefixes

**Comment by BiggestPotato111** [comment]
bump

**Comment by RockinChaos** [comment]
No need to bump, I get notifications directly to my phone. It is indeed one of the chat plugins you described. I just need to find out why, I just woke up so give me a little bit to comb through each plugin you listed so I can find the issue and formulate a fix.

**Comment by BiggestPotato111** [comment]
Gonna be honest, it's probably BungeeChat with it combing through messages.

**Comment by BiggestPotato111** [comment]
I'm gonna disable bungeechat and see if that fixes anything

**Comment by BiggestPotato111** [comment]
Update, it is BungeeChat indeed.

**Comment by RockinChaos** [comment]
Awesome thank you, it's likely because BungeeChat is canceling the event to forward it to bungee. I'll try increasing the priority of the event to fire before BungeeChat cancels it.

Give me a little bit to setup a Bungee proxy to test with.

**Comment by BiggestPotato111** [comment]
Would you like me to test it on my proxy?

**Comment by RockinChaos** [comment]
It will be quicker for me to test as it will take longer to compile each fix on the integration site to test each change. I have my own debugging program I run to test event proxies so it speeds up the process.

**Comment by BiggestPotato111** [comment]
Alrighty

**Comment by BiggestPotato111** [comment]
![image](https://user-images.githubusercontent.com/68661186/88353538-de97ce80-cd2b-11ea-99a1-b3a09794d17e.png)
I asked the dev of BungeeChat about this, and this is what he said:

**Comment by BiggestPotato111** [comment]
^ Might be good compatibility 🤷

**Comment by RockinChaos** [comment]
Hmmm, interesting, my goal is to try to intercept the message before BungeeChat does.

I have wasted way too much time trying to figure out the BungeeChat side of things, I can't even get it to allow me to type into the chat. It simply says "You do not have the permissions to perform that action" any ideas? Possible permission node I am forgetting?

**Comment by BiggestPotato111** [comment]
**bungeechat.command.local** is to chat locally on that server only, **bungeechat.command.global** is to chat globally on the bungeecord network (meaning you chat in all servers). I had that same problem.

**Comment by BiggestPotato111** [comment]
https://github.com/AuraDevelopmentTeam/BungeeChat2/blob/master/BungeeChatApi/README.md does this help?

**Comment by RockinChaos** [comment]
Perfect thank you. I was confused about why it is labeled "command" when I am simply typing in chat lol. Working now, looking for a fix on this. It seems they catch the message before its even sent server-side. I am likely going to have to catch the raw packet itself.

I will let you know when it is complete, this may take a little while.

**Comment by BiggestPotato111** [comment]
Alrighty I got it

**Comment by BiggestPotato111** [comment]
I may be able to fix this with *another* plugin

**Comment by BiggestPotato111** [comment]
I'll ask BungeeChat dev tomorrow for advice about this "temporary fix" he was talking about

**Comment by RockinChaos** [comment]
Okay so after a lot of testing I can confirm that there is nothing I can do on a "server" level. I would need to hear more from the BungeeChat developer as he cancels the event via Bungee before it even gets passed to the server so no packet is interceptable and no event is triggered server-side.

**Comment by BiggestPotato111** [comment]
![image](https://user-images.githubusercontent.com/68661186/88429334-70531a80-cdc4-11ea-965f-5c8c579eca55.png)

**Comment by BiggestPotato111** [comment]
Would you like his tag?

**Comment by RockinChaos** [comment]
Seems to work perfectly as he described.

Make sure you enabled `passToBackendServer` for both Local and Global chat, there are "Two of them"

**Comment by RockinChaos** [comment]
Hey, I haven't heard back from you. Was this able to resolve your problem?

**Comment by BiggestPotato111** [comment]
I just disable BungeeChat while I'm editing the inventory.

**Comment by BiggestPotato111** [comment]
^ I'll probably do that fix eventually, but I am just too lazy right now and working on other things. Thanks

**Comment by RockinChaos** [comment]
Okay sounds good, I created a note for the menu command in-case others come across this issue specifically with BungeeChat or any other bungee chat plugins; https://github.com/RockinChaos/ItemJoin/wiki/Commands#itemjoin-menu
