### ISSUE TITLE
Skull-owner error 5.0.7-snapshot

### ISSUE THREAD

**Issue by juancruzdal** [RockinChaos/ItemJoin#318]
Plugin Version: ItemJoin-5.0.7-SNAPSHOT-b484
Server Version: Paper 1.8.8

Console log: https://pastebin.com/5P8Gks8y

Error desc: problems to charge the skull-owner items

**Comment by juancruzdal** [comment]
My item config: https://pastebin.com/3vsaXmDM

**Comment by RockinChaos** [comment]
Resolved in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/488/

**Comment by RockinChaos** [comment]
Forwarded from duplicate issue;

Plugin Version: 5.0.7-SNAPSHOT-b488
Server version: Paper 1.8.8

Console log: https://pastebin.com/vj0KMpxX
Item config: https://pastebin.com/BXFE4K05



Bug testing this now.

**Comment by RockinChaos** [comment]
Replicated, here is a fixed snapshot; http://ci.craftationgaming.com/job/ItemJoin/489/

Let me know!

**Comment by juancruzdal** [comment]
Plugin Version: 5.0.7-SNAPSHOT-b489
Server version: Paper 1.8.8

Console log: https://pastebin.com/MdaLJtiH

**Comment by RockinChaos** [comment]
Very weird, seems that Java was bypassing my catch exception to use the legacy methods for skull items. Wasn't able to replicate it on my end but I have seen similar instances of ignoring catch exceptions before.

I designed a better method to catch and use the legacy skull methods so it should now work in the latest snapshot; http://ci.craftationgaming.com/job/ItemJoin/490/

Let me know, sorry about that!

**Comment by juancruzdal** [comment]
Plugin Version: 5.0.7-SNAPSHOT-b489
Server version: Paper 1.8.8

pd: Only happen when online-mode: false

Console log: https://pastebin.com/zmQZLdSs

**Comment by RockinChaos** [comment]
Should now function in this version;  http://ci.craftationgaming.com/job/ItemJoin/491/

Seems the player was being returned as having not played the server before so I made it simply apply the owner string. If you are using SkinRestorer its likely the skin will be a steve/alex until their API is fixed but you will only know from testing.

**Comment by juancruzdal** [comment]
Yes! you got it!

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.0.7.
You can grab it here; Download: https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
