### ISSUE TITLE
skull-owner problem in 5.0.7-SNAPSHOT-b488

### ISSUE THREAD

**Issue by juancruzdal** [RockinChaos/ItemJoin#319]
Plugin Version: 5.0.7-SNAPSHOT-b488
Server version: Paper 1.8.8

Console log: https://pastebin.com/vj0KMpxX
Item config: https://pastebin.com/BXFE4K05

**Comment by RockinChaos** [comment]
No need to duplicate issues, going to reference this in the original. #318
