### ISSUE TITLE
GUi bug

### ISSUE THREAD

**Issue by 136MasterNR** [RockinChaos/ItemJoin#323]
The bug is on GUi as you can see, when teleporting to a different world via GUi chest/inventory, the first 5 items from it will be stack on your survival crafting inventory, and then it will move on to your inventory after opening it. It doesn't do that every time, but very often.

Some Screen Shorts:
- Choosing a world: https://prnt.sc/tzo5lr
- When opening the inventory: https://prnt.sc/tzo8ey
As you can see, the glass panes appear there.

Version: 1.14.3
Software: Bukkit
Plugin Ver: 5.0.6

No console errors.

I have tested and my other plugins to see if it's not because of ItemJoin, but it seems like it.

**Plus**, Also it seems like you can duplicate items from the survival crafting inventory.

Example: when you put a Gold Ingot, and take it out, the result (gold nuggets) will stay there.

**Comment by RockinChaos** [comment]
I would suggest trying the latest snapshot first so we can narrow it down as not being any past issues; http://ci.craftationgaming.com/job/ItemJoin/504/

Please let me know.

**Comment by 136MasterNR** [comment]
It seems fixed on the snapshot, I couldn't test it to my original server to be sure, but it seems working on my alt server.
