### ISSUE TITLE
Items with Expiry Times

### ISSUE THREAD

**Issue by ryantheleach** [RockinChaos/ItemJoin#325]
## Thanks for taking the time to open a feature request!

**Is your feature request related to a problem? Please describe.**
I would like to be able to give players an item for a given time period. e.g. a 'noob juice' potion that expires after an hour of play, that would shield them from mobs while they play.

**Describe the solution you'd like**
2 different item properties.
1. A time-played expiry date, that expires when a player hits a certain time played, with lore explaining it in duration remaining.
2. A wall-clock based expiry date, that expires after an event is finished.

**Comment by RockinChaos** [comment]
Confirmed as in-the-works already, these will be classified as "Item Conditions" I will let you know when I have a snapshot available.

**Comment by RockinChaos** [comment]
Item conditions have been added in b603, however, it does not remove the item once the condition has elapsed, (I was unsure if you wanted this or not) it just renders the item unusable for the defined action.

See this post for how to set this up; https://github.com/RockinChaos/ItemJoin/issues/236#issuecomment-764142559

Devlog will be updated in the next day or so, it's quite a bit of information to add.


Snapshot; https://ci.craftationgaming.com/job/ItemJoin/603/
Devlog; https://github.com/RockinChaos/ItemJoin/wiki/DevLog

**Comment by RockinChaos** [comment]
This feature has been officially added in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
