### ISSUE TITLE
Jenkins RSS notifications have wrong address

### ISSUE THREAD

**Issue by rautamiekka** [RockinChaos/ItemJoin#334]
**Describe the bug**
The RSS notifications from the Jenkins use a LAN IP for the address that should take you to the build.

**To Reproduce**
1. Go to https://ci.craftationgaming.com/job/ItemJoin/ and scroll to the bottom.
2. Subscribe to any of the Atom/RSS notifications, such as for all the builds through https://ci.craftationgaming.com/job/ItemJoin/rssAll
3. Wait for a new notification, or open the subscription link in a browser.
4. In the notification, or the code when opened in browser, the link to the build on the Jenkins you always see 192.168.0.68 used.

**Expected behavior**
For ex, build 569 would have `http://192.168.0.68:8080/job/ItemJoin/569/` when it should be `https://ci.craftationgaming.com/job/ItemJoin/569/`.

**Comment by RockinChaos** [comment]
Sorry about that, I did a server migration last week and forgot to change the default URL.

Should now be fixed, please let me know!

**Comment by rautamiekka** [comment]
> Sorry about that, I did a server migration last week and forgot to change the default URL.
> 
> Should now be fixed, please let me know!

According to https://ci.craftationgaming.com/job/ItemJoin/rssAll it's all fixed now.
