### ISSUE TITLE
Error when players join or quit

### ISSUE THREAD

**Issue by Tyloon1e** [RockinChaos/ItemJoin#337]
## Thanks for taking the time to open a bug report!

**Describe the bug**
Just installed ItemJoin. This error appears every time players join or quit.

**To Reproduce**
1. Install ItemJoin
2. See error in console

**Expected behavior**
I expect this error not to happen.

**Pastebin**
https://pastebin.com/raw/uJqgnj7C

**Please complete the following information:**
 - Resource Version and Build Number: 5.1.1-SNAPSHOT-b574
 - Server Version: Tuinity 1.16.3

**Comment by Tyloon1e** [comment]
Anything I can do to troubleshoot?

**Comment by RockinChaos** [comment]
Nothing is needed, I was able to replicate it. I am currently working on creating a method that pushes this action to the main thread so the error doesn't occur. I should have it done either tomorrow or Sunday.

**Comment by RockinChaos** [comment]
Should now be fixed in the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/576/

Let me know!~

**Comment by Tyloon1e** [comment]
> Should now be fixed in the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/576/
> 
> Let me know!~

It's fixed in the latest snapshot!

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=354306

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
