### ISSUE TITLE
Itemjoin not working! 

### ISSUE THREAD

**Issue by Porkason** [RockinChaos/ItemJoin#338]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detail you can.**
When joining and receiving items an error appears. 

**Pastebin**
Config: https://pastebin.com/7FG5ARvP
En-lang: https://pastebin.com/iEwB9YC2
items: https://pastebin.com/A0yaNedi

**Please complete the following information:**
 - Resource Version and Build Number: Latest
 - Server Version1 SPigot 1.16.3

**Additional context**
https://pastebin.com/3bPxXUer

This issue happens when a player joins and recieves items.

**Comment by RockinChaos** [comment]
Should already be resolved in the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/574/

**Comment by Porkason** [comment]
agreed!

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
