### ISSUE TITLE
Custom Items in Crafting Recipe

### ISSUE THREAD

**Issue by F1reP0wer12345** [RockinChaos/ItemJoin#339]
**Description**
As the title states, I'm trying to get a custom item from itemjoin, into the recipe for another item.
I don't know if I'm doing it wrong or not but what I've currently got in the items.yml doesn't work.
If this isn't possible yet, I would love to request this as a feature.

**Pastebin**
Items.yml:
https://pastebin.com/HHqVXT0k
I don't think I've even opened the Config.yml, but here it is anyway:
https://pastebin.com/enWN7Z6Q
I didn't change anything about the language file for sure, because, as it says below, this is a survival server.

**Version Information:**
 - Resource Version and Build Number: v5.1.0-RELEASE-b545
 - Server Version: Paper 1.10.2 (mostly for my custom survival plugins to work)

**Comment by RockinChaos** [comment]
Hey, can you elaborate more on what you mean? Do you mean another item as in another plugin or are you saying that you are trying to set up a custom recipe for an ItemJoin plugin but it isn't able to be crafted using vanilla Minecraft items?

**Comment by F1reP0wer12345** [comment]
In the items.yml you'll find 2 items. One is crafted with default minecraft resources and is called teleporter, and the other one is crafted using the teleporter item and more resources. Both of them are recipes inside the items.yml. If you'd please read it, perhaps you might understand more of what I'm trying to accomplish. I've added some text behind the last # .

**Comment by RockinChaos** [comment]
Sorry for the late reply. 
Ahhh I feel stupid, you are trying to use an ItemJoin item as a recipe in your other item.

So you are asking if I can add a feature to allow this to work correct? Currently it's only possible using materials. You can of course use the teleporter in the recipe but you can use any item with the same material if that makes sense. So it's currently not restricted to specifically that ItemJoin item.



Also I noticed you "B" ingredient is listed as `DARK_OAK_DOOR_ITEM` which is actually incorrect. Its suppose to be `DARK_OAK_DOOR`

So changing the ingredients to;
```
    ingredients:
    - A:COMPASS # refering to the upper item, which, of course, doesn't really work.
    - B:DARK_OAK_DOOR
```
Allows the recipe to function but again the "COMPASS" is generic so (not restricted to that ItemJoin item).

-- Did you enter the `DARK_OAK_DOOR_ITEM` yourself or was that via the `/itemjoin menu` if its the menu then that's a bug and I will need to track it down.

**Comment by F1reP0wer12345** [comment]
Sorry for my even later response, didn't really play survival that much, but i'm back now.
Actually i was playing on 1.10.2, and i don't really know if that matters with the dark oak item, but yes, I did actually use "/ij menu".
Also as soon as i've picked up survival again, i started upgrading from 1.10.2 to 1.15.2 which is actually supported by all of my plugins. "The DARK_OAK_DOOR_ITEM" and "DARK_OAK_DOOR", isn't really the problem. I mean it's good to know that it might have caused problems, but what i want to know is how do i replace the "COMPASS" item with the "teleporter" item.

If you're willing to implement this as a feature, I did notice that every item join item comes with an nbt tag, and it can be picked up by other custom crafting plugins, which support reading this nbt tag. I've got the following lines from EpicCrafting for the output item (The second modified compass):
      nbt:
      - ItemJoin Slot;8
      - ItemJoin Name;home-token
I'm not a big fan of EpicCrafting because it uses a custom crafting table, and that's not gonna work for my surivival. That's why I'm requesting this as a feature.

Edit: This is my first time on the github issues.. How do i close this issue? Or do you have to do that for me?
Edit2: Nevermind! found it!
