### ISSUE TITLE
Arbitrary slot

### ISSUE THREAD

**Issue by xyblues** [RockinChaos/ItemJoin#34]
I don't want to set the slot for the item because it will cover the slot item.
Like slot: null

**Comment by RockinChaos** [comment]
I am not understanding, you are saying you want to get an item but, you don't want to get the item... lol. Each item has to have a defined slot to put them in.

To follow up with your request are you wanting for ItemJoin to not over-write the item in that slot and put it in the next available slot?

Saying if I was to add a slot type slot: Arbitrary
This would cause ItemJoin to put each item in the FIRST available slot. Then continue to add each item if space is available?

For example a player logs in. Slot 2, 4, 8, and 12 have items in them. Are you wanting this new "Arbitrary" slot type to place the items in the available slots in order but randomly? Such as putting item1 in slot 1 and item2 in slot 3 as well as item3 in slot 5, and so on...?

**Comment by xyblues** [comment]
Yes,Your example is right.

**Comment by RockinChaos** [comment]
Okay, I will get on this. I will hopefully have this for the v3.0 Release.

**Comment by xyblues** [comment]
Thank you very much.

**Comment by RockinChaos** [comment]
v3.0 has been uploaded and will be approved shortly! Just set the slot: # to slot: Arbitrary
