### ISSUE TITLE
Problem Items

### ISSUE THREAD

**Issue by P4SION** [RockinChaos/ItemJoin#340]
Hello, this is a great plugin, but I have a problem in the items and when I move my scroll wheel on the items the name doesn't appear. My server is in 1.8.8. Thanks

**Comment by RockinChaos** [comment]
Can you provide your config.yml and items.yml in a pastebin.com link so I can look into this.
Also what client are you using for Minecraft as I don't quite understand what you mean by being able to see an items name using your scroll wheel? Do you simply mean the Action Bar Title that appears above the Hotbar when cycling through your hot bar items?
