### ISSUE TITLE
Can't Make Items

### ISSUE THREAD

**Issue by Anston06** [RockinChaos/ItemJoin#345]
I can't make an item. It just doesn't work. I tried going to different worlds and I have the permission.

Items Config File: [https://pastebin.com/kgRHMGFb](https://pastebin.com/kgRHMGFb)

**Comment by RockinChaos** [comment]
Everything seems correct in your items.yml, can you please provide your config.yml in a pastebin.com link.

**Comment by Anston06** [comment]
The build number is b545. I have the permissions. The get command worked! I would like the item to be given without the command though.

Config.yml: https://pastebin.com/mBE0P0Lx

**Comment by Anston06** [comment]
> Everything seems correct in your items.yml, can you please provide your config.yml in a pastebin.com link.
> Also, what build number is provided when you type `/itemjoin` in-game? It should say b360 for example.
> 
> EDIT: Another thing to check, you can confirm if your permissions are correctly setup by typing `/itemjoin permissions 2` and if they are RED then you do not have permission to receive them. You should also be able to get the items via `/itemjoin get example-item`

The build number is b545. I have the permissions. The get command worked! I would like the item to be given without the command though.

Config.yml: https://pastebin.com/mBE0P0Lx
