### ISSUE TITLE
Some players cant open server compass

### ISSUE THREAD

**Issue by RAFAELESPADA** [RockinChaos/ItemJoin#348]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
A clear and concise description of what the problem is. Ex. I need help creating a custom item that is given to the player on join. I want it to be a Diamond Sword and [...]
Some players cant open the server compass. It appear that the dont have enought money http://prnt.sc/vqvsr7 how i remove the money limit? In my items.yml dont have any money requirememts so i dont undestand why it is happening. When player has negative balance they cant open the server menu

**Pastebin**
Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links. This way if we need to help you modify any of these configuration files we will already have them handy.
Items.yml: https://pt.textbin.net/Wf4JP4zVYz
config.yml: https://hastebin.com/asayuxoweq.yaml

**Please complete the following information:**
 - Resource Version and Build Number: [e.g. 5.0.6-b364]
 - Server Version [e.g. Spigot-1.15.2]
Resource version and build number: 5.1.0-RELEASE-b545
Server version: PaperSpigot-1.8.8
**Additional context**

**Comment by RockinChaos** [comment]
Going to close this as it was continued on Discord.

The resolution is in the latest snapshot.
