### ISSUE TITLE
[Bug] Item permission not work in latest build version.

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#350]
**Describe the bug**  
Players will get the item even though they don't has permissions.
And also can run the commands.

Besides, I have a question that the item permission is for giving or execute commands?
(I think it is for giving...)

**To Reproduce**
1. Setup a item with "triggers: join" and "permission-node: itemjoin.test"
2. Join the server.
3. Get the item and can execute commands.

**Screenshots**
![image](https://user-images.githubusercontent.com/38014059/100644721-a5750800-3376-11eb-9eab-e1e93d65a88c.png)

**Pastebin**
items.yml
https://pastebin.com/cxhCbDHX

Other files: default

**Please complete the following information:**  
- ItemJoin-5.1.1-SNAPSHOT-b585.jar
- Paper version git-Paper-262 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Additional context**
Please look at this, thanks~

**Comment by RockinChaos** [comment]
You say that your other files are default, since you didn't provide your config.yml I will assume that this is true. Did you enable Item Permissions in the config.yml?

```
  Obtain-Items: false
  Obtain-Items-OP: false
```

These need to be set to true, OP is for OP players to require perms--for clarification.

**Comment by momoservertw** [comment]
I haven't set it up for two years, haha
Thanks a lot.
