### ISSUE TITLE
"/itemjoin get" for other players is not working

### ISSUE THREAD

**Issue by Ceqola** [RockinChaos/ItemJoin#351]
## Thanks for taking the time to open a bug report!

**Describe the bug**
Pretty simply; putting a player in when doing /itemjoin get <item> <player> doesn't work and gives an error in console.

**To Reproduce**
1. If a plugin/console runs it, returns an error
2. If OPed player does it, just gives the item to the player

**Expected behavior**
I expect not an error and to have the item given to the player

**Screenshots**

**Pastebin**
https://pastebin.com/Ae0ykeG9

**Please complete the following information:**
 - Resource Version and Build Number: v5.1.0-RELEASE-b545
 - Server Version: Spigot 1.16.4

**Additional context**
Would appreciate if this was fixed soon, as it's important for me to give players certain items

**Comment by RockinChaos** [comment]
Sounds like a duplicate ticket, pretty sure this is already fixed in the latest snapshot.
Link; https://ci.craftationgaming.com/job/ItemJoin/591/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
