### ISSUE TITLE
book is broken

### ISSUE THREAD

**Issue by lireboy** [RockinChaos/ItemJoin#353]
when i want to add a book when ppl are joining it works but the book is fked up 
[http://prntscr.com/wezwrk](url)

even tho according to you wiki it should be right!
[http://prntscr.com/wezx16](url)

**Comment by RockinChaos** [comment]
Can you send me a screenshot of your `/itemjoin` output in chat?

And can you provide a pastebin.com link of your book item so I can debug it please.

**Comment by lireboy** [comment]
> Can you send me a screenshot of your `/itemjoin` output in chat?
> 
> And can you provide a pastebin.com link of your book item so I can debug it please.
 what do you mean with output ?

**Comment by lireboy** [comment]
> Can you send me a screenshot of your `/itemjoin` output in chat?
> 
> And can you provide a pastebin.com link of your book item so I can debug it please.

https://pastebin.com/enw7MYtJ

**Comment by RockinChaos** [comment]
So it looks like your book is working perfectly fine using the latest version of ItemJoin. I am assuming you are using a legacy version of ItemJoin but it seems you didn't provide the screenshot so I can't confirm what version you are using.

The wiki is updated to work only with the latest release of ItemJoin which supports MC 1.7-1.16.4.

I would suggest using this version and testing your book again; https://ci.craftationgaming.com/job/ItemJoin/596/
**Remember to remove your old ItemJoin.jar file**
