### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Andreas-Iorgu** [RockinChaos/ItemJoin#354]
**Describe the bug**
Every time when i m closing the minecraft server i m getting this error :) nothing more. But the plugin works well without any problem.

**To Reproduce**
1. items.yml -> https://pastebin.com/57FRJQKp
2. config.yml -> https://pastebin.com/a3ub8FsC
3. Close the server

**Screenshots**
https://imgur.com/a/DEszSZO

**Please complete the following information:**
 - Resource v5.1.0-RELEASE-b545
 - Server: 1.16.4 1.16.4-R0.1-SNAPSHOT

**Comment by RockinChaos** [comment]
I am 99% sure this issue is already resolved in the latest snapshot as it looks fairly familiar.
Link; https://ci.craftationgaming.com/job/ItemJoin/597/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
