### ISSUE TITLE
Disable WorldEdit navigation

### ISSUE THREAD

**Issue by Tyloon1e** [RockinChaos/ItemJoin#355]
Just a very quick question. Is it possible to have ItemJoin cancel the WorldEdit navigation effect with a compass?
If you click with it, it teleports you around.

**Comment by RockinChaos** [comment]
Apologies for the late reply, I thought my prior message posted but apparently, it didn't.

ItemJoin cannot cancel WorldEdit navigation as WorldEdit does not allow this, the only option is to change the navigation item to a different item id in the config.yml of WorldEdit/WorldGuard.
