### ISSUE TITLE
Server lags when someone joins

### ISSUE THREAD

**Issue by llaurenss** [RockinChaos/ItemJoin#36]
Everytime someone joins my server lags for 1 second this is really anoying because i have a 1v1 server.

**Comment by RockinChaos** [comment]
1.) What version of Spigot/Craftbukkit are you using? is it up to date? /version

2.) What version of ItemJoin are you using?

3.) Can you send me your Items.yml and Config.yml in pastebin.com

**Comment by llaurenss** [comment]
1. spigot version 1.8.8

2. version 3.0

3. items.yml http://pastebin.com/W7HVWCjP  config.yml http://pastebin.com/q0dajJYr

4. ??

**Comment by RockinChaos** [comment]
Version 3.0 is untested for Spigot 1.8.8 so I will look into this and see if I get a bug on my end.

as for #4. When you server starts it creates a log under the logs folder in your server directory. Send me the full startup in a pastebin.com.

Then send me a player joining the server from the log file as well. ( any error codes etc or just the player plain joining if there is no error codes ).

**Comment by llaurenss** [comment]
nvm i think it's the server sorry
