### ISSUE TITLE
Could not pass event InventoryClickEvent to ItemJoin v5.0.6-RELEASE-b395

### ISSUE THREAD

**Issue by cloakfox** [RockinChaos/ItemJoin#363]
https://pastebin.com/RqQfLxFK

Running on tuinity 1.16.5

No idea how to reproduce the error, I saw it in console so thought i'd post it here.

**Comment by RockinChaos** [comment]
ItemJoin is out of date, current release version is v5.1.0 but you are running v5.0.6.

However, I would suggest the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/660/

**Comment by cloakfox** [comment]
Tried latest version that doesnt require me to redo configs but got crazy errors
https://pastebin.com/pGz3aKGH

**Comment by cloakfox** [comment]
Great. Because of that ***** players their inventory cleared again lol.

Imma just not use this, no offense.

**Comment by RockinChaos** [comment]
The config files reset any time there is a major version change such as v5.0.7 to v5.1.1 (the 0 changes to a 1) in this instance. Typically there have only been minor changes to the config files but nobody seems to read the changes and things start to break, hence why most developers implement this type of system of resetting config files when changes like this occur. Do note though your old configs are always backed up prior to this.

The latest snapshot (https://ci.craftationgaming.com/job/ItemJoin/664/) works as intended on Tuinity 1.16.5 but does require redoing configs.

If you are interested in continuing to use this plugin I can always translate your current config files to the latest version for you but you will need to provide them in pastebin.com links.
