### ISSUE TITLE
[Dev version] Condition fail message does not work.

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#364]
The condition works great, but the fail message does not work.

A few days ago, I mentioned it in another issue page.
https://github.com/RockinChaos/ItemJoin/issues/236#issuecomment-772309192

The test configuration(current):
https://pastebin.com/1yZgEvHe

Paper version: git-Paper-463 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
ItemJoin version: v5.1.1-SNAPSHOT-b668

**Comment by RockinChaos** [comment]
My bad! Didn't even see that message, looking into this now.

**Comment by RockinChaos** [comment]
Okay, so the latest snapshot has been tested and now resolves the fail message issues.

Snapshot; https://ci.craftationgaming.com/job/ItemJoin/674/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
