### ISSUE TITLE
Item commands not working

### ISSUE THREAD

**Issue by KhrysAK47** [RockinChaos/ItemJoin#367]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
To be short I was trying to make commands to a certain item and when I click the item, it doesn't execute a certain command and errors in console.

[05:49:38] [Server thread/ERROR]: [ItemJoin_ERROR] {ItemCommand} There was an error executing an item's command as console, if this continues report it to the developer.

**Pastebin**
items.yml: https://pastebin.com/4ez8CNaX
config.yml: https://pastebin.com/vRG2qyLr

**Please complete the following information:**
 - Latest version available currently (14th Feb)
 - Spigot 1.16.4

**Additional context**

**Comment by RockinChaos** [comment]
Answered via discord, update to latest snapshot resolves the bug.
