### ISSUE TITLE
Hide Attributes

### ISSUE THREAD

**Issue by Lemrigue** [RockinChaos/ItemJoin#37]
Hello, I would like to know if it is possible to add the next option for the items :
- hideflags : true/false (make the "+4 damage" dissapeared for example)

thanks !

**Comment by RockinChaos** [comment]
This is something I would love to add as I really hate the "flags" that mojang has added to them. I do not believe this is possible but I have been wrong a lot when I say this xD. I will look into this and get back to you ASAP!

**Comment by RockinChaos** [comment]
This has been added as of v3.1 and will be released soon!

These are called attributes btw and I have added them to the prevent-modifers:
So to hide them it would be 

prevent-modifers:
- 'attributes'

**Comment by RockinChaos** [comment]
Version 3.1 has been released! Enjoy!
http://dev.bukkit.org/bukkit-plugins/itemjoin/files/26-item-join-v3-1/
