### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by yurabens** [RockinChaos/ItemJoin#372]
Hello, there was a problem that people started to disappear things, after switching to a new version and reconfiguring the config, it happens randomly, sometimes it disappears when you log in, sometimes when you change the game mode, please see the config, maybe I configured something wrong? There were problems with the sections: ActiveCommands and Clear-Items, due to a poor understanding of the English language.

The task is this, a person enters the server, receives an item, and can never throw it out again, and if it suddenly turns out, he gets it again, no need for any deletion of things, no deletion when entering a foreign region, just GOT IT and forever.

Maybe you can change something in the config or remove the excess? The I translator does not allow you to fully understand the essence. Sorry if I'm not writing an appeal in the format, it's just a language barrier...

**Comment by yurabens** [comment]
[config.zip](https://github.com/RockinChaos/ItemJoin/files/6019081/config.zip)

**Comment by RockinChaos** [comment]
Its a bit hard to understand but I think I get the basics.

The configs look to be properly setup.
What version of Spigot are you running so I can bug test this?

**Comment by yurabens** [comment]
Server version: 1.16.4 (core: yatopia-1Server version: 1.16.4 (core: yatopia-1.16.4-paperclip-b40).16.4-paperclip-b40)

**Comment by yurabens** [comment]
I found out a small pattern, things disappear when you re-enter the server, and who has all the things, someone has a part, and this happens randomly, and rarely, if you count all the re-entries of people

**Comment by RockinChaos** [comment]
So after A LOT of testing.. I am starting to think this may be an issue with a third-party plugin.

To confirm this; can you set your `items-Delay` in your items.yml to let's say... 6?
So `items-Delay: 6`

It is a 3-second delay before you get the items but it will help determine if its another plugin or not, and if it is another plugin we can work on reducing the items-Delay to as short as it can go before they vanish again.
