### ISSUE TITLE
[Question] Stop moving of certain items in inventory?

### ISSUE THREAD

**Issue by MindOfModz** [RockinChaos/ItemJoin#375]
Hey!

Is it at all possible to stop the movement of certain items within an inventory? Such as a star but they can move anything else.

Many thanks.

**Comment by RockinChaos** [comment]
Yes, you can add the `inventory-modify` itemflag to the item.
`itemflags: inventory-modify, self-drops, death-drops` for example.

A full list of itemflags can be found in the wiki here; https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#defining-an-items-itemflags

**Comment by MindOfModz** [comment]
Thank you very much! I will now close this :D
