### ISSUE TITLE
NBT CustomModelData not working

### ISSUE THREAD

**Issue by posterhusky** [RockinChaos/ItemJoin#378]
Hi, I'm running a 1.16.3 server with a custom resource pack, and I made custom paper textures and assigned them a CustomModelData value. Everything works if I type: /give @s paper{CustomModelData:10001}, but when I put it in the Properties section of the plugin, it does not work.

```
  item_1:
    id: PAPER
    slot: 0
    name: '&b&lPLAY'
    itemflags: UNBREAKABLE, HIDE-ATTRIBUTES, HIDE-DURABILITY, PLACEMENT, INVENTORY-MODIFY,
      ITEM-STORE, CANCEL-EVENTS, DEATH-DROPS, SELF-DROPS, ITEM-MODIFIABLE, ITEM-REPAIRABLE,
      ITEM-CRAFTABLE, ALWAYS-GIVE, OVERWRITE, AUTO-REMOVE
    properties: 'CustomModelData:10001'
    enabled-worlds: ALL
```

**Comment by RockinChaos** [comment]
What version of ItemJoin is this (the build number)? 
You can type `/itemjoin` and it will tell you.

**Comment by posterhusky** [comment]
5.2.1-RELEASE-b678

**Comment by RockinChaos** [comment]
Sorry for the late reply, I have been working to replicate this issue.
It seems in the release the NBT tag is being properly applied.

Stupid question; are you using another plugin to handle the CustomModelData or are you trying to have Minecraft handle it?
If you are trying to have Minecraft handle it and not another plugin then you should be using the `model-data` option for items as that has to be specially coded by spigot and cannot be applied by a simple NBTTag.

Snippet from the wiki;
In (1.14+) there is now official Custom Model Data support so each item has its own individual texture regardless of durability taken. This can be done by adding `model-data: 10001` to the item for example. Do note, this is the numerical value you assigned in the .json file.

```
items:
  example-item:
    id: DIAMOND
    slot: 0
    model-data: 10001
```

**Comment by posterhusky** [comment]
thanks, it works
