### ISSUE TITLE
Itemjoin interfering. 

### ISSUE THREAD

**Issue by Porkason** [RockinChaos/ItemJoin#379]
Okay so i use a plugin called creativeparkour (which is irrelevant but yeah) I have a itemjoin item that issues a command to open a creativeparkour gui where they can choose a playermade map to play on. But somehow itemjoin interfere and the gui doesn't work and the items can be removed from the gui and moved to the inventory. When I remove itemjoin this problem does not appear anymore. No errors.

**Comment by RockinChaos** [comment]
So I haven't been able to replicate this so far with CreativeParkour.

Can you provide your ItemJoin - items.yml and config.yml in pastebin.com links please so I can test with your settings.
