### ISSUE TITLE
Colored Leather_Chestplate

### ISSUE THREAD

**Issue by Gabrielanderline** [RockinChaos/ItemJoin#38]
I have some good idea for this project: do you know the tags colors in leather_chestplate for example color:16711680 , you can make this, if i define in a file config the id with a leather_chestplate for example and the color he can give that armor with that specified color?

**Comment by RockinChaos** [comment]
This has been added as of ItemJoin v3.1 and will be uploaded soon! Thanks for your patience!

**Comment by RockinChaos** [comment]
Version 3.1 has been released! Enjoy!
http://dev.bukkit.org/bukkit-plugins/itemjoin/files/26-item-join-v3-1/
