### ISSUE TITLE
What is itemjoin.craftworld{name=world_lobby}.*

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#380]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
In an older script, I see a reference to the permission _**itemjoin.craftworld{name=world}.***_. I see no reference to this permissions in the current ItemJoin wiki. I suspect that is was a previous incarnation of **_itemjoin.world.*_**.

Can you elucidate?

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.2-SNAPSHOT-b688
 - Server Version 3020-Spigot-bff5261-ee5006d (MC: 1.16.5)

**Comment by RockinChaos** [comment]
So I would assume this doesn't occur in any new scripts as you said old script?

The permission `itemjoin.craftworld{name=world}.*` should not exist and as your prior issue in the year 2018 it was marked as fixed so I would hope that this isn't occurring as a new issue.

Ref; https://github.com/RockinChaos/ItemJoin/issues/162#issuecomment-358864504
Ref2: https://github.com/RockinChaos/ItemJoin/issues/162#issuecomment-359065773

So to elucidate that perm should not exist and should not be used by anything, so if it doesn't pop up in anything you are using now I would simply just select that perm and CTRL + X that out of existance.

**Comment by SlimeDog** [comment]
Thanks. I forgot about the old issue. That old permission remained in a script. It wasn't presenting a problem. I just want to remove it.
