### ISSUE TITLE
StackOverflowError console spam (wg regions)

### ISSUE THREAD

**Issue by deka9584** [RockinChaos/ItemJoin#382]
**Describe the bug**
I encountered this error that stopped the functioning of the objects that used the worldguard regions.
The following message continued to be printed in the console and in a short time the logs came to occupy almost 1gb.
Entering the regions the items were not changed.

**To Reproduce**
Unfortunately I have no way to describe how to reproduce the malfunction because after restarting the server I was no longer able to find the problem even redoing everything as before.
However, it seemed right to tell you because if it happens again when I do not have the console in sight it would bring me many problems.
All I can do is attach my plugin configuration.

**Pastebin**
Console error: https://pastebin.com/9ihKkh3G (this appeared at the same time that the player joined)

**Please complete the following information:**
 - Resource Version and Build Number: v5.2.1-RELEASE-b678
 - PaperSpigot-1.8.8

**Additional context**
config.yml: https://pastebin.com/UhpGNdGP
items.yml: https://pastebin.com/VnfgHTLZ

**Comment by RockinChaos** [comment]
Sorry about this issue!
So there have been quite a few notable changes in the snapshots for WorldGuard regions so I would suggest updating and checking if the issue still occurs.

Link; https://ci.craftationgaming.com/job/ItemJoin/692/
**Remember to remove your old ItemJoin.jar file**

**Comment by MrPranklez** [comment]
I ran into the same issue using build #688 I've updated to the latest version recently( #704), so I'll keep you posted!

**Comment by RockinChaos** [comment]
> I ran into the same issue using build #688 I've updated to the latest version recently( #704), so I'll keep you posted!

I would highly suggest updating to the latest dev build I pushed out today as it has been reported to 100% resolve the issue with the finalized changes.

Link; https://ci.craftationgaming.com/job/ItemJoin/706/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=403809

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
