### ISSUE TITLE
Compass without teleporting and Bungeecord version

### ISSUE THREAD

**Issue by Miluek** [RockinChaos/ItemJoin#384]
Hello, I have 2 questions...
1) It's possible to make Compass without teleporting? I want only Compass icon without left and right click, I want just that player click (right and left click) in game (also in inventory too) to open my ChestGUI for server navigation...

2) Does it exist Bungeecord version of this plugin? If yes, could you give me the link to download it?

Thanks 🙂

**Comment by RockinChaos** [comment]
Hi, 

1.) That is entirely WorldGuard/WorldEdit and isn't something that any plugin can mess with. Essentially your only solution is to go into WorldGuard/WorldEdit and change the teleport item to a different material say bedrock or something not frequently used.

2.) There "is" a version of ItemJoin-Bungee but it is not what you think, currently, it is a Proxy to allow users to execute BungeeCord commands from the local server via `bungee:` as found in the wiki. If you are interested it is here; https://github.com/RockinChaos/ItemJoin-Bungee it's not released on spigot yet until ItemJoin v5.2.2 is released as the bungee feature was implemented then but a jar exists already compiled on that GitHub page. 

In the future, though the plan is to expand this Proxy plugin to an actual version of ItemJoin (functionality-wise) currently the Proxy part is just a stepping stone to start with.
