### ISSUE TITLE
I can't craft anything on a crafting table

### ISSUE THREAD

**Issue by Kogp498** [RockinChaos/ItemJoin#386]
Hello, I have combined this plugin with ChestsCommands: https://dev.bukkit.org/projects/chest-commands and I have created a compass that by right-clicking opens a menu in which you select any minigame. Everything works fine but neither I nor anyone else can craft on a crafting table on the server. PLEASE HELP :(

**Comment by RockinChaos** [comment]
Can you please provide your config.yml and items.yml in a pastebin.com link so I can test this.

**Comment by Kogp498** [comment]
I already found out why I couldn't craft items on the crafting table! It was because reloading the plugin while the server is started can no longer be crafted until you restart the server again. I think this is a bug that you should fix. Oh and one last thing, auto-remove doesn't work. I have since the compass only appears in the following worlds: LobbyMG, SkyWars. Well, when I return to the normal world, the compass is not removed, could you check my config to see what is wrong? Thanks for answering :) [https://pastebin.com/mdUum9Bx](url)

**Comment by RockinChaos** [comment]
Okay so, after a lot of tweaking it seems I was able to fix the issue not being able to craft after reloading the plugin.

Link; https://ci.craftationgaming.com/job/ItemJoin/718/
**Remember to remove your ItemJoin.jar file**

**Comment by SimonMage** [comment]
@RockinChaos I have the same issue in 1.12.2, when i create an item with ItemJoin, i cant build anything in craftingtable and in inventory. I downloaded and used this version https://ci.craftationgaming.com/job/ItemJoin/718/

**Comment by RockinChaos** [comment]
> @RockinChaos I have the same issue in 1.12.2, when i create an item with ItemJoin, i cant build anything in craftingtable and in inventory. I downloaded and used this version https://ci.craftationgaming.com/job/ItemJoin/718/

I would suggest using the latest available snapshot. This is a really old issue well over a year old. Many changes have been done to the crafting items / menu since then.

Link; https://ci.craftationgaming.com/job/ItemJoin/820/
**Remember to remove your old ItemJoin.jar file**
