### ISSUE TITLE
Item disappearing from inventory

### ISSUE THREAD

**Issue by hlnebula** [RockinChaos/ItemJoin#388]
Item disappears from inventory once it is used￼

**Comment by RockinChaos** [comment]
Sounds like you have the disposable itemflag defined for your item.

I would need to see your items.yml to be 100% sure but that itemflag removes the item once you use it.

**Comment by hlnebula** [comment]
I figured it out it's because the commands item was sent to the same item. So my guess is that it was charging one Emerald to run the command and the item was an emerald so it was removing it from their inventory.￼￼￼
