### ISSUE TITLE
How do I use probability

### ISSUE THREAD

**Issue by hlnebula** [RockinChaos/ItemJoin#389]
How do I make it so when I click an item there is only a 5% chance that the command executes?￼￼

**Comment by TheRobLP** [comment]
Hey there. My apologies or the delay. RockinChaos has been sick over the past two weeks, and I am not checking Github very often. Regarding your question, there is no specific option to have command probabilities. Im not sure if it can be implemented, but I believe so. In the meantime however, there is a workaround actually, but it will fill up your items.yml quite a bit

**Comment by TheRobLP** [comment]
Really sorry, my finger slipped. I didnt mean to close this.

First of all, hey there. My apologies or the delay. RockinChaos has been sick over the past two weeks, and I am not checking Github very often. Regarding your question, there is no specific option to have command probabilities. Im not sure if it can be implemented, but I believe so. In the meantime however, there is a workaround actually, but it will fill up your items.yml quite a bit. In the pastebin link below you can see an item which should roughly have a 5% chance of executing:

https://pastebin.com/B6d2pBi3

As you can see though, it is a quite tedious process, but it should do for now.

To @RockinChaos : What do you thinnk about a probability for command execution? I feel like it would fit very well.
