### ISSUE TITLE
 Is it possible to add tags like "CanPlaceOn"? I don't find any info about it.

### ISSUE THREAD

**Issue by medovi40k** [RockinChaos/ItemJoin#392]
Is it possible to add tags like "CanPlaceOn"? I don't find any info about it.

**Comment by RockinChaos** [comment]
Hi,
By tags do you mean NBT Tags/Properties?

This section covers it fairly well; https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#setting-up-nbtproperties
If it is another plugin handling the `CanPlaceOn` it depends on how they set the tag that you would need to replicate. Examples such as it being nested in a folder such as Item would be `Item.CanPlaceOn`.

By default though this should work for you, simply add this to your item;
`properties: 'CanPlaceOn:DIRT'`
Just replace the DIRT with your desired value. (I am not sure what functionality this tag serves so I am just showing an example)
