### ISSUE TITLE
Server Crashed task 58026773

### ISSUE THREAD

**Issue by mantrakp** [RockinChaos/ItemJoin#395]
## Thanks for taking the time to open a bug report!

**Describe the bug**
My server crashed due to it idk how it never gave such errors in my life and no editing was dont on any item when it crashed
i have 2 items 1 survival menu 1 temp fly item no edition was happening during the crash and the plugin was on latest version
**Please complete the following information:**
 - Resource Version v5.2.1
 - Server Version purpur 1.16.5

**Additional context**
Pls resolve it
[2021-05-07-1.log](https://github.com/RockinChaos/ItemJoin/files/6445253/2021-05-07-1.log)

**Comment by RockinChaos** [comment]
Already confirmed to be resolved, please update to the latest snapshot.

Link; https://ci.craftationgaming.com/job/ItemJoin/707/
**Remember to remove your old ItemJoin.jar file**
