### ISSUE TITLE
Region access not working

### ISSUE THREAD

**Issue by hlnebula** [RockinChaos/ItemJoin#396]
So I have the region access trigger on my arrows. The enabled region is set to arena. If people disconnect then re-join the spawn point is at the pvp-spawn region and they still have arrows. So the region access only removes items if you are walking out of the region not if you are teleporting out of the region or spawning outside of the region￼￼.

**Comment by hlnebula** [comment]
I don't know why I labeled this as a question this is more of a bug.￼

**Comment by RockinChaos** [comment]
Answered you on your discord ticket :)
