### ISSUE TITLE
Connection leak detection triggered 

### ISSUE THREAD

**Issue by P2LOVE** [RockinChaos/ItemJoin#398]
Here is randomly warn spamming into console errors about SQL leak connection/

**Pastebin**
https://pastebin.com/4jcxLBNb

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.1-RELEASE-b678
 - Server Version PaperSpigot 1.12.2

**Additional context**
Cannot get steps to reproduce, but in console logs it is very common warn

**Comment by RockinChaos** [comment]
I would reference the existing issue number but I can't quite remember which one it was but anyways, this is already fixed in the least snapshot so all you need to do is update.

Link: https://ci.craftationgaming.com/job/ItemJoin/710
**Remember to remove your old ItemJoin.jar file**

**Comment by P2LOVE** [comment]
will it be compatible with 1.12.2 server core?

**Comment by RockinChaos** [comment]
Yes,
All ItemJoins versions are backward compatible with the latest Minecraft version which is currently 1.7 - 1.16.5 so that includes 1.12.2.

It has been tested as working on 1.12.2 and is slated to be a release candidate so if you encounter any issues, please let me know.

**Comment by P2LOVE** [comment]
ty!
