### ISSUE TITLE
items not showing when moving to an enabled world

### ISSUE THREAD

**Issue by lvsidh** [RockinChaos/ItemJoin#399]
## Thanks for taking the time to open an assistance request!

I setted up items and enabled worlds, but when i go to one of the enabled worlds, the items doesnt show up, it only shows up on one of the enabled worlds...

**ion get this pastebin link one sry**

**Please complete the following information:**
 - v5.2.1-b678
 - Spigot 1.16.4

The items only shows up on one of the enabled worlds but when i go to the other worlds, they doesnt show up

**Comment by RockinChaos** [comment]
Hi, can you provide your items.yml and config.yml so I can look into this issue.
