### ISSUE TITLE
give-on-world-change: Bug

### ISSUE THREAD

**Issue by zogoria** [RockinChaos/ItemJoin#4]
Thank you for the best join items plugin, i tried all but your plugin is the best....
I use Spigot 1.8.8, Multiverse 2.5-b699 (beta) and ItemJoin ItemJoin v2.1. I have no errors in console. Using "give-on-world-change: true"
The problem is when I teleport from worlda to worldb, I receive  worlda's items in worldb, it suppose to be vise versa, 
It means after I teleported to worldb I should receive worldb's items not another world's item. 
any hope to solve that,
Thank you.

**Comment by XSilverSlayerX** [comment]
Sorry for the late reply. I have been very ill. 
Multi world items only realistically works with clear on world change or Multiverse inventories. ItemJoin does not remove worlda items when entering worldb and gives them to you. Its a feature I would like to add eventually.

Please try the following and let me know if these render results you are looking for:

1.) Do you have clear on world change enabled?
2.) Do you have Multiverse inventories?

Can you also please post your items and config.yml in pastebin.com and link it.
