### ISSUE TITLE
Command /itemjoin get <slot> <player> does not work

### ISSUE THREAD

**Issue by xyblues** [RockinChaos/ItemJoin#40]
When I use slot: Arbitrary
This command will not work, can not give players items

**Comment by RockinChaos** [comment]
Sorry for the late reply, going through personal issues. I am looking into this and I think I have found the bug. This will be fixed in the next update.

**Comment by RockinChaos** [comment]
Thanks for the report! This has been fixed for version 3.1 and will be release soon!

**Comment by RockinChaos** [comment]
Version 3.1 has been released! Enjoy!
http://dev.bukkit.org/bukkit-plugins/itemjoin/files/26-item-join-v3-1/

**Comment by xyblues** [comment]
@RockinChaos 
When I use slot: Arbitrary
Can't get it on the console.But players can.
If a player already owns the item, it does give a duplicate.
![image](https://cloud.githubusercontent.com/assets/15712089/16174845/ab2fd1cc-3609-11e6-80c8-cdc9fd5eab58.png)
