### ISSUE TITLE
Items that can not move/drop can be placed in item frame

### ISSUE THREAD

**Issue by Brickmaster122** [RockinChaos/ItemJoin#400]
## Thanks for taking the time to open a bug report!

**Describe the bug**
Hi so when you get the item from your inv that is not supposed to be dropable it can be placed in an item frame and removed to get the item .

**To Reproduce**
1 get the un-dropable item and place it in the item frame 

**Expected behavior**
Make it not possible to put non-dropable items in item-frame pls

**Please complete the following information:**
Version 5.2.0 
Server version Bukket 1.16.5

**Comment by RockinChaos** [comment]
Hi, I sincerely apologize for not responding to your Github post, I have been quite busy with some personal issues.

To prevent the "storage" of the ItemJoin item you need to add the `item-store` itemflag to your items.

Example;
`itemflags: inventory-modify, item-store`
