### ISSUE TITLE
Join trigger ignoring permission negation and giving item anyways.

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#401]
RE: https://github.com/RockinChaos/ItemJoin/commit/b7ab6743b07b74fb81ab2d12a8230007a5325f4a#commitcomment-51007806

**Describe the bug**
Join trigger is giving a book to an admin group with permission wildcards despite permission being negated.

**To Reproduce**
1. Be a group with all permissions using a wildcard ``*`` & ``itemjoin.spawn.*``
2. Have an item that triggers to give on join.
3. Specify a custom permission for the item.
4. Negate the permission from the admin group.
5. Be given the item on join anyways.

**Expected behavior**
No item on join as admin.

Functional with dev build 709. Broke in dev build 710.

Breaking commit https://github.com/RockinChaos/ItemJoin/commit/b7ab6743b07b74fb81ab2d12a8230007a5325f4a

**Comment by RockinChaos** [comment]
Perfect, exactly what I needed. Will have an update shortly :)

**Comment by mibby** [comment]
Apologies for the delay in testing. This seems to be fixed now, thanks!
