### ISSUE TITLE
Hikari issues

### ISSUE THREAD

**Issue by jortpepe** [RockinChaos/ItemJoin#402]
**Bug description**
On startup, I seem to get some non-critical error messages, a few seconds after startup a connection leak gets detected.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Run the plugin on Purpur 1.16.5 build 1090 (not sure if it matters).
2. See the console after the 'done' on startup.
3. Wait for max a minute or two and see the leak detection message.

**Expected behaviour**
No error messages and leak detection is triggered.

**Screenshots**
Not applicable, see Pastebin.

**Pastebin**
Error messages on startup: https://pastebin.com/ZRiRGKWU 
Connection leak being detected: https://pastebin.com/XyEiUGUB

Configuration file ItemJoin: https://pastebin.com/9zGwa9R5

**Please complete the following information:**
 - Resource Version and Build Number: v5.2.1-RELEASE-b678
 - Server Version: Purpur 1.16.5 build 1090

**Additional context**
None.

**Comment by RockinChaos** [comment]
Same issue as #369 already resolved.
Please use the latest snapshot;
https://ci.craftationgaming.com/job/ItemJoin/709/
**Remember to remove your old ItemJoin.jar file**

**Comment by jortpepe** [comment]
Oh, my apologies! I was unaware it had already been fixed. Thank you for the quick reply and have a nice day!
