### ISSUE TITLE
Armor parts as an Item and no Armor Slots

### ISSUE THREAD

**Issue by ivandelp** [RockinChaos/ItemJoin#404]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
There is a trigger to prevent only place a player skull or a hat as an armor?

I want to have as an item for players and they can move it in all inventory but not in armor slots.

**Please complete the following information:**
 - Resource Version and Build Number: ItemJoin v5.2.1
 - Server Version - Paper 1.16.5

**Comment by RockinChaos** [comment]
Currently, this isn't possible to restrict the equipment of items (only) without using some hackyness with Item Commands.

However, I will add this as a feature request as it should be pretty easy to implement.

**Comment by ivandelp** [comment]
Okey, thanks.

**Comment by RockinChaos** [comment]
The latest snapshot implements this feature request provided the item is equippable and is not "force equipped" by another plugin.

Simply add the `cancel-equip` itemflag to the item and you will be able to freely move the item around but you will not be able to equip it.

Link; https://ci.craftationgaming.com/job/ItemJoin/732/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
This feature has been officially added in the release of ItemJoin v5.2.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=403809

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
