### ISSUE TITLE
Possibly Forgot [ cancel-equip ] ( Player_Head Item )

### ISSUE THREAD

**Issue by ivandelp** [RockinChaos/ItemJoin#405]
## Thanks for taking the time to open a bug report!

**Describe the bug**
**cancel-equip** not work with player_head item.

**To Reproduce**
1. Move player_head item to Armor Slots with cancel-equip activated.

**Expected behavior**
Possibly you forgot add player_heads to that flag.

**Please complete the following information:**
 - Resource Version and Build Number: ItemJoin-v5.2.2-RELEASE
 - Server Version: Paper 1.16.5

**Comment by RockinChaos** [comment]
I sincerely apologize for the late reply, ItemJoin has grown a lot in popularity over the past few months and it has been so hard for me to keep up with the number of tickets.

Can confirm this issue.
Just going to silently slide in this link and we can pretend I didn't miss player heads xD.

Link; https://ci.craftationgaming.com/job/ItemJoin/738/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
