### ISSUE TITLE
I got a error

### ISSUE THREAD

**Issue by llaurenss** [RockinChaos/ItemJoin#41]
https://ghostbin.com/paste/3yzo9

**Comment by RockinChaos** [comment]
I need more information.

1.) What are the steps to reproduce this error?

2.) What version of spigot/craftbukkit are you using?

**Comment by RockinChaos** [comment]
From what I can tell from what you gave me is that it is a bug with TrainingPvP.

at me.jeroenhero123.TrainingPvP.CombatTagHook.isTagged(CombatTagHook.java:28) ~[?:?] at me.jeroenhero123.TrainingPvP.Commands.CommandRanked.onCommand(CommandRanked.java:53) ~[?:?]


As well as

Unhandled exception executing command 'ranked' in plugin TrainingPvP v7.3

Sorry I cant help much, you will have to contact the TrainingPvP developer.
