### ISSUE TITLE
NickAPI Incompatibility 

### ISSUE THREAD

**Issue by nicholasveronico** [RockinChaos/ItemJoin#413]
## Thanks for taking the time to open a bug report!

**Describe the bug**
I have a disguise plugin that uses NickAPI to disguise the player. For some reason, when putting NickAPI on the server, ItemJoin seems to have issues giving items on join. Every join is different. For example, the first join could only give item 1 and item 2, but not item 3, and others sometimes give only item 2 and item 3, etc. There is never a case when all items are given. There aren't any errors for ItemJoin; however, NickAPI gets this strange error: https://pastebin.com/iXexr5h4

**To Reproduce**
1. Install NickAPI and use this config (https://pastebin.com/ncrb9fZ1)
2. Have ItemJoin on the server, with this config (https://pastebin.com/hfrvYecd) and these items (https://pastebin.com/r86FxUVn)
3. Join with a cleared inventory, clear inventory, rejoin and not all items will be given

**Expected behavior**
I expect the player to receive all items when joining using NickAPI. The player isn't even disguised when this happens either. It doesn't happen when the player is disguised with NickAPI.

**Screenshots**
Expected inventory: https://i.imgur.com/jk7OxFV.png
Some inventories with NickAPI installed: 
- https://i.imgur.com/ZreKQ6P.png
- https://i.imgur.com/TWjTTuV.png

**Pastebin**
Config: https://pastebin.com/hfrvYecd
Items: https://pastebin.com/r86FxUVn

**Please complete the following information:**
 - Resource Version and Build Number: v5.22-RELEASE-b734
 - Server Version: mSpigot 1.8.8

**Additional context**
N/A

**Comment by RockinChaos** [comment]
Okay so, this seems to simply be a feature compatibility issue.
I have added support for NickAPI so it now checks their database of players and fetches the proper player information.
Link; https://ci.craftationgaming.com/job/ItemJoin/764/
**Remember to remove your old ItemJoin.jar file**
Let me know!~

**Comment by RockinChaos** [comment]
This feature has been officially added in the latest release.

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
