### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xFrex** [RockinChaos/ItemJoin#415]
## Thanks for taking the time to open a bug report!

**Describe the bug**
The command assigned to the item does not work

**To Reproduce**

when I right click on the item

**Expected behavior**
it does not work

**Screenshots**
https://imgur.com/A8s9PDL

**Pastebin**
Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links as well as any related error codes from the console window.

**Please complete the following information:**
 - Resource Version: v5.2.1-RELEASE-b678
 - Server Version: 1.8

**Additional context**
no

**Comment by RockinChaos** [comment]
So I would start by updating ItemJoin as you are using an outdated release version. The latest release is v5.2.2 which removes the use of Hikari as displayed in your error message.

However, I would suggest the latest v5.2.3 snapshot as it is more stable than the current v5.2.2 release.

Link; https://ci.craftationgaming.com/job/ItemJoin/750/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by RockinChaos** [comment]
This is likely now fixed in the latest release, I would suggest starting there. I am going to mark this as resolved due to inactivity, please feel free to reach out if you still need help.

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
