### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by Anim3Add1ct** [RockinChaos/ItemJoin#417]
I get this error in the console from time to time, no specifc pattern: https://pastebin.com/Hi1DqXcU

config.yml: https://pastebin.com/cxVkw86H
items.yml: https://pastebin.com/7HjBuGEU

 - ItemJoin v5.2.1-RELEASE-b678
 - Purpur 1.16.5

**Comment by RockinChaos** [comment]
I would suggest updating as this error seems familiar so I am willing to bet it is already fixed.
v5.2.2 is that latest release but I suggest the v5.2.3 snapshot as it is more stable.

Link; https://ci.craftationgaming.com/job/ItemJoin/750/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by Anim3Add1ct** [comment]
Thanks, should be fixed. I'll take your word for it since I can't access to the server rn.
