### ISSUE TITLE
Color change of item

### ISSUE THREAD

**Issue by mrstakan1** [RockinChaos/ItemJoin#418]
Hi. I have a question about changing item color. What i mean: i have a item in lobby server, which has red color, but i want to change it to another, i`ve changed color in .yml, but nothing changed to me and players also. What should i do?

**Comment by RockinChaos** [comment]
So I am not quite sure exactly what you mean without seeing your items.yml.
However, I can say changing the item in the items.yml will not automatically update an existing item in the players inventory. You either have to clear your inventory and re-get it or you need to add the `dynamic` itemflag to the item which will automatically update the item as long as the "node-name" doesn't change.

I hope that makes sense, let me know!~

**Comment by mrstakan1** [comment]
Hi
yes, u were absolitely right) i`ve fixed everything! Thank u
