### ISSUE TITLE
Bug In Join and ChangeWorld event (3.1 & 3.2)

### ISSUE THREAD

**Issue by Lemrigue** [RockinChaos/ItemJoin#42]
Hello I have a problem when I change world in version 3.1 and 3.2 (spigot 1.9.4), it doesn't give the items
http://puu.sh/pmR6O/281f0d37f3.png
http://puu.sh/pmRpp/6e4d5c582d.png
Works fine in 3.0

**Comment by RockinChaos** [comment]
Thanks for your report! Please try this v3.3-SNAPSHOT and tell me if this resolves your problems. I am unable to test this atm but I believe it was a simple null checker I forgot to add for the new leather color support.

v3.3-SNAPSHOT: http://www.mediafire.com/download/k08xga50mzn0dxm/ItemJoin.jar

**Comment by Lemrigue** [comment]
It seems to work perfectly fine

**Comment by RockinChaos** [comment]
Sweet I deleted the previously uploaded v3.2 and replaced it with the jar that has fixed this bug.
Thanks for the speedy report!
