### ISSUE TITLE
Items given upon joining a multiverse world

### ISSUE THREAD

**Issue by GLUR-DEV** [RockinChaos/ItemJoin#424]
## Items given upon joining a multiverse world

I am rather new to ItemJoin plugin and I was wondering if anyone could help me on this matter.
**My problem is:**
I have multiverse-plugin and multiverse-portals installed. Every time someone logs onto my server for the first time, they have an option to got through a multiverse portal which takes them to another world. I have the items registered in the items.yml to when ever a player joins or logs onto the world the player is given an item, that is not a problem it works fine. The problem is if they are new to the server and have never joined that world before they don't get the item, which is really frustrating. I was wondering if there is a trigger that I could apply to that item to solve this problem. And if not you could implement it into the plugin :).

Thanks in advance, any suggestions would be appreciated.  

(I have searched the issues and haven't found a thread that covered this)

**Comment by RockinChaos** [comment]
I honestly wonder if this has something to do with tweaking the `items-Delay` (to a higher number) in the items.yml as it sounds like Multiverse is "lagging" behind a bit on registering the player's functions for the first time.

I would suggest making that number higher (increasing by 2 or 4) and testing if it changes.

If it doesn't work (even after increasing the delay to a max of `20`) I would suggest providing your items.yml so I can test your configuration.

**Comment by GLUR-DEV** [comment]
Unfortunately tweaking the items-Delay value didn't work. I incremented the items-Delay value by 2 all the way up to twenty reloading the plugin every time I made a change. I also want to say that I am running spigot 1.12.2 just incase the outdated version has something to do with the issue. 

Here's my items.yml config: *note: I changed the items-Delay variable back to 2 after I finished testing*
https://pastebin.com/MFpdhJ78

**Comment by RockinChaos** [comment]
I sincerely apologize for the late reply, I have been working hard on this bug but I haven't had anything to report.

It seems after a long time testing different scenarios I am unable to replicate this issue.
Would it be possible to join your server so I can test this myself?
If so can you provide the IP & go into your config.yml of ItemJoin and set Debugging to `true` then `/itemjoin reload`.

I have multiple accounts so I should be able to test this a few times without needing my dat files deleted.

**Comment by RockinChaos** [comment]
This is likely now fixed in the latest release, I would suggest starting there. I am going to mark this as resolved due to inactivity, please feel free to reach out if you still need help.

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
