### ISSUE TITLE
Items with "inventory" action not executing commands.

### ISSUE THREAD

**Issue by Rismack** [RockinChaos/ItemJoin#427]
Hello!

This problem is not a bug because I've tested ItemJoin in a test server and everything worked fine, but if you could help me, it would be awesome.

As the title says, items that are supposed to execute a command when clicking on them with the inventory open, are not doing so. This is happening in my main server where I have many other plugins installed so I guess that something is preventing ItemJoin from working properly.

Also, when I change the item action to "interact", the commands are executed just fine.

-Edit:

I removed all plugins from my main server and the problem persists, so now the plugin list is not relevant anymore. I really don't know what could be causing this because as I said, ItemJoin works fine in my test server with no other plugins.

I also removed all config files from ItemJoin in my main server. Everything is exactly the same as the test server but it still doesn't work.

Can a server file like spigot.yml, bukkit.yml, paper.yml, etc. be the problem? Is there any config in those files that can affect ItemJoin?

**Comment by RockinChaos** [comment]
Hmmm, would you be able to provide your configuration files so I can test this myself? It may entirely be a conflict with another plugin as you said.

**Comment by Rismack** [comment]
I just managed to solve the problem. 

I'm not sure what was the cause but I reset the config of some plugins and now it's woking. Maybe there was a corrupted file somewhere and I didn't notice.

In any case, I'll let you know if the problem appears again.
Thank you for your message!
