### ISSUE TITLE
World Switching Problem

### ISSUE THREAD

**Issue by m4kii420** [RockinChaos/ItemJoin#428]
When player enters the region he gets iron sword but the problem is if I relog or change the world and go back to that world the  iron sword is still there. Any suggestion how can I fix that? Here is video: https://youtu.be/8UMZZs6xLBA

btw thank you for this amazing plugin <3

**Comment by RockinChaos** [comment]
Could you provide your configuration files and a screenshot of your `/itemjoin` output so I can start debugging this issue for you.

**Comment by m4kii420** [comment]
[ij.zip](https://github.com/RockinChaos/ItemJoin/files/7281874/ij.zip
![Screenshot_1](https://user-images.githubusercontent.com/85348361/135938978-99cd9ac1-55ba-4a43-ab63-2d451ba3ab1a.png)
)

**Comment by RockinChaos** [comment]
> [ij.zip](https://github.com/RockinChaos/ItemJoin/files/7281874/ij.zip ![Screenshot_1](https://user-images.githubusercontent.com/85348361/135938978-99cd9ac1-55ba-4a43-ab63-2d451ba3ab1a.png) )

I was meaning a screenshot of your `/itemjoin` output (command) as it will display its build number in chat.
I will assume you are using the latest though.

**Comment by m4kii420** [comment]
yup its latest (v5.2.2)

**Comment by m4kii420** [comment]
It would be nice if there was an option to remove items in disabled regions, but if not I can add with WorldGuard that every time player join that region it runs a command "/ij remove item_2 [player]"

**Comment by m4kii420** [comment]
this happens because of the PerWorldInventory plugin, if I link this world with hub the item will be removed, but the problem is that those 2 worlds must not be connected

**Comment by RockinChaos** [comment]
Wow, now that was a hard bug to replicate, can confirm it is an issue with Multiple Inventory plugins.

I have produced a fix that will resolve this issue, please see the latest snapshot.
Link; https://ci.craftationgaming.com/job/ItemJoin/768/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by m4kii420** [comment]
Works perfectly now. Thanks for your help :)

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
