### ISSUE TITLE
Hide Damage and Attack speed attributes

### ISSUE THREAD

**Issue by Maxence621** [RockinChaos/ItemJoin#429]
Hello,
I have a server with some friends, and i made custom swords with custom model datas tags.
I also modify the attack damage and the attack speed , wich depends on the custom model data tags.
I wanted to hide the "old" AttackDamage and AttackSpeed attributes, but the only thing that do this is the itemFlags:"HideAttributes", but the problem is, the enchantment don't show up again after i put this wich is sad,
The custom lore work correctly, but we can't see the enchantments

My question is :
How can i remove all attributes, except the custom lore and the enchantment ?

 - Resource Version and Build Number: Version 5.2.2
 - Server Version : Paper 1.17.1

**Comment by RockinChaos** [comment]
This feature has been officially added in the latest release.

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
