### ISSUE TITLE
Rank Items

### ISSUE THREAD

**Issue by MrStreeet** [RockinChaos/ItemJoin#430]
Hello! I just wanted to know if there's an option of making that if a player has a rank it can get an special item on-join.

It's 2 different menus, the point it's if the player joins to the server and it has a rank, it gets the item that can open the vip menu intead of the normal item that opens the normal menu.

I'm working in an RPG menu and I wanted to add Rank features in it, like this:

No rank menu:
![image](https://user-images.githubusercontent.com/50084238/137396934-27a173cf-1187-42de-9ae7-c5329c4def47.png)

With rank menu:
![image](https://user-images.githubusercontent.com/50084238/137396997-76b61dd8-faf8-4c51-9692-65726f4aa46d.png)

Thank you so much ^^

 - Resource Version and Build Number: [5.3.3-RELEASE-b734]
 - Server Version [Paper git-Paper-325 MC:1.17.1]

**Comment by RockinChaos** [comment]
Hi, I apologize if I misunderstand.
You can indeed grant specific permissions for custom items so players will need those perms to get the item on-join.

This can be done via the following;

**Before Proceeding**
You will need to enable item permissions in your config.yml via;
Config.yml > `Permissions.Obtain-Items` set this to `true`
**Note** This is only for regular players, if you want this to apply to OP players set;
Config.yml > `Permissions.Obtain-Items-OP` set this to `true`

Add this to your item;
`    permission-node: 'itemjoin.specialty'`

Here is an example of an item utilizing the custom permission node utility;
```
items:
  example-item:
    id: DIAMOND_SWORD
    slot: 0
    permission-node: 'itemjoin.specialty'
```

You can change the permission node to whatever you want such as 'example.fish'. I simply chose to use ItemJoin as the beginning string of the custom permission node. Make sure to add the custom permissions you create to a permissions plugin afterward.

Additional info on permissions can be found here; https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#establishing-itempermissions-required

Let me know!~
