### ISSUE TITLE
Hi! Please help me, I don't know how to solve the problem. I have a plugin installed for pets, where you need to install an item in the config to mount a horse on my pet and ride. In itemjoin, I made a menu in the form of an item: compass, also installed an item: compass in the config of the item, which, by clicking on the horse, will allow them to sit on it, but this does not work. I click the compass from itemjoin on the horse and I can't get on the horse in any way.

### ISSUE THREAD

**Issue by Pikachu2p** [RockinChaos/ItemJoin#435]
Hi! Please help me, I don't know how to solve the problem. I have a plugin installed for pets, where you need to install an item in the config to mount a horse on my pet and ride. In itemjoin, I made a menu in the form of an item: compass, also installed an item: compass in the config of the item, which, by clicking on the horse, will allow them to sit on it, but this does not work. I click the compass from itemjoin on the horse and I can't get on the horse in any way.

**Comment by RockinChaos** [comment]
Hi, sorry to hear you are having issues.

Let me recap to make sure I understand,
You have a custom compass item and you are saying that you are unable to mount a pet such as a horse while the compass is in your hand?

In addition, can you please provide a snippet of the item in question, a pastebin.com link would be preferred.

Once I get that information I will be able to help you further.

**Comment by Pikachu2p** [comment]
It's okay, don't apologize

Look, the problem is that I can sit on a regular horse, but if my horse is from the mypet plugin, I selected the compass menu from the itemjoin plugin so that by clicking on the horse I could sit on it, but I can't sit. It doesn't give me errors, I understand that I need to write some parameters or settings, or somehow add a vanilla right click to the compass so that it clicks with the right mouse button like a regular vanilla compass, and not like the compass of the server menu. In addition, when I click them in the air or on blocks, the menu should appear, but when I click on creatures from the mypet plugin to sit down, then I really have to sit on a horse and the opening of the menu should be ignored and the right mouse click should be performed.

**Comment by RockinChaos** [comment]
Hmmm so after some testing I am unable to replicate this.

Would you be able to provide the ItemJoin item so I can test using your exact settings. (Pastebin.com link is preferred).

**Comment by Pikachu2p** [comment]
mainmenu:
    id: compass
    slot: 0
    name: 'Menu'
    interact:
    - 'player: menu'
    itemflags: item-store, self-drops, death-drops, CreativeBypass, AllowOpBypass, item-repairable, item-craftable, item-modifiable, death-keep
    triggers: join, respawn, world-switch
    enabled-worlds: ALL





There is a config in the MYPET plugin, scroll to the bottom and there will be such a setting (line 161-162). 

    Ride:
      Item: compass


I have set up a compass in items. 

That is, clicking with a regular compass works, but itemjoin does not work from the plugin. I will really wait for the solution of the problem :)

**Comment by RockinChaos** [comment]
Okay so after a lot of testing I have determined this to be a bug with MyPet.
If the item is modified at all, it just simply wont work. Instead they should be comparing the material type against the set material type.

So essentially you need to contact the developer of MyPet and let them know if it is a compass from any other plugin that it wont work so they should instead compare material types instead of checking if the item is similar to a default vanilla item.

Let me know if I need to clarify.
