### ISSUE TITLE
AuthMe and ItemJoin

### ISSUE THREAD

**Issue by morgan2233** [RockinChaos/ItemJoin#436]
## Thanks for taking the time to open a bug report!

**Describe the bug**
When you have both Authme and ItemJoin enabled, the integration means that you don't get items until you login which is fine; however, if you make registration optional and not compulsory then ItemJoin won't give item to players who haven't even registered

So, if I'm registered, it works as expected and I get the items following login but if I am not, then I don't get them at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Both Authme and Itemjoin with integration on
2. Connect to server without registering (as not required)
3. See error (no items and no way to get items)

**Expected behaviour**
I would like to see players who are not registered get their items instantly when in Authme force registion is turned off and only registered players be restrict.

OR

Option to disable authme integration

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.2
 - Server Version: Paper 1.17.1 - 377

**Comment by RockinChaos** [comment]
Should now be fixed in the latest snapshot, tested as working.
Link; https://ci.craftationgaming.com/job/ItemJoin/776/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
