### ISSUE TITLE
Suggestion: %hitplayer%

### ISSUE THREAD

**Issue by llaurenss** [RockinChaos/ItemJoin#44]
There is already %player% but can you also add %hitplayer%.
If you hit someone with an item, the player that got hit his name wil be replaced with %hitplayer%.

I am holding an item with the command "duel %hitplayer%" and when I hit someone with that item his name will be replaced with %hitplayer%

For example:
When I hit Bob with an itemjoin item it will perform the command /duel Bob.

Sorry for my bad english.

**Comment by RockinChaos** [comment]
If you could re-state this a little better like, go more in detail please. Its a little hard for me to understand.

**Comment by llaurenss** [comment]
Updated I hope you understand it now

**Comment by llaurenss** [comment]
You think this is possible?

**Comment by RockinChaos** [comment]
This has been added as of ItemJoin v3.5 and it has been released!

You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107083
