### ISSUE TITLE
Replacing items in slots

### ISSUE THREAD

**Issue by cta10** [RockinChaos/ItemJoin#443]
Hello, I want to share a problem, which is that when a player enters the game, his items in the first and last slot change to things from this plugin. How can I remove this problem, tell me.

**Comment by RockinChaos** [comment]
Apologizes for the late reply, it sounds like you have overwrite enabled.
To double check my fix I would need to see your items.yml in a pastebin.com link however, for now;
1.) Disable the `items-Overwrite` boolean at the top of the items.yml.
2.) Remove any `overwrite` itemflags from your item.
3.) Add the itemflag `give-next` to give the ItemJoin item in the next available slot or `move-next` to move the items that you currently have in the specified slots to the next empty slot.

Let me know!~
