### ISSUE TITLE
player Active-Commands

### ISSUE THREAD

**Issue by FakEEE14** [RockinChaos/ItemJoin#444]
hi
there is a feature that excute comand when met in config yml
but Active-Commands it's only excute command as console
possible to add player: like items to make player excute that command ?
and add a dilay to it like items to ?

**Comment by FakEEE14** [comment]
or adding like execute a command when you gave the player the item

**Comment by RockinChaos** [comment]
Currently it is not possible so I will keep this feature request, it is currently only defaulted to console.
I will add support for the existing command identifiers.

**Comment by FakEEE14** [comment]
great
thank you

**Comment by RockinChaos** [comment]
A few years late but this feature is now implemented.
All executors can be used excluding the `delay:` and `swap-item:` executors for obvious reasons.
The only addition that is different is that the `first-join:` executor exists for Active-Commands but not for items.

Link; https://ci.craftationgaming.com/job/ItemJoin/873/
**Remember to remove your old ItemJoin.jar file**

Let me know!~
