### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DynamicThijs** [RockinChaos/ItemJoin#45]
Getting these messages on every player join, no stacktraces.

ItemJoin Please contact the plugin developer immediately!
ItemJoin This may cause critical errors such as not recieving your items!
ItemJoin Something has gone wrong with the maps!

I hope you can fix it

**Comment by RockinChaos** [comment]
Looking into it now I think I have found the issue. I will keep you posted.

**Comment by DynamicThijs** [comment]
Have you made any progress?

**Comment by RockinChaos** [comment]
Please forgive me, this issue has been completely resolved and will be uploaded with ItemJoin v3.4.
My friends Girlfriend has came into town for a few days and we have been hanging out with her so I have not been able to finalize the update as fast.

This is no excuse though! I will have this update out in the next few days.

**Comment by DynamicThijs** [comment]
I'll forgive you :p 
Thanks for the fix :)

**Comment by RockinChaos** [comment]
ItemJoin v3.4 has been uploaded! This has been tested and fixed. Thank you for your patience.
