### ISSUE TITLE
ItemJoin>Menu>CustomModelData: Preview glass panes should represent the item being selected.

### ISSUE THREAD

**Issue by ryantheleach** [RockinChaos/ItemJoin#452]
**Is your feature request related to a problem? Please describe.**
When creating an itemjoin item from a custom item, the customModelData was ignored. (bug?)

I then attempted to set the CustomModelData using the menu option and discovered that the glass panes had all different button effects.

![image](https://user-images.githubusercontent.com/141554/148405328-d118a4cc-ee3c-49e3-b0df-90129bfa8824.png)

**Describe the solution you'd like**
I would 
1. Like the custom item dropped customModelData to be preserved.
2. Have the CustomModelData Menu use previews of the item instead, this would allow people to see the items graphically when choosing a model.

**Comment by RockinChaos** [comment]
Sorry this took so long to get to, I implemented some changes to the menu that use the defined item material and apply the model data so you can preview how it would look (aside from the preview you see in the main item definition menu prior to saving).

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
