### ISSUE TITLE
There is a strong drop in tps about once a day.

### ISSUE THREAD

**Issue by thears2** [RockinChaos/ItemJoin#454]
Hello! I use ItemJoin.  Please tell me why such a disaster can happen? 
For me this happens about once a day, after which I reload the plugin 
using plugman and for a certain time everything is normalized, 
and then again in a circle.
https://pastebin.com/D3jtKS27 - my config.yml
https://pastebin.com/Z0RMk3VH - my items.yml
https://timings.aikar.co/?id=5fa480afbc7446b7bd2a5f06694ef226 - my timings
Thanks in advance for your attention!

**Comment by RockinChaos** [comment]
Hmmm so, everything seems normal with your timings on the part of plugins honestly.

The only thing that is high timings is the item animations task which is expected but I noticed a few things.
The items.yml you provided contains a lot of the default example items which can be hurting the server performance for no reason. Is there any specific reason for this?

I went ahead and cleaned up the items.yml so it doesn't include the animations as it doesn't seem you were using them.
Link; https://pastebin.com/0wdsyvVe

**Try that items file and let me know if it fixes the issue. If it does then it narrows down the issue**.

**Comment by thears2** [comment]
> Hmmm so, everything seems normal with your timings on the part of plugins honestly.
> 
> The only thing that is high timings is the item animations task which is expected but I noticed a few things. The items.yml you provided contains a lot of the default example items which can be hurting the server performance for no reason. Is there any specific reason for this?
> 
> I went ahead and cleaned up the items.yml so it doesn't include the animations as it doesn't seem you were using them. Link; https://pastebin.com/0wdsyvVe
> 
> **Try that items file and let me know if it fixes the issue. If it does then it narrows down the issue**.

It's been working great for 2-3 days now with your help! Thanks!

**Comment by exzolink** [comment]
@RockinChaos latest update has memory leak or something like that, 5.2.3 - 40% of ticks, 5.2.2 - less than 1%

**Comment by exzolink** [comment]
Some lambda (scheduler i guess) in ItemUtilities class takes 35-40% of ticks

**Comment by exzolink** [comment]
And I dont use animations

**Comment by exzolink** [comment]
> And I dont use animations or dynamic

**Comment by RockinChaos** [comment]
> And I dont use animations and dynamic

Would you be able to create a new issue with your items.yml, config.yml, and a link to the timings, please?
This will help me narrow down the issue in the code.

https://github.com/RockinChaos/ItemJoin/issues/new/choose
