### ISSUE TITLE
Item Flag: hide-enchantments Only

### ISSUE THREAD

**Issue by Zamoar** [RockinChaos/ItemJoin#456]
**Is your feature request related to a problem? Please describe.**
I would like to be able to only hide the enchantments of an item since hide-flags hides ALL of the attributes, such as firework color, and damage the item does. 

There could also be flags for other specific attributes as well.

**Describe the solution you'd like**
hide-enchantments - Hides only enchantments.

**Describe alternatives you've considered**
I've just been using hide-flags and could input the lore myself, but I feel like it would be much simpler to just hide the enchantments with a flag.

**Comment by RockinChaos** [comment]
Seems simple enough, will update you here once I implement it.

**Comment by RockinChaos** [comment]
Apologies that it took so long to get to this feature.
Good news though! It has officially been added in the latest snapshot and is slated for the official release!

Link: https://ci.craftationgaming.com/view/Chaos/job/ItemJoin/871/
**Remember to remove your old ItemJoin.jar file**

Let me know!~
