### ISSUE TITLE
Incorrect language file

### ISSUE THREAD

**Issue by AdminHcat** [RockinChaos/ItemJoin#457]
Both traditional Chinese and Chinese used tw-lang.yml this is incorrect

The correct one should be 
Chinese -> cn-lang.yml
Traditional Chinese -> tw-lang.yml

We usually use Chinese to call simplified Chinese

**Comment by RockinChaos** [comment]
I sincerely apologize for the late reply on this.
I did some testing and I see the issue you are having.

Simplified Chinese calls cn-lang.yml
Traditional Chinese calls tw-lang.yml.

However Chinese alone should call simplified but instead it calls traditional.

I have fixed this issue for the next release, you will see this change in the following snapshot;
Link; https://ci.craftationgaming.com/job/ItemJoin/799/
**Remember to remove your old ItemJoin.jar file**
