### ISSUE TITLE
Item permission-node dont work

### ISSUE THREAD

**Issue by PinaYTTT** [RockinChaos/ItemJoin#463]
Hello, I have an item that is only for Owners and none of the other ranks should be able to have it. But when I enter the server with another rank, the server gives me the item that is only for Owners.

**Pastebin**
[items.yml](https://pastebin.com/GvzB0Rms)

**information:**
 - Resource Version and Build Number: v5.2.3-RELEASE-b789
 - Server Version "Spigot-1.8.8"

**Comment by RockinChaos** [comment]
You need to enable permissions in your config.yml under the permissions section.

Please see; https://github.com/RockinChaos/ItemJoin/wiki/Config.yml#permissions
