### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by lucylucy09Q2WE312** [RockinChaos/ItemJoin#465]
Im op so why do i get this msj? "Failed to give you 1 items,you are not allowed to overwrite items!?

**Comment by RockinChaos** [comment]
Being OP doesn't bypass the `items-Overwrite: false` boolean set at the top of your items.yml.
If you wish to overwrite items simply set it to true.

Hopefully that answers your question :)

**Comment by lucylucy09Q2WE312** [comment]
Thx you that fixxed it,also if you are kind to help me,how can i set up so they cant drop only the compass?when i set up like this 
nobody can drop any items,i want this to be just for the compas,not to all the items from the game
Prevent:
  Pickups: true
  itemMovement: true
  Self-Drops: true
  Death-Drops: true
  Bypass: OP

**Comment by RockinChaos** [comment]
I sincerely apologize for the late reply, The info you provided are **GLOBAL** modifiers so they apply to all items.
If you want actions to apply only to specific ItemJoin items you need to add `itemflags`.

Simply add `itemflags: self-drops, death-drops, item-store` to your compass item.

See itemflags here; https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#defining-an-items-itemflags
