### ISSUE TITLE
How to make when a player go back to the main world he gets the join items?

### ISSUE THREAD

**Issue by x10k** [RockinChaos/ItemJoin#466]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**

How to make when a player go back to the main world he gets the join items? Beacause When i tried whit in the settings doesent work

**Pastebin**
https://pastebin.com/VDba4aBj - Config
https://pastebin.com/ujAFWtJw - Items

**Please complete the following information:**
 - Resource Version and Build Number: v5.2.3
 - Server Version Spigot-1.8.8

**Additional context**
I Tried to fix it in the settings making it when switch server gives you the join items but nothing  :|

**Comment by RockinChaos** [comment]
Sorry for the late reply, it sounds like the `WORLD-SWITCH` trigger would give you the result you are looking for.
So add this to the existing trigger you have defined for each item.

Example;
`triggers: JOIN, WORLD-SWITCH`
