### ISSUE TITLE
1.18.2 error on getting NBTData

### ISSUE THREAD

**Issue by nathanielcutajar** [RockinChaos/ItemJoin#467]
## Thanks for taking the time to open a bug report!

**Describe the bug**
When I upgraded the server to 1.18.2, and a player joins, the plugin is giving me this error:
[Server] ERROR [ItemJoin_ERROR] {ItemMap} An error has occured when setting NBTData to an item.
It is repeating 3 of them every 9 seconds.
The plugin has even been updated to the latest snapshot

When I then used the item tied to this plugin (to show off a menu using the ChestCommands plugin), I get this error:
https://pastebin.com/WQhX9mJT
it mainly seems that it just needs a bump in version support I'm assuming

**To Reproduce**
1. Update to 1.18.2
2. Have an item set for the player to interact with
3. Player joins the server (first error)
4. Player interacts with the item (second error)

**Expected behavior**
Item opens and does now show any errors

**Screenshots**
n/a

**Pastebin**
Error on activating item: https://pastebin.com/WQhX9mJT
ItemJoin Config Yaml: https://pastebin.com/sxJYzq9v
ItemJoin Items Yaml: https://pastebin.com/USHGTpPj

**Please complete the following information:**
 - ItemJoin-5.2.4-SNAPSHOT-b799
 - purpur-1.18.2-1574
 - 
**Additional context**
n/a

**Comment by RockinChaos** [comment]
Sounds like something pretty major changed in regards to their class structure, testing this now.
I will let you know when I have a new snapshot available.

**Comment by compieter-gh** [comment]
I have the same issue.

**Comment by mesl** [comment]
Same issue here, But seems like its already a confirmed bug

**Comment by RockinChaos** [comment]
@mesl @compieter-gh @nathanielcutajar 
Okay, so no guarantees but it seems all issues with 1.18.2 have been resolved with the patches I have made.
Please try the latest snapshot and let me know; https://ci.craftationgaming.com/job/ItemJoin/800/

**Comment by Strikerpro21** [comment]
i got the same problem when wil be the next update?

**Comment by OverCrave** [comment]
Latest snapshot (801) works fine with 1.18.2 on my end

**Comment by Strikerpro21** [comment]
the download link is not working for some reason from rockinchaos

**Comment by OverCrave** [comment]
Use this one: https://ci.craftationgaming.com/job/ItemJoin/lastSuccessfulBuild/ the build he linked seemed to have been deleted

**Comment by Strikerpro21** [comment]
thank you so much
