### ISSUE TITLE
Give item only once per player on region-enter

### ISSUE THREAD

**Issue by jg2002-j** [RockinChaos/ItemJoin#468]
Hi, I'm trying to set up this plugin for a server and need to use region enter as the way to get new items. However, I want it to be an exclusive item unlocked when players discover the area - so ideally it should only drop once per player (irrelevant of lifetimes, or inventory content). 

I've noticed the item won't drop if I already have it in my inventory, but if I store it in a chest or throw it on the ground before entering the region I can duplicate it as many times as I need. 

So yeah, if there is a way to only obtain the item once per player - I'd be grateful for any help! Ty :))

**Comment by jg2002-j** [comment]
Nvm im dumb i just found the IP item lock thingy sorry and thank u awesome plugin!!

**Comment by jg2002-j** [comment]
It doesn't seem to work though SORRYAGAIN aaa

In Itemflags I enabled IP Limit but I can walk through the region multiple times and get multiple copies of the item. I de-oped and encountered the same issue.

**Comment by jg2002-j** [comment]
![image](https://user-images.githubusercontent.com/85451562/159570179-1a9f51e3-210d-4581-ae55-735265d01b90.png)
- IP limit enabled but can obtain the item multiple times
- also sometimes I get 2 drops instead of one when walking through the region

**Comment by RockinChaos** [comment]
Okay so after some testing I think I misunderstood your issue.
You don't want to limit the item to a specific IP for each player, you want to make the item only be given ONCE per player.

The itemflag you were looking for is `FIRST-JOIN` or `FIRST-WORLD` if you want per world.
Try that and let me know!~
