### ISSUE TITLE
Items given but no name or permissions. Running 1.10.2 server.

### ISSUE THREAD

**Issue by EvanDawesome** [RockinChaos/ItemJoin#47]
I am running the latest version of both the plugin and the server jar. Whenever A player joins their items instantly turn into default items. How could I fix this?

**Comment by RockinChaos** [comment]
Please send your items.yml, config.yml, en-lang.yml as well as check for any error codes in the console please.

**Comment by EvanDawesome** [comment]
[config.txt](https://github.com/RockinChaos/ItemJoin/files/338590/config.txt)
[en-lang.txt](https://github.com/RockinChaos/ItemJoin/files/338591/en-lang.txt)
[items.txt](https://github.com/RockinChaos/ItemJoin/files/338592/items.txt)

**Comment by EvanDawesome** [comment]
You get them? I made them into .txt and then posted on here.

**Comment by RockinChaos** [comment]
Yes, I have been using them on 1.10.2 and I am having issues reproducing this error. I have a few more things to try.

**Comment by RockinChaos** [comment]
Can you explain what you mean by default items? I am getting the items perfectly fine.

**Comment by EvanDawesome** [comment]
I mean by default items the items in the list. The only way a player is getting the functionality of that item and not just a sword that says Diamond Sword is when they are OPed. They also have itemjoin.* still just plain vanilla items given.

**Comment by EvanDawesome** [comment]
here are my plugins. please just look at the .jars for many folders are remaining from a no longer used plugin.
[filelist.txt](https://github.com/RockinChaos/ItemJoin/files/342813/filelist.txt)

**Comment by RockinChaos** [comment]
Can you try the new release of ItemJoin and tell me if that fixes it.

https://www.spigotmc.org/resources/itemjoin.12661/download?version=100153

**Comment by EvanDawesome** [comment]
Unfortunately I am having the same problem however the items stay named and linked to commands for around an extra second. I am honestly not sure what is happening.

**Comment by EvanDawesome** [comment]
figured it out!! I had to toggle this false " check items: false" in the ChatGuard plugin. Just to inform you of what caused it. If you want you may want to take note of this on your plugins homepage.

**Comment by EvanDawesome** [comment]
Thank you for your help!

**Comment by RockinChaos** [comment]
Lol thank god I was getting frustrated testing all of those plugins. xD

No, Thank you! You really helped me there lol.

Sorry I wasnt able to find it to help you out sooner xD
