### ISSUE TITLE
Enchantment with a placeholder

### ISSUE THREAD

**Issue by FakEEE14** [RockinChaos/ItemJoin#474]
Hello

**Describe the bug**
Can't put a placeholder with a number output at item enchantment 

**To Reproduce**
Set any placeholder that output a number at the enchantnumber
Like :ALL_DAMAGE:%player_level%

**Expected behavior**
To set the enchantment as the placeholder number
When you /ij reload ,in chat say the number is not a number

**Please complete the following information:**
 - Resource Version: dev build 812
 - Server version: paper 1.18.2 build

**Comment by FakEEE14** [comment]
my bad i think it was a bug
![image](https://user-images.githubusercontent.com/68513641/163563074-fc63c37a-e2a7-4db2-9f2b-0fd3ee89f659.png)

**Comment by FakEEE14** [comment]
Hi again
this is so usefull , it's Possible to add it ?

**Comment by RockinChaos** [comment]
Hi, yes it is possible to add.
I will start working on this as soon as I can, currently, bugs take priority over feature requests so I work on feature requests once I complete all bug reports.

I will update you here with a snapshot once I complete this feature.

**Comment by FakEEE14** [comment]
Cool and thank you

**Comment by FakEEE14** [comment]
hello sir, any news ?

**Comment by FakEEE14** [comment]
hello
any news sir

**Comment by RockinChaos** [comment]
No news atm. This is planned for the next release so it shouldn't be too long.
Currently, have this partially done but I had to stop to implement Minecraft 1.19 support so I can start preparing for the next release.

I don't want to give an exact date but sometime before the end of the month. Could be a few days or it could be a week or so, just depends on how quickly things progress.

**Comment by FakEEE14** [comment]
still no news sir?

**Comment by FakEEE14** [comment]
still no news sir?

**Comment by RockinChaos** [comment]
No news, as stated before it's slated for the next release which is still not completed. I have progressed a bit on this but bug reports are taking priority. Once I get everything ironed out with Minecraft 1.19 I should be able to get this finished the rest of the way. I expect to release the official update in the next few weeks so this feature will be implemented soon.

**Comment by FakEEE14** [comment]
update came NICE

**Comment by FakEEE14** [comment]
hi
any hope for this to be implemented ?

**Comment by FakEEE14** [comment]
hi and good day sir
any news for this ?

**Comment by FakEEE14** [comment]
hello
still no news sir ?

**Comment by FakEEE14** [comment]
hi sir @RockinChaos 
this is possible or not happening ?

**Comment by RockinChaos** [comment]
Thank you for being patient, the enchant system has been reworked to incorporate this feature.
You can specify both the enchant name & level as a placeholder individually assuming you have a plugin with placeholders that can specify a string enchant name.

For your usage you would want to do (for example);
`enchantment: FIRE_ASPECT:%player_level%, DAMAGE_ALL:%player_level%`

Please let me know if you encounter any issues.

Link; https://ci.craftationgaming.com/job/ItemJoin/857/
**Remember to remove your old ItemJoin.jar file.**

**Comment by FakEEE14** [comment]
hi and good day sir 
this is the item in config file

  boots-item:
    id: IRON_BOOTS
    slot: boots
    name: '&bBlazefury - %data_bootenchant%'
    enchantment: 'PROTECTION_ENVIRONMENTAL:3, %data_bootenchant%'
    itemflags: inventory-modify, death-drops, self-drops
    triggers: join, world-switch
    enabled-worlds: world

this placeholder return this
![image](https://user-images.githubusercontent.com/68513641/206895878-2f230a0d-19aa-455d-ae99-bb064e00eeff.png)

but it break and don't put any enchant on it

**Comment by FakEEE14** [comment]
and noticed if place holder have the symbole , it get break like
[ItemJoin_ERROR] {ItemStatistics} An error occurred in the config, %data_boot is not a number and a number was expected!
but the place holder is %data_boot,level% or %data_boot,enchant%

**Comment by RockinChaos** [comment]
Enchantment is incorrectly specified. You still have to follow the enchantment system's rules.
`Enchant:Level`

Therefore your placeholder has to be `%data_boot_name%:%data_boot_level%` for example.
Meaning it has to be split with a colon `:` and this cannot be inside the placeholder either, it has to be two individual placeholders.

**Comment by FakEEE14** [comment]
so not piossible to set a long string to add all enchantment we want to a single placeholder ?
like %data_boot_level% = PROTECTION_ENVIRONMENTAL:3, PROTECTION_FALL:%player_level%
and put only the placeholder

**Comment by RockinChaos** [comment]
Done, any levels set to 0 or below will automatically not be set.

Link; https://ci.craftationgaming.com/job/ItemJoin/861/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by RockinChaos** [comment]
Since this seems to be inactive I am marking this as filled since the feature seems to work as intended.

Link: https://ci.craftationgaming.com/view/Chaos/job/ItemJoin/871/
**Remember to remove your old ItemJoin.jar file**
