### ISSUE TITLE
Massive lag

### ISSUE THREAD

**Issue by iRama7** [RockinChaos/ItemJoin#482]
## Thanks for taking the time to open a bug report!

**Describe the bug**
The plugin is causing a lot of lag in my server.

**To Reproduce**
Just use the plugin with 10+ players switching servers

**Expected behavior**
no lag

**Screenshots**
![image](https://user-images.githubusercontent.com/67761349/170886326-d5b26973-36e4-4c5c-a629-fdc29cd5891f.png)

**Pastebin**
[Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links as well as any related error codes from the console window.](https://timings.aikar.co/?id=b624f9c59f86412ca6918a315d012a9a#timings)

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.3-RELEASE-b789
 - Server Version git-Paper-411 (MC: 1.17.1)

**Additional context**

**Comment by RockinChaos** [comment]
Going to mark this as resolved since it seems you closed the ticket on Discord.
Please let me know if this still continues with the updated snapshot I provided in the ticket on Discord.

**Comment by iRama7** [comment]
Hello,

It still happening with the latest version.
