### ISSUE TITLE
skins restorer unsupported

### ISSUE THREAD

**Issue by FakEEE14** [RockinChaos/ItemJoin#486]
hi i see this error on 1.19 only  [ItemJoin_ERROR] {DependAPI} [2] Unsupported SkinsRestorer version detected, unable to set the skull owner.

**Comment by RockinChaos** [comment]
So I can't seem to replicate this with the latest skinsrestorer.

Can you provide the following;
1.) Screenshot of `/itemjoin`
2.) Screenshot of `/version SkinsRestorer`
3.) Paste of your item in question.

**Comment by FakEEE14** [comment]
hi
when you have the latest version of skin restorer installed on bungeecord and the latest itemjoin on 1.19 minecraft and add on join item with a playername head
when you join the server and this error pops

**Comment by danirod12** [comment]
Same issue.
Spigot: git-Purpur-1605 (MC: 1.18.2)
ItemJoin: 5.2.4-b822
SkinsRestorer: 14.2.1, proxy mode
![2022-07-16_22 06 22](https://user-images.githubusercontent.com/69750264/179368793-4e3548ac-84a2-4c69-bfa3-637c80d846be.png)

**Comment by RockinChaos** [comment]
> Same issue. Spigot: git-Purpur-1605 (MC: 1.18.2) ItemJoin: 5.2.4-b822 SkinsRestorer: 14.2.1, proxy mode ![2022-07-16_22 06 22](https://user-images.githubusercontent.com/69750264/179368793-4e3548ac-84a2-4c69-bfa3-637c80d846be.png)



> hi when you have the latest version of skin restorer installed on bungeecord and the latest itemjoin on 1.19 minecraft and add on join item with a playername head when you join the server and this error pops


The latest snapshot should now address this issue.
Link; https://ci.craftationgaming.com/job/ItemJoin/844/
**Remember to remove your old ItemJoin.jar file**

**Comment by danirod12** [comment]
> The latest snapshot should now address this issue. Link; https://ci.craftationgaming.com/job/ItemJoin/844/ **Remember to remove your old ItemJoin.jar file**

Cannot configm. Bug exist
![2022-07-26_22 23 03](https://user-images.githubusercontent.com/69750264/181094436-d771269d-b972-4c63-8a73-56a0df4ced93.png)
s

**Comment by FakEEE14** [comment]
same here

**Comment by RockinChaos** [comment]
> > The latest snapshot should now address this issue. Link; https://ci.craftationgaming.com/job/ItemJoin/844/ **Remember to remove your old ItemJoin.jar file**
> 
> Cannot confirm. Issue still exists ![2022-07-26_22 23 03](https://user-images.githubusercontent.com/69750264/181094436-d771269d-b972-4c63-8a73-56a0df4ced93.png)



> same here

Can you please provide your skinsrestorer config & the ItemJoin item so I can test.
I have tried just about everything and I am unable to replicate this.

Also enabling debugging in the config.yml of ItemJoin and providing the error code that appears afterwards would help as well.

**Comment by danirod12** [comment]
SkinsRestorer in bungee-mode (In backend server there is a readme to setup plugin at bungeecord)
Giving bungeecord SkinsRestorer config, ItemJoin config and items

[config.zip](https://github.com/RockinChaos/ItemJoin/files/9257936/config.zip)

**Comment by danirod12** [comment]
All is working, but this messages are really annoying, could you disable it or provide a config option for it?

**Comment by RockinChaos** [comment]
Ah I see so it looks like its just a communication issue between the server and bungee.
I should be able to fix this, give me a little bit to produce a fix for the next snapshot.

**Comment by PaBox** [comment]
I also have the same problem, but I am playing on 1.16.5 (same versions as above though). I got to mention though I am using the server in offline mode.

**Comment by RockinChaos** [comment]
Okay so, it's more than just a message it turns out the SkinsRestorer functionality isn't working at all.
Currently, it is impossible to make any API calls via the backend server therefore I have simply just disabled SkinsRestorer support when proxy mode is detected.

The latest snapshot should resolve your issue.
Link; https://ci.craftationgaming.com/job/ItemJoin/847/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=467409

**Comment by VladOliinyk** [comment]
Hello there! 
Facing the same issue at the moment:
![image](https://github.com/RockinChaos/ItemJoin/assets/5873850/8d770337-8c24-4b04-ba9f-47d028f193ca)

**Comment by VladOliinyk** [comment]
Just updated to 6.0.2 - same thing.
![image](https://github.com/RockinChaos/ItemJoin/assets/5873850/a532970c-ba44-4563-9be3-56bb49a34703)

will try to update Skin Restorer on bungee and reply here

**Comment by VladOliinyk** [comment]
@RockinChaos sorry to ping you, but here we have a similar issue at the moment. Have you seen this?

**Comment by RockinChaos** [comment]
@VladOliinyk Update to the latest snapshot
https://ci.craftationgaming.com/job/ItemJoin/
- If the website fails to load, refresh it a few times.

**Comment by VladOliinyk** [comment]
> @VladOliinyk Update to the latest snapshot https://ci.craftationgaming.com/job/ItemJoin/
> 
> * If the website fails to load, refresh it a few times.

Thanks, will try asap, and give a feedback here!

**Comment by VladOliinyk** [comment]
> @VladOliinyk Update to the latest snapshot of ItemJoin or downgrade your SkinsRestorer version. https://ci.craftationgaming.com/job/ItemJoin/
> 
> * If the website fails to load, refresh it a few times.

@RockinChaos all is good. No errors, this issue is gone. Works fine!
Thanks <3
