### ISSUE TITLE
Version that support Minecraft Paper/spigot/bukkit 1.19?

### ISSUE THREAD

**Issue by HighPriestKing** [RockinChaos/ItemJoin#489]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
A clear and concise description of what the problem is. Ex. I need help creating a custom item that is given to the player on join. I want it to be a Diamond Sword and [...]

Looking for jar file for minecraft 1.19

**Pastebin**
Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links. This way if we need to help you modify any of these configuration files we will already have them handy.

**Please complete the following information:**
 - 5.2.4 b804 
 - Server Version: Paper Spigot 1.19

**Additional context**

5.2.4 b804 is not compatiable with minecraft 1.19

Is it just that i cant find it? or does it not exist?

**Comment by RockinChaos** [comment]
Integration Server (Snapshots): https://ci.craftationgaming.com/

**Comment by HighPriestKing** [comment]
Keep on Rockin man! You Rule!
