### ISSUE TITLE
Maps error on join.

### ISSUE THREAD

**Issue by DynamicThijs** [RockinChaos/ItemJoin#49]
I was finally able to test the new ItemJoin release, but I still get the messages:
[ItemJoin Please contact the plugin developer immediately!
[ItemJoin This means your custom map will not be rendered!
[ItemJoin Something has gone wrong with the maps!

My config: http://pastebin.com/7D9CkNCw
My items.yml: http://pastebin.com/R3ka97Bc
I did not edit the language file

**Comment by DynamicThijs** [comment]
I figured out that it's just something with the default config, if I remove every item from the list except the first one, it'll work fine.

**Comment by RockinChaos** [comment]
Hm... I will look into this again but I cant seem to replicate it. This is because you removed the map item so it doesnt have to render maps to the error never appears.

**Comment by DynamicThijs** [comment]
Nope, I changed the maps before I removed the items

**Comment by RockinChaos** [comment]
This has been fixed as of ItemJoin v3.5 and it has been released, I have decided to temporarily remove the custom maps item until spigot fixes their shit.

You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107083
