### ISSUE TITLE
FILLED_MAP not valid ID in 1.12.2

### ISSUE THREAD

**Issue by JonnygamingTv** [RockinChaos/ItemJoin#491]
items.yml:
```yml
items-Version: 8
items-Delay: 2
items-Overwrite: true
items-Spamming: false
items-RestrictCount: false
items:
  map-item:
    id: FILLED_MAP
    map-id: 3
    slot: 3
    name: '&eNews'
    lore:
      - '&7Any good news today?'
    itemflags: inventory-modify, unbreakable, hide-attributes, death-drops, self-drops, creativebypass
    triggers: join, respawn, world-change
    permission-node: 'itemjoin.map'
    enabled-worlds: world
```

I get the following error:
```
[18:31:10] [Server thread/INFO]: [ItemJoin] Configuration(s) Reloaded!
[18:31:11] [Server thread/ERROR]: [ItemJoin_ERROR] {ItemDesigner} The Item map-item's Material 'ID' is invalid or does not exist.
[18:31:11] [Craft Scheduler Thread - 59/INFO]: [ItemJoin] Hooked into { WorldGuard, Citizens, Vault }
[18:31:11] [Server thread/WARN]: [ItemJoin_WARN] {ItemDesigner} The Item map-item will not be set!
[18:31:11] [Craft Scheduler Thread - 59/INFO]: [ItemJoin] 5 Custom item(s) loaded!
```
And as I previously used (on old ItemJoin version) ID: MAP, it just creates a new map (not setting the correct map-id)

Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by RockinChaos** [comment]
So FILLED_MAP is 1.13+ whereas MAP is for versions below 1.13 aka 1.12.2.

I would need some additional info to figure out why it wouldn't be working for you, can you provide the output when you type `/itemjoin` so I can test the exact build number?

**Comment by JonnygamingTv** [comment]
ItemJoin v5.2.4-RELEASE-b822 by RockinChaos

**Comment by RockinChaos** [comment]
> ```yaml
> items-Version: 8
> items-Delay: 2
> items-Overwrite: true
> items-Spamming: false
> items-RestrictCount: false
> items:
>   map-item:
>     id: FILLED_MAP
>     map-id: 3
>     slot: 3
>     name: '&eNews'
>     lore:
>       - '&7Any good news today?'
>     itemflags: inventory-modify, unbreakable, hide-attributes, death-drops, self-drops, creativebypass
>     triggers: join, respawn, world-change
>     permission-node: 'itemjoin.map'
>     enabled-worlds: world
> ```

Hmmmm so after checking it seems that the map id is being properly set.
Could you send me your player.dat file (get the item then log off the server) so I can inspect it with my nbt editor to confirm if the mapid is set or not.

**Comment by JonnygamingTv** [comment]
Using ItemJoin v5.2.5-RELEASE-b850

[Uploading 79e21065-394d-4e73-ab7d-a21d13763be6.dat…]()
[itemjoin_test_b850.zip](https://github.com/RockinChaos/ItemJoin/files/9445591/itemjoin_test_b850.zip)

**Comment by RockinChaos** [comment]
Apologies for the late update on this, it took a while to figure this issue out.

A recode was done on the maps to better reflect the original functionality of v4.4.
I have tested it and it seems to work perfectly now on MC 1.12.2 in conjunction with other mapping plugins.

Simply just setting the matching map-id and the renderer will automatically be handled.

Link; https://ci.craftationgaming.com/view/Chaos/job/ItemJoin/875/
**Remember to remove your old ItemJoin.jar file**

Let me know!~
