### ISSUE TITLE
how do I hide an object enchantment

### ISSUE THREAD

**Issue by AkariDream** [RockinChaos/ItemJoin#493]
when I enchant the item. 
it will show enchantments. 
how do to hide it?

**Comment by AkariDream** [comment]
and idk how to customize the players head

**Comment by RockinChaos** [comment]
https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#defining-an-items-itemflags
**hide-attributes** - Hides ALL attributes, such as firework color, damage the item does, **enchantments.** (Hides everything from lore except the custom lore).

https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#creating-a-custom-skull-player-heads
via `skull-owner: '%player%'` or `skull-texture: 'url-13e8bbc8d174aecd6b46888fa63f9bade14b042e5e17063139d67f8e0163a38'`

**Comment by AkariDream** [comment]
thx
