### ISSUE TITLE
Question about a parameter 

### ISSUE THREAD

**Issue by Smiil3** [RockinChaos/ItemJoin#495]
Hello, I need help creating a custom item that is given to the default player on join but not to opped player. Which parameter should I use ?

- config.yml | https://pastebin.com/UVFGXdKU
- items.yml | https://pastebin.com/P01Ffvwc

 - Resource Version and Build Number: v.5.2.5-RELEASE-b850
 - Server Version | Paper-1.17.1

**Comment by RockinChaos** [comment]
I would enable Obtain-Items-OP in the config.yml as this will make it so OP Players are required to have the permission of the item to receive it while allowing NON-OP players to automatically get the item.
