### ISSUE TITLE
Instant Join

### ISSUE THREAD

**Issue by Sxlect** [RockinChaos/ItemJoin#496]
## Thanks for taking the time to open an assistance request!

Is there a way to make it so you instantly have the items when you join, basically so there's no delay with the items spawning in your Hotbar/inventory upon joining?

**Comment by RockinChaos** [comment]
Yes you can change the delay in the items.yml at the top of the file you will see `items-Delay` setting this to 0 is the lowest possible delay. However if you notice issues then you will need to increase the delay, typically this is useful when other plugins are trying to mess with the player inventory.
