### ISSUE TITLE
not working in my server

### ISSUE THREAD

**Issue by powercoque** [RockinChaos/ItemJoin#5]
server version spigot 1.8.8
mv version 1.5
multiverse inventories
good configurated
help!!
please

**Comment by XSilverSlayerX** [comment]
Can you please post your config and items.yml.  any error codes in console? I'll try to look into this but I'm very sick so it might take some time.

**Comment by powercoque** [comment]
#// <>==<>==<> ItemJoin's Global Settings  <>==<>==<> //#
#// <>==<>==<> By XSilverSlayerX <>==<>==<> //#
#// These options work best with Multiverse-Inventories! http://dev.bukkit.org/bukkit-plugins/multiverse-inventories //#
#// NOTE!: ALL WORLDS DEFINED UNDER HERE MUST BE SETUP IN THE items.yml FILE! //#
CheckforUpdates: true #// Disable this if you dont want to be notified if there is an update. //#
First-Join-Only: false #// Set this to true if you wish to get the items on the players first login on the server. You must be in that world listed under items.yml worldlist. //#

#// Give items on respawn //#
give-on-respawn: true #// Set this to true if you want to receive the items for each specified world below once you respawn from death. //#
AllowOPBypass-give-on-respawn: false #//Set this to true if you wish for OP players to bypass this //#
give-on-respawn-worldlist:
  - test
  - lobby

#// Give items on world change //#
give-on-world-change: true #// Set this to true if you want to receive the items for each specified world below once you enter it. "Changed World" //#
AllowOPBypass-give-on-world-change: false #//Set this to true if you wish for OP players to bypass this //#
give-on-world-change-worldlist:
  - test
  - lobby

#// Clear items on world change //#
clear-on-world-change: true #// Set this to true if you want to clear your inventory on "Changed World" You can define what worlds under clear-inventory-worldlist. //#
AllowOPBypass-clear-on-world-change: false #//Set this to true if you wish for OP players to bypass this //#
clear-on-world-change-worldlist: #List the worlds below that you want to be involved in the Global Settings. //
  - test
  - lobby

#// Clear items on join //#
clear-on-join: true #// Set this to true if you want your inventory to be cleared on join. Must be in that world on join. Define allowed worlds under clear-on-join-worldlist. //#
AllowOPBypass-clear-on-join: false #//Set this to true if you wish for OP players to bypass this //#
clear-on-join-worldlist: 
  - test
  - lobby

#// Prevent the dropping of items on death //#
prevent-death-drop: true #// Set to true to prevent players from dropping items on death. //#
AllowOPBypass-prevent-death-drops: false #//Set this to true if you wish for OP players to bypass this //#
prevent-death-drops-worldlist:
  - test
  - lobby

#// Prevent players from moving items around in their inventory //#
prevent-inventory-modify: true #// Set to true to prevent players from moving items in their inventory and storing items in chests. //#
AllowOPBypass-prevent-inventory-modify: false #//Set this to true if you wish for OP players to bypass this //#
prevent-inventory-modify-worldlist:
  - test
  - lobby

#// Prevent players from picking up items on the ground //#
prevent-pickups: true #// Set to true to prevent players from picking up items. //#
AllowOPBypass-prevent-pickups: false #//Set this to true if you wish for OP players to bypass this //#
prevent-pickups-worldlist:
  - test
  - lobby
	
#// Prevent players from dropping items out of their inventory //#
prevent-drops: true #// Set to true to prevent ALIVE players from dropping items. //#
AllowOPBypass-prevent-drops: false #//Set this to true if you wish for OP players to bypass this //#
prevent-drops-worldlist:
  - test
  - lobby

**Comment by powercoque** [comment]
#// <>==<>==<> ItemJoin's Join Items <>==<>==<> //#
#// <>==<>==<> By XSilverSlayerX <>==<>==<> //#
#// For per-world support this best works with Multiverse-Inventories! http://dev.bukkit.org/bukkit-plugins/multiverse-inventories //#
#// Otherwise you will need to set clear-on-world-change to true if you want to get the new items when you change worlds. //#
#// Then you will need to set give-on-world-change to true to recieve the new items. //#

worldlist: #// This is the list of worlds that have custom join items. //#
  - test
  - lobby

#// For every world listed in the worldlist, you need to make a section for it. //#
world:
  items:
    1: #// This is the slot, 1 is first slot in hot bar, 36 is bottom right in inventory. //#
      id: WOOD_SWORD #// This is a wooden sword. See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for item names! //#
      data-value: 0
      name: '&3Junk Sword' #// Colors are shown with & and then it's code.  Use two &s to denote an actual &. //#
      lore:
        - '&7This is a pretty junk sword'
        - '&7You will probably want to get'
        - '&7A &bDiamond &7one'
      commands:
        - 'say this is item slot 1' #// This is a command! //#
        - 'say how is your day?' #// You can even execute more than one command! //#
    3:
      id: WOOD_PICKAXE #Wood pick
      name: '&aJunk pick' #Leave off options that are unused.
      commands:
        - 'gamemode 1 %player%' #// Also supports the variable %player%. The end result would be /gamemode 1 XSilverSlayerX. Only if I was the one to click the item though. //#
        - 'say this is item 3'
    4:
      id: WOOD_SPADE #// Remember to use the right names!  This is a shovel! //#
      commands: #// Remove this line if you do not want commands for this item. //#
        - 'say i am a command' #// Same for this line. Remove it. //#
    5:
      id: STAINED_GLASS
      data-value: 12 #// Support for data-values. This is the ending number of the item ID. Since brown stained glass is 95:12 we would put 12. So you would get STAINED_GLASS:12. //#
      count: 32 #// How many of this item you would like to recieve. Since this item stacks, you would get 32 brown stained glass. //#
      commands:
        - 'server survival' #// Supports BungeeCord too! (Since its in instance of the player). //#
    9:
      id: COMPASS
      name: '&bClick to Navigate'
      data-value: 0 #// Default data value for an item is 0. So since this is a compass you can just remove the data-value line. //#
      lore:
        - '&l&1BOLD'
world_nether:
  items:
    1:
      id: WOOD_HOE
      name: 'JUNK'
    2:
      id: SEEDS
    3:
      id: WHEAT
      commands:
        - 'say i enjoy life!'
    4:
      id: MINECART
      data-value: 0
      lore:
        - '&l&1BOLD'

**Comment by powercoque** [comment]
the world:
test and lobby

**Comment by XSilverSlayerX** [comment]
Lol I should have said to post each one in pastebin.com

**Comment by powercoque** [comment]
jajaja,sorry

**Comment by XSilverSlayerX** [comment]
And link each one please. Past bin is what I use for finding errors especially in spacing.

**Comment by powercoque** [comment]
ok

**Comment by powercoque** [comment]
console
http://pastebin.com/wCVBSabR

**Comment by powercoque** [comment]
items
http://pastebin.com/CLgvHyz9

**Comment by powercoque** [comment]
config
http://pastebin.com/8UBLaFj8

**Comment by powercoque** [comment]
It is done

**Comment by powercoque** [comment]
full console
http://pastebin.com/gvM3Bi9T

**Comment by XSilverSlayerX** [comment]
Okay, found the problem. You did not setup the config correctly. The config.yml is correct.
Yet the items.yml you listed the 2 worlds you wanted right? Test and Lobby. Now where you list the items you did not change the 
world:
  items:

and

world_nether:
  items:

TO

test:
  items:

AND

lobby:
  items:

For every world listed under items.yml worldlist, MUST be defined under the items.yml as an item so you can recieve them. Does that make some sense?

**Comment by powercoque** [comment]
soo much thx <3 love you ...
very good plugin , i will donate ;)

**Comment by powercoque** [comment]
not works :(

**Comment by XSilverSlayerX** [comment]
Oh i noticed you said you are using multiverse-core 1.5 You need 2.5 for it to work.
http://dev.bukkit.org/bukkit-plugins/multiverse-core/files/28-2-5-b699-beta/

**Comment by powercoque** [comment]
no i write bad 2.5

**Comment by powercoque** [comment]
i delete the plugins ,but not multiverse and itemjoin and still not working
sorry i am español

**Comment by XSilverSlayerX** [comment]
May i ask what world you are trying to get the items in? The name of it

**Comment by powercoque** [comment]
Okay, I think I found the problem , I think is skywarsreloader or other plugin

**Comment by powercoque** [comment]
Yes, it works the only problem is to see how I put all plugin at a time , many thanks

**Comment by RockinChaos** [comment]
Sweet. Let me know if you have any more issues.
