### ISSUE TITLE
still Example items

### ISSUE THREAD

**Issue by UnknownBrueck** [RockinChaos/ItemJoin#50]
hey. So when I change the config to different items and save it, when I restart the server its still the example items. I tried reloading it but it didn't work. Could you please help me.

**Comment by RockinChaos** [comment]
Can you please send me the items.yml you are trying to change it to. (The version that wont save). In a pastebin.com

1.) What version of craftbukkit/spigot are you using?
2.) What version ItemJoin are you using?

So what you are saying is you change the items in the items.yml and save it, then restart the server and return to it and everything you had typed in the items.yml is reverted back to default and you have to rewrite it again?

Are any other files created in the ItemJoin folder? Or is it just items.yml, en-lang.yml, and config.yml?

**Comment by UnknownBrueck** [comment]
http://pastebin.com/MKg6q1Na

**Comment by UnknownBrueck** [comment]
I am also using spigot 1.10

**Comment by RockinChaos** [comment]
You are removing the world: and items: identifier. Its okay to remove the first item "ultra-item"

but you completely removed the identifiers. ItemJoin would break without them.


for each specified world there can be items listed for it.
Here is a corrected version of your items.yml

http://pastebin.com/V22kdbFB


Also, the world you are trying to get items in is what the world identifier should be called.

Since the world I am join is called world this is why it is listed as such


**world:**
   **items:**
       // items go here //

**Comment by UnknownBrueck** [comment]
Thanks so much for the new config. But navigation and adblock are not working for me.

**Comment by RockinChaos** [comment]
I am not sure what you are meaning by not working but I noticed you have a lot of problems with your items.

You should really consult https://www.spigotmc.org/wiki/itemjoin/ when creating items.

First off your adblock item has the data-value in the ID. This cannot be done.

You must put the ID of the item in ID
and create an identifier called data-value and put the data-value in it.
so it would be

id: 35
data-value: 14

Lastly, as for the Navigation you did the correct id by putting Compass but it needs to be uppercased as shown on the spigot materials page. So it should be listed as
id: COMPASS

Here is a corrected version of the items.yml, let me know if you have any more problems.
http://pastebin.com/471hMMjK

**Comment by UnknownBrueck** [comment]
Thanks for the help recently, that was all I needed.  Thanks! : )
