### ISSUE TITLE
Color code not working on items

### ISSUE THREAD

**Issue by iFamm** [RockinChaos/ItemJoin#500]
when i rename an item with color code. for example: &eCompass. the color code doesnt show and instead its just the normal color code aka white. and when i rename it in the files. it just says the id of the item

**Comment by RockinChaos** [comment]
I apologize for the late reply, my computer died last month and replacement parts took a while to get.

I tested your issue and cannot replicate it. 
If you can provide your items.yml in a pastebin.com link I will be able to assist you further.
