### ISSUE TITLE
void teleport issue.

### ISSUE THREAD

**Issue by SirCraftypants** [RockinChaos/ItemJoin#501]
Hi,

I'm using itemjoin in a void skyblock world and i'm using voidteleport+

If i set keep-inventory to false in void teleport you naturally lose all of your inventory. Voidteleport teleports you back to your last known location before you die in the void and clears your inventory. 

I've tried all item flags and triggers available but still lose the items, is there a way to replace the items upon teleport?

**Comment by RockinChaos** [comment]
Hmmm I am not sure I understand the issue.
Can you provide a pastebin link of your items.yml and config.yml so I can get a better understanding?

**Comment by SirCraftypants** [comment]
> Hmmm I am not sure I understand the issue. Can you provide a pastebin link of your items.yml and config.yml so I can get a better understanding?

OK, basically i want to turn off keep inventory in my skyblock but if i do that i lose the itemjoin items. I would like my itemjoin items to be returned upon teleporting back to my island. 

So say 'teleport' as a trigger to give the items again.

**Comment by SirCraftypants** [comment]
Hi, any chance of adding teleport as a trigger please?

**Comment by RockinChaos** [comment]
I can look into this, I just got my computer back up and running after a hardware failure so give me a little bit to get everything set up.

Will update you here soonish.;

**Comment by RockinChaos** [comment]
Okay, so I have added the teleport trigger as requested.

This applies to both items and the active-commands in the config.yml.

Simply add `TELEPORT` to the list of triggers for the item.

Let me know if you encounter any issues!~

Link; https://ci.craftationgaming.com/job/ItemJoin/879/
**Remember to remove your old ItemJoin.jar file**

**Comment by SirCraftypants** [comment]
Awesome, thanks you

Testing now.

**Comment by SirCraftypants** [comment]
`  skyblock-menu-stone:
    id: STICK
    slot: 7
    count: 1
    model-data: 186
    name: '&1Skyblock Menu Stone'
    lore:
      - '&7Left click to open Skyblock Menu'
    interact-left:
      - 'player: is'
    itemflags: give-next, death-keep, self-drops, cancel-events, cancel-equip, item-store, death-drops, unbreakable
    triggers: join, world-switch, respawn, teleport   
    permission-node: 'itemjoin.default'    
    enabled-worlds: bskyblock_world`

When i teleport to the world, i end up with 2 of this item?

**Comment by SirCraftypants** [comment]
> Okay, so I have added the teleport trigger as requested.
> 
> This applies to both items and the active-commands in the config.yml.
> 
> Simply add `TELEPORT` to the list of triggers for the item.
> 
> Let me know if you encounter any issues!~
> 
> Link; https://ci.craftationgaming.com/job/ItemJoin/879/ **Remember to remove your old ItemJoin.jar file**

**Comment by SirCraftypants** [comment]
Sorry for late reply, works perfectly, much appreciated!
