### ISSUE TITLE
New Language

### ISSUE THREAD

**Issue by DeskTecc** [RockinChaos/ItemJoin#506]
## New Language Request: Brazilian Portuguese

Hello i'm Tecc and i want to contribute this plugin with the translation i've made for my native language.

[pt-lang.zip](https://github.com/RockinChaos/ItemJoin/files/9842675/pt-lang.zip)

**Thanks** 😄

**Comment by RockinChaos** [comment]
Awesome thanks! I will include this in the next snapshot commit!

**Comment by RockinChaos** [comment]
Language has officially been implemented, thank you for your contribution!

You will find this change in the latest snapshot.
Simply specify `Portuguese` in the Language section in the config.yml file.

Link; https://ci.craftationgaming.com/job/ItemJoin/858/
**Remember to remove your old ItemJoin.jar file if you install this snapshot.**
