### ISSUE TITLE
Add a permission change trigger

### ISSUE THREAD

**Issue by Josh65-2201** [RockinChaos/ItemJoin#507]
## Thanks for taking the time to open a feature request!

**Is your feature request related to a problem? Please describe.**
I run all my itemjoin items via permission so it all in one place and I know what links to what. But there's not permission change trigger so items aren't given correctly.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RockinChaos** [comment]
Oh hey.... sorry this was added in the official latest release, it's called the `permission-switch` trigger.
A few others requested this on Discord so I overlooked this open GitHub issue.

Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=543458
**Remember to remove your old ItemJoin.jar file**

Thanks for requesting this feature!
