### ISSUE TITLE
Preventing from Attaching to /Hat (EssentialsX)

### ISSUE THREAD

**Issue by TheWylot** [RockinChaos/ItemJoin#509]
## Thanks for taking the time to open a feature request!

**Is your feature request related to a problem? Please describe.**
Its be good to add a flag for preventing an item to be attached with /hat on players hat (EssentialsX)

**Describe the solution you'd like**
add a flag to block it

**Comment by iSeitan** [comment]
Add the same setup with the /ah from CMI too please :)
Same issue

**Comment by RockinChaos** [comment]
This feature has been added in the latest snapshot and has been tested as fully functional.
Simply specify the itemflag `not-hat` and the `/hat` command will be blocked for items with that specified itemflag.
In addition, a message will be sent indicating the action was prevented if the message is defined in the lang.yml file via `commands.item.badCommand` (will need to be manually added for older lang.yml files).

Link; https://ci.craftationgaming.com/job/ItemJoin/872/
**Remember to remove your old ItemJoin.jar file**

Let me know!~
