### ISSUE TITLE
Crash on join

### ISSUE THREAD

**Issue by DynamicThijs** [RockinChaos/ItemJoin#51]
Sometimes if I join, the server crashes when giving the items.
Crash dump: http://pastebin.com/raw/6mYUmGHE
(there were no errors before the crash)

**Comment by RockinChaos** [comment]
Currently looking into this. I will get back to you when I have more information. Thank you for bringing this to our attention.

**Comment by RockinChaos** [comment]
This issue has been resolved for v3.5 release. This will hopefully be out within the next week.

**Comment by DynamicThijs** [comment]
Thank you!

Sent from my iPhone

**Comment by RockinChaos** [comment]
This has been fixed as of ItemJoin v3.5 and it has been released!

You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107083
