### ISSUE TITLE
WorldGuard incompatibility with ItemJoin

### ISSUE THREAD

**Issue by LOCNetwork** [RockinChaos/ItemJoin#510]
## Thanks for taking the time to open a bug report!

**Describe the bug**
On 1.19.2, if you install WorldGuard and ItemJoin and you create a region, when you join, ItemJoin's items given to you on joining will disappear from your inventory if you move in that region.

**To Reproduce**
1. Create a 1.19.2 Server
2. Install WorldGuard
3. Install ItemJoin
4. Create a WorldGuard region (No specific flags needed, just a default one)
5. Create an ItemJoin item with the JOIN flag, so you get that item on join.
6. Disconnect in the WorldGuard region.
7. Reconnect
8. Move your camera and then the item disappears.

**Expected behavior**
The Item does not disappear.

**Screenshots**

**Pastebin**
No errors in the console.

**Please complete the following information:**
 - Resource Version and Build Number: v5.2.5-RELEASE-b850
 - Server Version: 1.19.2 PAPER

**Additional context**

**Comment by RockinChaos** [comment]
Confirmed, working on a fix for v6.0.0.

**Comment by RockinChaos** [comment]
Apologies this took so long, this seems to now be fixed in the latest snapshot.
I was able to replicate the issue and produce a fix for this.

v6.0.0-Snapshot is now available.
Link; https://ci.craftationgaming.com/job/ItemJoin/881/
**Remember to remove your old ItemJHoin.jar file**
