### ISSUE TITLE
item not open ChestCommand menu only on inventory event click

### ISSUE THREAD

**Issue by Klover91** [RockinChaos/ItemJoin#511]
i created an item with custom model data texture  (totem of undying) and i made it to run the CC command as OP `cc open menu`
  (menu = the name of the menu i created in chest command) with `inventory_left_click`.
it gives me this error:
  
`[01:42:03 WARN]: [ItemJoin] Plugin ItemJoin v5.2.5-RELEASE-b850 generated an exception while executing task 36697
java.lang.ArrayIndexOutOfBoundsException: null`

everything is ok with `right_click` event while held, but somehow every other inventory click event won't work.

pls help! <3

**Comment by Klover91** [comment]
solved, i was on creative while trying, but in survival everything works

**Comment by RockinChaos** [comment]
Ah, I see, still a bug though. Thank you for letting me know!~ I should be able to fix that error to not appear in the next snapshot.
