### ISSUE TITLE
Color-Codes of Placeholders aren't considered

### ISSUE THREAD

**Issue by MinecraftCoder3** [RockinChaos/ItemJoin#512]
## Thanks for taking the time to open a bug report!

**Describe the bug**
Color-Codes of Placeholders aren't considered

**To Reproduce**
1. Pick a placeholder with a color-code e.g. a prefix
2. Apply this placeholder to an Item
3. Reload ItemJoin
4. The Color Codes are displayed as text

**Expected behavior**
The color codes are considered and used

**Screenshots**
None

**Pastebin**
None

**Please complete the following information:**
 - Newest at the time of writing
 - Paper-1.19.2

**Additional context**
None

**Comment by RockinChaos** [comment]
Hmmm... yeah never thought about this, never really considered color codes being in placeholders. Placeholders are parsed after running through color code checks.
Looks like I just got to bump it up to parse prior to running through the colors.

Will be an easy fix, I will update you soon.

**Comment by RockinChaos** [comment]
Confirmed and resolved for the v6.0.0 release.
Currently, v6.0.0 is highly unstable so I won't send you a snapshot link but if you are interested in testing it on a TESTING ONLY server you can easily find it on our integration server (Jenkins).

Thank you for your bug report!~
