### ISSUE TITLE
Does this work on respawn

### ISSUE THREAD

**Issue by rbcoder117** [RockinChaos/ItemJoin#514]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
can you get this to that when you die it gives something also like a random kit.

**Pastebin**
Haven’t installed
**Please complete the following information:**
 -Haven’t installed
 - Spigot 1.19

**Additional context**

**Comment by RockinChaos** [comment]
Apologies for the late reply,

Yes, ItemJoin is very capable of this. There are many triggers including respawn, and it is quite easy to select from a list of randomized items.

The wiki best details this; https://github.com/RockinChaos/ItemJoin/wiki

**Comment by rbcoder117** [comment]
Thanks for the reply. No Worries its all good.
