### ISSUE TITLE
SkinRestorer support

### ISSUE THREAD

**Issue by qarbon1** [RockinChaos/ItemJoin#515]
Hello I keep getting this error

[ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner qarbon_.

**Comment by RockinChaos** [comment]
They changed their API in the current update, already resolved in the latest snapshot however its still unstable as it's a major recode.

I will ping you with a link once it's stable. If you are interested you can test it by downloading it from our Jenkins server however please do not use it on a production server.

**Comment by RockinChaos** [comment]
Tested and should now be fixed in the latest snapshot;
Link: https://ci.craftationgaming.com/view/Chaos/job/ItemJoin/870/
**Remember to remove your old ItemJoin.jar file**

Let me know!~
