### ISSUE TITLE
Add a cost item.

### ISSUE THREAD

**Issue by xyblues** [RockinChaos/ItemJoin#52]
I want to add a cost item.
Player right click item, will run the command and remove the item.

**Comment by RockinChaos** [comment]
Sounds like a great idea and it will be easy to add. Ill try to get it out for the next update.

**Comment by xyblues** [comment]
Hope to update as soon as possible.

**Comment by RockinChaos** [comment]
Sorry, this will be coming out very soon. I have ran into a few problems with life lol. The house next door burnt down and we lost internet for a while there, as well as i'm prepping for college so I haven't had that much free time but I am pushing for a release in the next couple of days.

**Comment by xyblues** [comment]
Well, thank you. Don't need to say sorry...

**Comment by RockinChaos** [comment]
This has been officially implemented for v3.5. I just have a few things to finish up for the release.

**Comment by RockinChaos** [comment]
This has been added as of ItemJoin v3.5 and it has been released!

You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107083
