### ISSUE TITLE
Autocrafting(Shift-clicking) the resulting item

### ISSUE THREAD

**Issue by LukeIamareYourFather** [RockinChaos/ItemJoin#522]
### Server Version

Paper 1.19.3

### Resource Version

ItemJoin v5.2.5-RELEASE-b850

### Dump Information

Unknown command error

### Describe The Problem

The in built recipe creator doesn't work for me, so I use a different plugin which works well with yours, but when you try to shift click the result item in a crafting table to get the maximum number of them, you only get one instance of the item and the server crashes. When I craft items from other plugins with ItemJoin items it works but when I craft an ItemJoin item from ItemJoin items it crashes the server :'(

### Additional Context

I would be grateful for receiving insight for what could be the cause, even more so for the solution. If there is any additional info to provide, I will.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Yikes, that isn't supposed to happen.

The dump command isn't implemented yet as it's in the v6.0.0-snapshot, instead would you be able to provide your items.yml so I can test this item in question?

**Comment by LukeIamareYourFather** [comment]
If it will help you to find the problem, sure. The odd thing is that it isn't just one item, even if I make a new item without anything special on it i.e.: I only define the necessary with basic entries (id: STICK, slot: 21, name: Wand, lore: Does this spell, itemflags :GIVE-NEXT , triggers: DISABLED) with the appropriate YAML coding.

Is there anything that useful that the console provides? I tried to look at tit but not much can be deducted from it.

Basically if ItemJoin items are used to craft an item from different plugin or vanilla, you can create the maximum amount by shift click.
 But if you try to create a custom ItemJoin item this way, only one instance of the item is created, the items don't get used up to create even the one item (basically free instance) {At this point the server crashes I believe} and you are unable to interact with right click with anything after closing the craft table. After a while the server closes completely.

**Comment by RockinChaos** [comment]
I apologize for the extremely delayed response.
I have done quite a few bug fixes in regard to this and I believe the latest snapshot will now resolve your issue.
Please use the latest snapshot and let me know if this resolves your issue.

Link; https://ci.craftationgaming.com/job/ItemJoin/887/
**Remember to remove your old ItemJoin.jar file**

If you continue to encounter issues, you will now be able to provide me with the `/itemjoin dump` output.

**Comment by RockinChaos** [comment]
The v6.0.0 release is now available.

Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=494934
**Remember to remove your old ItemJoin.jar file**

If you continue to experience issues feel free to open a new issue and include the `/itemjoin dump` information.
