### ISSUE TITLE
Compass always enchanted

### ISSUE THREAD

**Issue by porudev** [RockinChaos/ItemJoin#524]
### Server Version

PaperSpigot 1.8.8

### Resource Version

ItemJoin v6.0.0-SNAPSHOT-b877

### Dump Information

https://pastebin.com/gM5UYb2z

### Describe The Bug

The compass is always set to be enchanted by default

### Expected Behavior

The compass should not be enchanted

### Steps To Reproduce

Just make a compass

### Additional Info

![image](https://user-images.githubusercontent.com/81072838/221531937-a30848fb-2a6f-4b1c-8df8-c0b561edd425.png)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
I apologize for the late reply, I am currently in college and it just happened to be my finals week.

I have been debugging this issue extensively and cannot replicate it. I suspect there is a conflict somewhere with another plugin, although I cannot be certain which one.
It may be beneficial for you to go through and use a plugin like PlugMan to disable plugins 1-by-1 until you find the culprit, clearing and re-getting your items each time. It is very likely a config option inside one of the plugins.

**Comment by porudev** [comment]
> 

This bug only occur when i switch from the version that have skin restorer error to the latest build. Sorry for the late reply, i was kind of super busy

**Comment by RockinChaos** [comment]
I have still not been able to replicate this issue and suspect there is a conflict with something else. Currently, the v6.0.0 release is now available so I recommend trying that first to see if it resolves your issue.

Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=494934
**Remember to remove your old ItemJoin.jar file**

If you continue to experience issues feel free to open a new issue and include the `/itemjoin dump` information.

**Comment by RockinChaos** [comment]
Okay so it seems pushing this issue to release has finally brought some decent reports about the issue in.
I was able to replicate the issue and resolve it now so it is 100% confirmed in the v6.0.1 snapshots.

Link; https://ci.craftationgaming.com/job/ItemJoin/891/
**Remember to remove your old Itemjoin.jar file**

Let me know!~
