### ISSUE TITLE
give items only in first join

### ISSUE THREAD

**Issue by MohammadAlawieh** [RockinChaos/ItemJoin#525]
### Server Version

PaperSpigot 1.19.2

### Resource Version

ItemJoin v5.2.5

### Dump Information

it says unknown command

### Describe The Problem

I just wanna know how to give players items only when they join the 1st time, not every time

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Hi, apologies for the late reply.

The `first-join` trigger will do this for you.
You can see additional triggers here; https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#defining-an-items-triggers
