### ISSUE TITLE
Doesnt give items

### ISSUE THREAD

**Issue by ARDragssss** [RockinChaos/ItemJoin#526]
I made 3 items and even though I enabled Join, Gamemode Switch, Respawn and World Switch it doesn’t always give me the items. Sometimes it gives me one item and other times two. Sometimes all and sometimes none. Heres my configs:
https://paste.gg/p/anonymous/0d7ced1741bc4b5192c1f636fc845394

Paper 1.19.3

**Comment by ARDragssss** [comment]
issue was with another plugin. fixed

**Comment by RobinRMC** [comment]
@ARDragssss, which plugin?
