### ISSUE TITLE
Not Log The Command Executed To Console

### ISSUE THREAD

**Issue by Its-Ario** [RockinChaos/ItemJoin#528]
### Server Version

Spigot 1.8.8

### Resource Version

ItemJoin 5.2.5-RELEASE-b850

### Dump Information

>itemjoin dump [15:02:28 INFO]: [ItemJoin] Unknown command, See /ItemJoin Help for a list of commands.

### Describe The Problem

Hi, is there a way to not log the command executed with the item to console? I am using CommandPanels to open a GUI on item click

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Yes indeed there is! In the config.yml under the general section you should see a boolean called log-commands. Changing this will disable the command from being logged in the console window.
