### ISSUE TITLE
Enabled World's Bug

### ISSUE THREAD

**Issue by SirCraftypants** [RockinChaos/ItemJoin#529]
### Server Version

PaperSpigot 1.19.4

### Resource Version

ItemJoin-6.0.0-SNAPSHOT-b879

### Dump Information

https://pastebin.com/rhUHHsK1

### Describe The Bug

When i teleport from `bskyblock_world` to world `lobby`, it does not remove the item with the below enabled world settings.

`    enabled-worlds: bskyblock_world, bskyblock_world_nether, bskyblock_world_the_end`

When teleporting to `bskyblock_world` from world `lobby`, it does not remove the item with the below enabled world settings.

`    enabled-worlds: Lobby, world`

?

### Expected Behavior

Both items should be removed from inventory when not an enabled world.

### Steps To Reproduce

Use the same idea and teleport from and too each world.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by SirCraftypants** [comment]
I thought enabled worlds would remove items upon leaving as well as give the worlds items upon joining?

**Comment by RockinChaos** [comment]
As per the wiki items do not get automagically removed, you must tell them you want that functionality.
The `auto-remove` itemflag will accomplish this.

Wiki snippet;
auto-remove - Upon performing one of the defined triggers for the item, if the custom item is found in the player's inventory and is in a world which is not defined under the enabled-worlds it will be automatically removed. This best works with the world-switch trigger that way when players switch to a world that is not enabled for the item, it will simply be removed.

Also, you accidentally checked too many boxes in the checklist.

**Comment by SirCraftypants** [comment]
> As per the wiki items do not get automagically removed, you must tell them you want that functionality. The `auto-remove` itemflag will accomplish this.
> 
> Wiki snippet; auto-remove - Upon performing one of the defined triggers for the item, if the custom item is found in the player's inventory and is in a world which is not defined under the enabled-worlds it will be automatically removed. This best works with the world-switch trigger that way when players switch to a world that is not enabled for the item, it will simply be removed.
> 
> Also, you accidentally checked too many boxes in the checklist.

Thank you, i did check the wiki, i just misunderstood how enabled worlds works as didn't realize a flag did what i thought enabled worlds did.
