### ISSUE TITLE
Group Manager Dependency

### ISSUE THREAD

**Issue by PrincessPurple** [RockinChaos/ItemJoin#53]
Would maybe nice for a optional dependency for group manager and essentials chat so that you can show a player rank with the %player% tag as well as just their name.

**Comment by RockinChaos** [comment]
This is very possible and I will look into it. Sorry, the house next door caught on fire and we lost internet for a while there.

**Comment by RockinChaos** [comment]
I have began implementing group manager type plugins. the "prefixes/suffixs". I have a question though, what are you wanting this feature for? Is it the en-lang? Or the custom messages from running a command? Or something else entirely?

I have noticed that PlaceholderAPI does support this, and if you wanted to you could use the placeholderapi optional dependency for ItemJoin to make this happen. You would just have to install placeholderapi on your server and set placeholderapi to true in the itemjoins config.yml

The placeholders are as such:
%vault_rank%
%vault_prefix%
%vault_rankprefix%
%vault_rankprefix_#%
%vault_suffix%
%vault_ranksuffix%
%vault_ranksuffix_#%
%vault_prefix_color%


If you are wanting me to add support for these on my plugin without it requiring placeholderapi I can look into doing so. 

Please give me feedback so I can proceed forwards, thank you :)
