### ISSUE TITLE
Created new item and not working!

### ISSUE THREAD

**Issue by Remppaaja** [RockinChaos/ItemJoin#531]
### Server Version

Spigot 1.19.2

### Resource Version

ItemJoin v5.2.5-Release-b850 by RockinChaos

### Dump Information

Not working

### Describe The Problem

I created a new map with custom photo and it doesnt gonna work out because it not generate to my inventory when im joining the server

and when im looking the menu its not showing on right place
that photo where im showing the map its some kind template inventory or something and on next photo is that right one where i want to have so please help me eith my proplem

![2023-04-14_10 41 41 copy](https://user-images.githubusercontent.com/130740830/231978511-b2c0d7e3-27a2-4611-80f8-95ceced37765.png)
![Itemjoin](https://user-images.githubusercontent.com/130740830/231978518-160feceb-5db1-4eed-ae6e-d14a675fcdd8.png)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
I apologize for the delayed response.
I have done quite a few bug fixes in regard to this and I believe the latest snapshot will now resolve your issue.
Please use the latest snapshot and let me know if this resolves your issue.

Link; https://ci.craftationgaming.com/job/ItemJoin/887/
**Remember to remove your old ItemJoin.jar file**

**If you continue to encounter issues**, you will now be able to provide me with the `/itemjoin dump` output.
In addition please provided the image file you are trying to set.

**Comment by RockinChaos** [comment]
The v6.0.0 release is now available.

Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=494934
**Remember to remove your old ItemJoin.jar file**

If you continue to experience issues feel free to open a new issue and include the `/itemjoin dump` information.
