### ISSUE TITLE
6.0.1 Errors on initial installation

### ISSUE THREAD

**Issue by x1p** [RockinChaos/ItemJoin#532]
### Server Version

Purpur 1.19.4

### Resource Version

ItemJoin 6.0.1

### Dump Information

https://pastebin.com/YkBtnQyL

### Describe The Bug

On a default test server (with no prior installation of ItemJoin) this appears on startup:
https://pastebin.com/raw/0uq4n6r4

### Expected Behavior

No error (or at most a message saying that the database does not exist and a new one shall be created)

### Steps To Reproduce

1. Delete existing ItemJoin directory
2. Start server
3. See error

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Confirmed, I have already done some fixes in the snapshot but a little more work is required.
Will be fixed for v6.0.2

**Comment by RockinChaos** [comment]
Confirmed as fixed in the snapshots and will be present in the release.

**Comment by RockinChaos** [comment]
The official release is now available.
Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=509886
**Remember to remove your old ItemJoin.jar file**
