### ISSUE TITLE
HELP VERSION

### ISSUE THREAD

**Issue by ImSmoch** [RockinChaos/ItemJoin#533]
Does anyone know what the correct plugin version is for Spigot 1.8.8? The latest one seems to be buggy.

**Comment by RockinChaos** [comment]
All versions of ItemJoin support 1.8.8 so if there is a bug a proper bug report would be recommended so I can solve the issue. As well as including your `/itemjoin dump` information.

**Comment by ImSmoch** [comment]
https://pastebin.com/CxhT0Hbw
What happens is that of all those items that appear, only two load for me, and when I use /itemjoin menu, the menu does not work. I click on them and they do not perform their functions.

**Comment by ImSmoch** [comment]
https://pastebin.com/CRNp5wvQ

When I use /itemjoin reload, this comes up.

**Comment by ImSmoch** [comment]
![2023-05-07_11 58 39](https://user-images.githubusercontent.com/81275112/236693116-6bafa6e3-182e-4f9a-95e9-5842e31e98ab.png)

**Comment by RockinChaos** [comment]
Going to close this since it seems this has been now answered in your Discord Ticket.
If you are unaware please see ticket-1345 on our Discord Server.
