### ISSUE TITLE
is there already support for 1.20.1?

### ISSUE THREAD

**Issue by Youri5** [RockinChaos/ItemJoin#538]
### Server Version

paper 1.20.1

### Resource Version

ItemJoin-v6.0.1-RELEASE

### Dump Information

none

### Describe The Problem

is there already suport for 1.20.1?

### Additional Context

none

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by Youri5** [comment]
sorry, i already got it working!
i have no further quetions

**Comment by RockinChaos** [comment]
No problem, but do note the latest release does not have official v1.20 / v1.20.1 support.
However, I am actively working on this so a semi-solid snapshot is already available and you can track it on our integration server;
https://ci.craftationgaming.com/job/ItemJoin/
