### ISSUE TITLE
Print debug messages as info, not warning

### ISSUE THREAD

**Issue by MarvinKlar** [RockinChaos/ItemJoin#542]
### Describe The Feature

The debug messages are warnings. There is not reason for it.

### Expected Solution

Make the debug messages info messages, not warnings.

### Describe Alternatives Considered

We need the debugging since we had an issue with the plugin and want to find out, where that issue is coming from. So there is not alternative.

### Additional Context

Debug messages like:

`[09:30:03 WARN]: [ItemJoin_DEBUG] {ItemMap} Player has been given the item menue-item in the world [world].`

### Checklist

- [X] I have read the wiki to make sure my request has not already been implemented.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my feature request is unique and another request does not exist.

**Comment by RockinChaos** [comment]
Done and implemented in the latest snapshot.
https://ci.craftationgaming.com/job/ItemJoin/914/
