### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Lonely132** [RockinChaos/ItemJoin#544]
### Server Version

Spigot 1.20.1

### Resource Version

ItemJoin v6.0.1

### Dump Information

https://pastebin.com/9YmtvL3t

### Describe The Bug

https://pastebin.com/rmg0z6yy Im getting this error in console, other than that everything is working correctly.

### Expected Behavior

Im just getting an error..

### Steps To Reproduce

?

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
The latest snapshot already fixes this issue.
https://ci.craftationgaming.com/job/ItemJoin/897/artifact/target/ItemJoin-6.0.2-SNAPSHOT-b897.jar

v6.0.2

**Comment by RockinChaos** [comment]
The official release is now available.
Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=509886
**Remember to remove your old ItemJoin.jar file**
