### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by CJYKK** [RockinChaos/ItemJoin#545]
### Describe The Feature

Hi, could you consider adding Velocity related support to ItemCommands?
For example, making "server" support Velocity and adding a "velocity" option to execute Velocity commands.

### Expected Solution

Use Velocity in items.yml

### Describe Alternatives Considered

Now I'm using [CommandSync](https://www.spigotmc.org/resources/commandsync.52093) plugin with "console: sync console bungee send %player% survival". It's working, but too slow.

### Checklist

- [X] I have read the wiki to make sure my request has not already been implemented.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my feature request is unique and another request does not exist.

**Comment by RockinChaos** [comment]
I apologize for my stupidity. I just got around to looking to implement this feature but I am pretty sure this feature already exists.
I already designed a resource called CloudSync that hooks into bungee commands and I ended up adding Velocity support a while back.

Simply download; https://www.spigotmc.org/resources/cloudsync.93382/
Drop it into your velocity instance.
There is nothing for you to configure with CloudSync.

Then in your items.yml use `bungee:` as the initiator for the command.


CloudSync is similar to CommandSync in premise but CloudSync is waaaay simpler as it uses the backend channels to automatically pass messages back and forth between ItemJoin and CloudSync and visa versa.

**Comment by CJYKK** [comment]
It's working, thanks for your patience in replying!

**Comment by CJYKK** [comment]
> I apologize for my stupidity. I just got around to looking to implement this feature but I am pretty sure this feature already exists.
> I already designed a resource called CloudSync that hooks into bungee commands and I ended up adding Velocity support a while back.
> 
> Simply download; https://www.spigotmc.org/resources/cloudsync.93382/
> Drop it into your velocity instance.
> There is nothing for you to configure with CloudSync.
> 
> Then in your items.yml use `bungee:` as the initiator for the command.
> The following command should then be written as if you were typing it in the velocity console.
> 
> For instance a velocity friends plugin command would be added to ItemJoin's item commands looking like `bungee: friend add %player% %player_target%` as an example.
> 
> 
> CloudSync is similar to CommandSync in premise but CloudSync is waaaay simpler as it uses the backend channels to automatically pass messages back and forth between ItemJoin and CloudSync and visa versa. This results in minimal latency which should be absolutely unnoticeable since its pretty instantaneous.
> 
> If you encounter any issues with Velocity support please let me know.

It's working, thanks for your patience in replying!
