### ISSUE TITLE
Material Identifier

### ISSUE THREAD

**Issue by ItzTevy** [RockinChaos/ItemJoin#548]
### Server Version

1.19.4

### Resource Version

ItemJoin v6.0.2

### Dump Information

https://cdn.discordapp.com/attachments/1145413532389736628/1145741407001268224/image.png

### Describe The Bug

I tried with compass name and with his id but it doesn't work and i don't get it

### Expected Behavior

{ItemDesigner} The itembusola does not have a Material ID definied

### Steps To Reproduce

1. Go to item.yml and try to make the item.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Hi, so at a minimum I need you to execute the command `/itemjoin dump` and provide the URL.
Currently, this bug report has basically zero information for me to go off of.
