### ISSUE TITLE
The bug

### ISSUE THREAD

**Issue by parf1n** [RockinChaos/ItemJoin#550]
### Server Version

Puperfish 1.20.1 Build #23

### Resource Version

ItemJoin v6.0.2

### Dump Information

it.doesnt.work

### Describe The Bug

The plugin gives me one item from items.yml (doesn't give the other two) and when I write /ij it gives the following error:
https://paste.helpch.at/celonagavo.md

### Expected Behavior

want this to work..

### Steps To Reproduce

1. Join to the server
2. Write /itemjoin

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Known issue in the release build, snapshots already contain a fix for this though are still experimental.
https://ci.craftationgaming.com/job/ItemJoin/
