### ISSUE TITLE
build 903 cannot be loaded; missing plugin.yml

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#551]
### Server Version

Paper 1.20.2

### Resource Version

ItemJoin-6.0.3-EXPERIMENTAL-b903

### Dump Information

N/A

### Describe The Bug

Plugin cannot be loaded, since it is missing `plugin.yml` (or `paper-plugin.yml`).

### Expected Behavior

Clean load

### Steps To Reproduce

- Install ItemJoin-6.0.3-EXPERIMENTAL-b903
- Start server
- Read log

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
It saddens me that this is now brought to my attention after being downloaded so many times this week.
Thank you for taking the time to let me know!~

Looks like a Maven compile problem, it now seems to be fixed (and properly included) in the latest snapshot.

https://ci.craftationgaming.com/job/ItemJoin/905/
**Remember to remove your old ItemJoin.jar**

**Comment by RockinChaos** [comment]
Gonna link this and #552 together here as I recall something similar that I believe I fixed in the experimental builds.

**Comment by SlimeDog** [comment]
> It saddens me that this is now brought to my attention after being downloaded so many times this week. Thank you for taking the time to let me know!~

Amazing!
