### ISSUE TITLE
New Version for mc 1.20.2

### ISSUE THREAD

**Issue by Nicalion** [RockinChaos/ItemJoin#553]
### Server Version

Paper 1.20.2

### Resource Version

ItemJoin v6.0.2

### Dump Information

https://pastebin.com/5ygFcvJg

### Describe The Problem

https://i.imgur.com/o8bFYsT.png

this will happen in the new version and i didnt change anything
when u clear the item.yml it works when you use the templet it didnt work
when you want to add item didnt work

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Already known issue resolved in the snapshots (confirmed fix on b906)
See previous issue #552
