### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by AlmostPanda** [RockinChaos/ItemJoin#555]
### Server Version

Paper 1.20.2

### Resource Version

ItemJoin-6.0.3-EXPERIMENTAL-b907.jar

### Dump Information

https://pastebin.com/b2jSfr1P

### Describe The Problem

On version ItemJoin-6.0.2-SNAPSHOT-b897.jar when I changed gamemode to creative I could remove or move with items in hotbar, now I updated to latest version and its not working, when I move or try to remove items it keeps them on there place.
I can't even copy block with middle click on mouse, the block disappear.
Can u help me with it please? 

### Checklist

- [X] I am running latest version of this resource.
- [ ] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [ ] I have checked that my help request is unique and another request does not exist.
- [ ] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Confirmed, a fix has now been implemented.
Thanks for the report!

Link; https://ci.craftationgaming.com/job/ItemJoin/912/
**Remember to remove your old ItemJoin.jar file**
- If you get an error when loading the webpage give it a refresh a few times.

**Comment by AlmostPanda** [comment]
It works awesome, thank you very much
