### ISSUE TITLE
SPAM CONSOLE ERROR, ERROR WITH VIA VERSION?

### ISSUE THREAD

**Issue by JimmyEstrada** [RockinChaos/ItemJoin#561]
### Server Version

Spigot 1.88.2

### Resource Version

ItemJoin v6.0.2

### Dump Information

//pastebin.com/kjEUW0kP

### Describe The Bug

Hello, sorry, I have the latest version of skinrestorer and the latest version of item join and all night I got this error in the console second after second, can you help me solve it?

`08.11 12:04:22 [Server] Server thread/INFO Jimmy_FPE issued server command: /itemjoin dump
08.11 12:04:27 [Multicraft] Skipped 1 lines due to rate limit (30/s)
08.11 12:04:27 [Server] Server thread/ERROR [ItemJoin_ERROR] {ChatExecutor} Failed to execute the DUMP command.
08.11 12:04:27 [Server] Server thread/WARN java.io.IOException: Server returned HTTP response code: 413 for URL: https://pastebin.com/api/api_post.php
08.11 12:04:27 [Server] Server thread/WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
08.11 12:04:27 [Server] Server thread/WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
08.11 12:04:27 [Server] Server thread/WARN at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
08.11 12:04:27 [Server] Server thread/WARN at me.RockinChaos.core.utils.api.PasteAPI.getPaste(PasteAPI.java:144)
08.11 12:04:27 [Server] Server thread/WARN at me.RockinChaos.itemjoin.ChatExecutor.dump(ChatExecutor.java:296)
08.11 12:04:27 [Server] Server thread/WARN at me.RockinChaos.itemjoin.ChatExecutor.onCommand(ChatExecutor.java:169)
08.11 12:04:27 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
08.11 12:04:27 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
08.11 12:04:27 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:826)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1796)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1777)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.bo(SourceFile:116)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1145)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051)
08.11 12:04:27 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
08.11 12:04:27 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)
08.11 12:04:28 [Multicraft] Skipped 19 lines due to rate limit (30/s)
08.11 12:04:28 [Server] Craft Scheduler Thread - 1024/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:28 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:28 [Server] Craft Scheduler Thread - 992/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:28 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:28 [Server] Craft Scheduler Thread - 992/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:28 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:29 [Server] Craft Scheduler Thread - 1022/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:29 [Server] Craft Scheduler Thread - 1009/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:29 [Server] Craft Scheduler Thread - 992/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:29 [Server] Craft Scheduler Thread - 1025/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Craft Scheduler Thread - 1009/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Craft Scheduler Thread - 1026/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Craft Scheduler Thread - 1024/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Craft Scheduler Thread - 1021/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Craft Scheduler Thread - 1021/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:30 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:31 [Server] Craft Scheduler Thread - 1009/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:31 [Server] Craft Scheduler Thread - 1026/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:31 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:31 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:31 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:32 [Server] Craft Scheduler Thread - 1009/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:32 [Server] Craft Scheduler Thread - 1009/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:32 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:32 [Server] Craft Scheduler Thread - 1026/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:33 [Server] Craft Scheduler Thread - 1026/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:33 [Server] Craft Scheduler Thread - 1025/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:34 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:34 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:36 [Server] Craft Scheduler Thread - 1025/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:36 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:37 [Server] Craft Scheduler Thread - 1026/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:37 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:38 [Server] Craft Scheduler Thread - 992/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:38 [Server] Craft Scheduler Thread - 1026/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:39 [Server] Craft Scheduler Thread - 1024/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:39 [Server] Craft Scheduler Thread - 992/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:39 [Server] Craft Scheduler Thread - 1024/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:39 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:40 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:40 [Server] Craft Scheduler Thread - 1012/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:40 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:40 [Server] Craft Scheduler Thread - 1012/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:40 [Server] Craft Scheduler Thread - 1009/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:41 [Server] Craft Scheduler Thread - 1025/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:41 [Server] Craft Scheduler Thread - 1025/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:41 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:41 [Server] Craft Scheduler Thread - 1021/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:42 [Server] Craft Scheduler Thread - 992/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:42 [Server] Craft Scheduler Thread - 1025/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:43 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:43 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:45 [Server] Server thread/INFO CONSOLE issued server command: /list 
08.11 12:04:45 [Server] Server thread/INFO Hay 1 jugadores de un máximo de 50 jugadores en linea.
08.11 12:04:45 [Server] Server thread/INFO Admins: OWNER Jimmy_FPE
08.11 12:04:45 [Server] Craft Scheduler Thread - 1022/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:45 [Server] Server thread/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:46 [Server] Craft Scheduler Thread - 1009/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:46 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner MCList.
08.11 12:04:47 [Server] Craft Scheduler Thread - 992/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.
08.11 12:04:47 [Server] Craft Scheduler Thread - 1023/ERROR [ItemJoin_ERROR] {DependAPI} [1] Unsupported SkinsRestorer version detected, unable to set the skull owner Jimmy_FPE.

`

### Expected Behavior

I do not understand this

### Steps To Reproduce

I only have this

items:
   profile:
     id: SKULL_ITEM:3
     #skull-texture: '%player_uuid%'
     skull-owner: '%player%'
     #skull-owner: '%player_uuid%'
     slot: 1
     name: '%triton_itemjoin.profile%' #&aMy profile &7(Right click)
     lore:
     - '&7Right click to open the options menu!'
     interact-right:
     - 'player:MyBingPixelBangCJIProfile'
     #commands-sound: CHICKEN_EGG_POP
     commands-sound: BLOCK_NOTE_PLING
     itemflags: death-drops, self-drops, animate, death-drops
     triggers: join, respawn, inventory-modify #, world-switch
     enabled-worlds: Lobby

And when I enter the server I get that error

### Additional Info

<img width="988" alt="image" src="https://github.com/RockinChaos/ItemJoin/assets/137147205/e113d1fe-24f0-4777-9913-2ab990286659">
<img width="629" alt="image" src="https://github.com/RockinChaos/ItemJoin/assets/137147205/f341f091-548a-4eaa-b77d-d14f693e32af">

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Update to the latest snapshot, you are running a version of ItemJoin that does not support the latest version of SkinsRestorer.

Link: https://labs.craftationgaming.com/RockinChaos/ItemJoin/latest
**Remember to remove your old ItemJoin.jar file**
