### ISSUE TITLE
item disappear on menu

### ISSUE THREAD

**Issue by MaiCaleni** [RockinChaos/ItemJoin#563]
### Server Version

paper 1.20.1

### Resource Version

itemjoin v 6.0.3

### Dump Information

https://pastebin.com/5eRa7j1A

### Describe The Bug

after create the custom item and change atributtes and flags, when i try to change something in the /itemjoin menu , those item dont appear but they work and the item.yml changes works fine.

They just dont appear in the principal menu like other items.

Also the option to set a custom model data from the menu dont work. only work if you put the model data on the items.yml

### Expected Behavior

i wanna see my items in the menu, somethings cant be changed on the yml file like the diposable number option etc etc

### Steps To Reproduce

1. Create a custom item with the menu.
2. save and change little thing in the items.yml
3. reload
4. dont appear in the menu 

### Additional Info

![image](https://github.com/RockinChaos/ItemJoin/assets/75397352/a9287640-4599-40a2-bbc1-d80c8c59439c)

![image](https://github.com/RockinChaos/ItemJoin/assets/75397352/23f98e30-b933-40be-b04f-29c05a082f1d)
custom items are in the circle on my inv
![image](https://github.com/RockinChaos/ItemJoin/assets/75397352/6e31e581-e404-4e8d-aa9b-f8e07ef0099c)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Resolved via Discord.
