### ISSUE TITLE
STOP AND START

### ISSUE THREAD

**Issue by SpuckyYT123** [RockinChaos/ItemJoin#565]
### Server Version

Spigot 1.8

### Resource Version

v6.0.3

### Dump Information

https://pastebin.com/V0AHe8ST

### Describe The Bug

My problem is that I have an item that if you click on it it does an action but what happens is that every time I restart or turn on the server or turn it off when the item is opened it becomes unusable and I have to reload the plugin to get it back to work and so on all the time, this process is very boring, please help me.

### Steps To Reproduce

i don't know.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
It sounds like a plugin conflict, seems like the items are being sterilized (a plugin is removing the custom data tags).
Could you provide me a screenshot of your `/plugins` output so I can check for conflicts?

**Comment by SpuckyYT123** [comment]
![image](https://github.com/RockinChaos/ItemJoin/assets/121553293/f0071b84-8559-419b-b5f1-2653de46a8fe)

**Comment by RockinChaos** [comment]
I apologize for the lengthy delay in a reply, I have done some extensive testing and this issue seemed very similar to another bug report. I believe this is now resolved in the latest snapshot and was entirely unrelated to a plugin conflict.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
