### ISSUE TITLE
Permission Node Bug

### ISSUE THREAD

**Issue by KhrysAK47** [RockinChaos/ItemJoin#566]
### Server Version

1.17.1

### Resource Version

6.0.3-RELEASE-b18

### Dump Information

https://pastebin.com/Dv4kdzkQ

### Describe The Bug

Players get join items with the permisison node denied.

### Expected Behavior

Players should not get join items with the permisison node denied.

### Steps To Reproduce

1. Assign a permission to an item and a trigger of join.
2. Deny that permission (LuckPerms)
3. Remove the item from inventory
4. Rejoin

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
You don't have permissions enabled in your config.yml.

Permissions.Obtain-Item & Permissions.Obtain-Item-OP

**Comment by KhrysAK47** [comment]
> You don't have permissions enabled in your config.yml.
> 
> Permissions.Obtain-Item & Permissions.Obtain-Item-OP

Just tested with those settings changed, items still appear after joining.

**Comment by RockinChaos** [comment]
> > You don't have permissions enabled in your config.yml.
> > Permissions.Obtain-Item & Permissions.Obtain-Item-OP
> 
> Just tested with those settings changed, items still appear after joining.

Likely a configuration issue somewhere with your permissions.

As long as you set those two to `true`, I tested using your exact configs and it functions properly.

You can verify your permissions via `/itemjoin permissions 2` they should be RED when disabled.
Furthermore be sure you cleared the previous items from your inventory as simply changing permissions doesn't remove them automagically.

**Comment by KhrysAK47** [comment]
> > > You don't have permissions enabled in your config.yml.
> > > Permissions.Obtain-Item & Permissions.Obtain-Item-OP
> > 
> > 
> > Just tested with those settings changed, items still appear after joining.
> 
> Likely a configuration issue somewhere with your permissions.
> 
> As long as you set those two to `true`, I tested using your exact configs and it functions properly.
> 
> You can verify your permissions via `/itemjoin permissions 2` they should be RED when disabled. Furthermore be sure you cleared the previous items from your inventory as simply changing permissions doesn't remove them automagically.
> 
> * Additionally if you are using `/itemjoin get` command(s) to test, if you want permissions to apply to those you will need to enable the `Commands-Get` permission in your config file.

Players have the permission in the default group to get the item, I have a setting that negates the permission, however, even after the /itemjoin permissions 2 it still shows as green, tried both with and without op, * and owner rank.

**Comment by KhrysAK47** [comment]
Fixed.
