### ISSUE TITLE
NBTData Error

### ISSUE THREAD

**Issue by KhrysAK47** [RockinChaos/ItemJoin#567]
### Server Version

Paper 1.17.1

### Resource Version

6.0.3-RELEASE-b18

### Dump Information

Failed to execute the DUMP command.

### Describe The Bug

https://gyazo.com/6978bd8dc7f10d3d9a492fc91f144ae5

### Expected Behavior

Shouldn't appear at all?

### Steps To Reproduce

Not sure, it randomly appears in chat.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
The latest release is now available and contains this fix.
Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=524873
**Remember to remove your old ItemJoin.jar file**
