### ISSUE TITLE
Unable to bind items on the equipment slot

### ISSUE THREAD

**Issue by xingfujiuhao** [RockinChaos/ItemJoin#570]
### Server Version

1.20.1

### Resource Version

ItemJoin v6.0.3

### Dump Information

https://pastebin.com/qZhpQHGU

### Describe The Problem

I created four projects for the equipment slot: helmet, breastplate, pants, and shoes. Their materials are paper. The file data is 10235. And added a ban on movement to them. But I hold the helmet type equipment in my hand and right-click it. He will replace it. The project I set up. My hand will turn into the helmet paper I set for the project.
I want to ask if there is a way to keep them still. And it can also be equipped with armor. It will be displayed when the armor is removed. Information about the itemJoin plugin. On the contrary, equipping armor will not display. Information about the itemJoin plugin.
The significance of adding four items to the equipment slot is that I have bound an RPG more items column backpack. I want to bind the project with itemJoin. Open the GUI interface of the RPG item bar for other plugins. You can bind and open other RPG equipment slots. But there are also slots based on the original version inside. Therefore, it cannot be perfectly achieved. So I came here to seek help. I want to know if there is a way to achieve this effect.
If you haven't understood. You can directly say that I will explain carefully word by word below. I really want to sponsor you. I think you should have noticed too. My language is not fluent. I am not from the same region as you. I really want to know how to sponsor you. I want to give you more encouragement!

### Additional Context

![12](https://github.com/RockinChaos/ItemJoin/assets/140907248/838bd307-e667-4f8d-95e5-af407bc6d380)
![QQ图片20231221032512](https://github.com/RockinChaos/ItemJoin/assets/140907248/990fdd2c-669f-474f-9ab3-6caf4e1e5f0b)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Apologies for the late response, I was away for the holiday.



> If you haven't understood. You can directly say that

Honestly, I am quite lost.
Are you trying to force equip paper?
It's probably best to ignore the fact about model-data since it's irrelevant and may lead to confusion since in reality its just paper.

Is the issue that the items refuse to appear in the armor slots upon triggering their give-conditions?
Or are you saying you want to be able to right-click equip paper?


Sorry for the confusion.

**Comment by xingfujiuhao** [comment]
When equipping armor. The itemJoin project will be hidden. When the equipment is removed, they will display

**Comment by xingfujiuhao** [comment]
When equipping armor. The itemJoin project will be hidden. When the equipment is removed, they will display

**Comment by xingfujiuhao** [comment]
Instead of equipping items. Will move the itemJoin project to another location
