### ISSUE TITLE
Bug Skinrestorer 

### ISSUE THREAD

**Issue by uNippw** [RockinChaos/ItemJoin#571]
### Server Version

PaperSpigot 1.8.8

### Resource Version

6.0.4-RELEASE-b923

### Dump Information

https://ci.craftationgaming.com/dump?id=ujokohamep

### Describe The Bug

When I install the 'skinrestorer' plugin, it glitches and doesn't load the player's skin or show the head to click on.

### Expected Behavior

Not to display the error when I install the skinrestorer plugin

### Steps To Reproduce

Server is offline mode
Get latest skin restorer
Give your self skull item with skull owner's skin
Get the error in console, not in chat

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
![image](https://github.com/RockinChaos/ItemJoin/assets/10971577/85e95e59-47f5-4277-80c3-89e0a970ad4f)
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**
