### ISSUE TITLE
"Animate" flag does not take into amounts of items

### ISSUE THREAD

**Issue by enels0n** [RockinChaos/ItemJoin#572]
### Server Version

PaperSpigot 1.20.2 (Build 318)

### Resource Version

ItemJoin v6.0.4-RELEASE-b923

### Dump Information

https://ci.craftationgaming.com/dump?id=ixucibixev

### Describe The Bug

When updating the name of stackable items, the plugin does not take into current amount of items.  Placeholders in names are used to localize titles.

### Expected Behavior

Saving the current amount of items

### Steps To Reproduce

1. Set "animate" itemflag
2. Get item 2 times
3. Drop one of it
4. See

### Additional Info

https://youtu.be/pMkgAWX1MwE

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Ah yeah this here would be the culprit; https://github.com/RockinChaos/ItemJoin/blob/a4f8da9acc59ef46ca0aa285acb371c0202a3a09/src/main/java/me/RockinChaos/itemjoin/item/ItemAnimation.java#L354

I temporarily hard-coded it to where any animated item automatically has its count reset to what is "defined" in the items.yml to resolve an issue a previous issue a user had where they wanted their count to be reset back to its original.


I will look and see what I can do in terms of a solution that will work for both situations.

Please allow me some time to work on a solution.

**Comment by RockinChaos** [comment]
Now fixed in the latest snapshot.
This feature is now disabled by default and must be enabled using `dynamic-count` itemflag instead.

So nothing you need to do since you do not need this feature.
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**
