### ISSUE TITLE
Add Folia support 

### ISSUE THREAD

**Issue by roggy666** [RockinChaos/ItemJoin#574]
### Describe The Feature

Can you add support of folia?: https://github.com/PaperMC/Folia

### Expected Solution

I want this plugin to support and run on folia

### Describe Alternatives Considered

.

### Checklist

- [X] I have read the wiki to make sure my request has not already been implemented.
- [ ] I ticked all of these boxes without actually reading them.
- [x] I have checked that my feature request is unique and another request does not exist.

**Comment by RockinChaos** [comment]
Folia support has officially been added in the latest snapshot.
I did some testing and it seems to work well after I made some changes to the schedulers.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
