### ISSUE TITLE
Could not pass event PlayerChangedWorldEvent to ItemJoin v6.0.5-RELEASE-b928

### ISSUE THREAD

**Issue by VacAge** [RockinChaos/ItemJoin#575]
### Server Version

purpur-1.20.4-2128

### Resource Version

ItemJoin v6.0.5-RELEASE-b928

### Dump Information

https://ci.craftationgaming.com/dump?id=jefohucege

### Describe The Bug

When logging in to the server, he writes 2 errors, previously there was only one on version 1.20.1, but now 2.
[Error Log](https://mclo.gs/xvawBMB)

### Expected Behavior

Log in without mistakes

### Steps To Reproduce

1. Log in to the server and returns an error

### Additional Info

-

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Resolved in the latest snapshot, thanks for the report!

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Thank you for your patience!
