### ISSUE TITLE
proxy + itemjoin

### ISSUE THREAD

**Issue by NezzyUwU** [RockinChaos/ItemJoin#578]
### Server Version

Paper 1.20.4

### Resource Version

ItemJoin v6.0.5

### Describe The Problem

I have a proxy (velocity), when a player enters through a proxy, he is redirected to the lobby server, but when I use itemjoin, the commands are written from the internal console and the proxy is not sent

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [x] I have checked that my help request is unique and another request does not exist.
- [x] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
You specified `- server fabric`
Which is an internal command.

Modifying it to `- 'server: fabric'`
should work properly since `server:` is the command identifier.

**Comment by NezzyUwU** [comment]
thanks
