### ISSUE TITLE
On Death Duping Inventory - Keep Inventory On.

### ISSUE THREAD

**Issue by thedannymojo** [RockinChaos/ItemJoin#579]
### Server Version

PaperSpigot - 196 - 1.20.1

### Resource Version

ItemJoin 6.0.5

### Dump Information

https://ci.craftationgaming.com/dump?id=iroyaqiyec

### Describe The Problem

I need help figuring out how to make it so that _**no multiple instances of an item are possible**_. 
The IJ item opens a menu of goodies. 
As it is a survival server, I made it so that KeepInventory is set to TRUE. This is because I want players to be able to collect their "Soul" to reclaim their items. This is a must setting for this to work. 

The conflict is this:
Upon death, the player should get their soul back, along with their items. One of which is the IJ item (I believe that KeepInventory interferes with the death-drop item flag.)

Once the player collects their soul, they will have 2 instances of the said IJ Item. 
I dont want this.

Is there a workaround this?

Triggers: Join.
Item Flags: Self-Drops, Inventory-Modify, DEATH-KEEP. 

PS: I have seen that this was a prior issue, but I was not able to see discord convos for solution.

### Additional Context

![2024-02-21_09 47 06](https://github.com/RockinChaos/ItemJoin/assets/160752318/d0f96d76-2da9-4374-a209-daab31cac208)
![2024-02-21_09 47 25](https://github.com/RockinChaos/ItemJoin/assets/160752318/972cf84b-feed-491f-96f5-04b2b017a086)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Quick aside before I bug test;
is there a particular reason to use death-keep and/or death-drops itemflag(s)?

If GameRule KeepInventory is set to true then these flags are pointless from my viewpoint since that GameRule already prevents the dropping of items on death and restores the inventory upon respawn.

**Comment by thedannymojo** [comment]
The only reason why KeepInventory is set to TRUE is to ensure that the Vanilla Refresh datapack "Soul Links" works. Some plugins online also require KeepInventory On. 

I was thinking that maybe there was a way to add an item-flag that **_destroys all dupe instances in inventory_**. If that is possible.

**Comment by RockinChaos** [comment]
Apologies for the long delay,
I have made some changes to how ItemJoin functions when KeepInventory is on.

Furthermore, I changed the functionality of death-keep so it should resolve any issues.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**
