### ISSUE TITLE
1.10.2 skull-item book-item not work itemflags example inventory-modify

### ISSUE THREAD

**Issue by olget** [RockinChaos/ItemJoin#58]
please fix it

**Comment by RockinChaos** [comment]
Looking into it now. It seems to be that a few itemflags are broken. Like prevent inventory-modify seems to be working but others such as prevent placement, count-lock, and others seem to be broken. I will continue to look into this and there will be a fix out later today

**Comment by RockinChaos** [comment]
Found the issue.. A skull item is technically not classified as a "block" so I had to add an alternative to that if it is a skull item. Itemflags will now work on v3.6 releasing today.

**Comment by RockinChaos** [comment]
Oh man! Thanks for making me look into this, I found another bug where ItemJoin-Specific-Items option was never working. I forgot to initialize it... derp.

**Comment by RockinChaos** [comment]
Fixed as of v3.6 and can be downloaded here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=107393

If you have any other problems feel free to open another issue.
