### ISSUE TITLE
Custom resourcepack item given on join

### ISSUE THREAD

**Issue by JelE123** [RockinChaos/ItemJoin#580]
### Server Version

Paper 1.20.4

### Resource Version

v6.0.5

### Dump Information

https://ci.craftationgaming.com/dump?id=peyebunora

### Describe The Problem

Hello! I wanna make a item that players get ONLY on first join. It happens to be a custom item from a resourcepack... Is there any way to make that happen?

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by MrPotat1282** [comment]
![Capture](https://github.com/RockinChaos/ItemJoin/assets/129358273/cc2355ad-4d46-47eb-b8d1-b6c59553f5df)
In the config for an item you can use "model-data" to specifiy the custom model data and under Triggers set it to "FIRST-JOIN"

**Comment by RockinChaos** [comment]
Marking this as solved as the answer provided above answers exactly what was asked.
If you need further help, feel free to re-open this issue.
