### ISSUE TITLE
Failed to execute database statement.

### ISSUE THREAD

**Issue by sagaciousness2022** [RockinChaos/ItemJoin#584]
### Server Version

Paper 1.20.2

### Resource Version

ItemJoin-6.0.6-SNAPSHOT-b977

### Dump Information

https://ci.craftationgaming.com/dump?id=labeyucedu

### Describe The Bug

Error displayed in administrator chat and console
mysql:https://mclo.gs/NxZ4q9i 
sqlite:https://mclo.gs/WbHdAgD

### Expected Behavior

Can be hidden or fixed.

### Steps To Reproduce

1.Player synchronizes inventory from server A to server B, then returns from B to A.

### Additional Info

![mysql](https://github.com/RockinChaos/ItemJoin/assets/147455518/4aa2d81a-16c0-4cb8-80f6-e7e7a2483525)
![M89IWZ3FY}L`87WMZVE~ESA](https://github.com/RockinChaos/ItemJoin/assets/147455518/ecbd3700-2d92-4fba-8ea9-ab7bb1528da3)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Confirmed, the issue was due to a tweak I made to database handling.
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by sagaciousness2022** [comment]
I have already installed version 6.0.6-SNAPSHOT-b978. The console is no longer displaying, but the OP chat is still visible.
![Uploading 93a00d55085d2c2f32582bb9e88d955.png…]()

**Comment by RockinChaos** [comment]
Could you enable debugging in ItemJoin's config.yml and then `/itemjoin reload` and produce the error again? It should list something in the console after doing that.

**Comment by sagaciousness2022** [comment]
I tried enable debugging and reload, and the error hasn't occurred since then. I tested it for two days, including several sub-servers, and it's been the same situation.
https://mclo.gs/L31YMYD

**Comment by RockinChaos** [comment]
Is this including the OP chat as well or is it still showing the error in the chat?

**Comment by sagaciousness2022** [comment]
Include OP chatting, and the backend won't throw errors even when debug mode is not enabled.

**Comment by RockinChaos** [comment]
Ah okay, in that case, it's likely the previous issue after updating was a residual message from when it was fixing the database due to the incorrect formatting in the previous version.

I'll keep this issue open for a bit, let me know if the issue occurs again.
I recommend keeping debugging enabled in the meantime in case the issue occurs so we can get the stack trace.
