### ISSUE TITLE
Add Disposable Goods.

### ISSUE THREAD

**Issue by xyblues** [RockinChaos/ItemJoin#59]
Players can only use a single item, use after cleaning items
An example, the player has 10 items, when the player run the command after only 9 items left.
Sorry for my poor English.

**Comment by RockinChaos** [comment]
Ahhh So items that have single command uses, and so once the command is ran it will remove x1 of the item from the players inventory. Is this what you mean? If so it is very achievable and I could easily get it out for v3.7

**Comment by xyblues** [comment]
Yes,thank you very much.

**Comment by Mayr3D** [comment]
it would be so cool for first join item :dancers:

**Comment by RockinChaos** [comment]
ItemJoin v3.7 has been released and you can get it here;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115467

This has been added as of v3.7 :D
