### ISSUE TITLE
Itemjoin blocking interactions with recipebook

### ISSUE THREAD

**Issue by GIToez** [RockinChaos/ItemJoin#592]
### Server Version

Purpur 1.20.4

### Resource Version

ItemJoin v6.0.5

### Dump Information

https://ci.craftationgaming.com/dump?id=mitufitoti

### Describe The Bug

The plugin blocks all custom functions when involving the recipebook from other plugins

### Expected Behavior

When clicking on an item in the recipe book (for my plugin) its opens up a custom GUI

### Steps To Reproduce

This is a custom plugin designed for my server, its turns the recipebook into an interactive menu which clicking on recipes. 

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Is this recipe book set up something you are able to provide me so I can bug test against it?
It would simply things if you are able to provide the configuration needed (not ItemJoin) to produce this bug.

**Comment by GIToez** [comment]
It turns the minecraft recipebook into a quest tracker, when you Click on that "recipe" it opens up a gui menu. 

I can send ya the plugin but requires betonquest IDK if you ever used that, takes some setting up. 

Uploading 2024-04-19 14-52-59.mp4…

**Comment by RockinChaos** [comment]
Going to close this since we continued the convo via discord.
