### ISSUE TITLE
Question about conditions

### ISSUE THREAD

**Issue by BartosB13** [RockinChaos/ItemJoin#596]
### Server Version

Paper 1.20.1

### Resource Version

6.0.7-RELEASE-b995

### Dump Information

-

### Describe The Problem

 Hello!
I just want to ask about how this works for items. I set it up via the in-game menu. Perhaps the problem is the extra colon inside the placeholder?
 
```
    inventory-conditions: '%betonquest_SYS:condition.itemjoin_blockcmd%:EQUAL:false'
    interact-conditions: '%betonquest_SYS:condition.itemjoin_blockcmd%:EQUAL:false'
```

In console:

`[18:43:18 WARN]: [ItemJoin_WARN] {ItemMap} The condition %betonquest_SYS:condition.itemjoin_blockcmd%:EQUAL:false is not the proper format CONDITION:OPERAND:VALUE, the item may not function properly.`

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Can confirm that this is due to the colon inside the placeholder. ItemJoin parses using the colons as parts so its getting 4 parts instead of 3 because of that colon.

I am going to classify this as a bug and work on a fix as it should be solvable by formatting the placeholders **before** parsing the colons which would resolve this issue since the placeholder would be properly formatted.

**Comment by RockinChaos** [comment]
Now resolved in the latest snapshot.
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by BartosB13** [comment]
I tested it. Everything seems to be working properly now. Thanks for the help. This ticket can be closed.

A small additional question at the very end, will the FakeCreative plugin be developed/supported long-term? I'm considering purchasing it and using it on one of my server's modes.

**Comment by RockinChaos** [comment]
> I tested it. Everything seems to be working properly now. Thanks for the help. This ticket can be closed.
> 
> A small additional question at the very end, will the FakeCreative plugin be developed/supported long-term? I'm considering purchasing it and using it on one of my server's modes.

Glad everything is working!

To answer your question yes, FakeCreative receives regular updates just like ItemJoin and it is prioritized over my free plugins. Like all my plugins they are built off of user requests so most new features are implemented based on user requests. Though I do use my own plugins so sometimes I implement features that I found need of.

**Comment by BartosB13** [comment]
ok thanks!
