### ISSUE TITLE
Is it possible to create a chess menu?

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [RockinChaos/ItemJoin#598]
### Server Version

Spigot 1.21

### Resource Version

ItemJoin  6.0.8-SNAPSHOT-b1000

### Dump Information

https://ci.craftationgaming.com/dump?id=sibiwoqova

### Describe The Problem

I am wondering if there is a way to create a chess menu with items in it which the user can click on to execute command. Something like this:
![image](https://github.com/RockinChaos/ItemJoin/assets/68761233/719c2236-9857-45de-a48f-580941f14566)
I had a read on #276 and it seems like I need another plugin to do that, is it true?

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Correct, ItemJoin is meant to be physical items that the player can access. Which means they are originally meant to be given via their inventory.

ItemJoin does not handle or create virtual menus (excluding the item editor). Typically ItemJoin is meant to be used in conjunction with a menu plugin so you can use an ItemJoin item to open these menu's via interacting with the ItemJoin item.

Some menu plugins that I recommend are; DeluxeMenus, ChestCommands, and BossShop.

**Comment by RockinChaos** [comment]
Any of the above-listed plugins work best with ItemJoin. Some just have different features than others so it's really based on your needs. Personally, I like using DeluxeMenus and it has great developer support.
