### ISSUE TITLE
Link item

### ISSUE THREAD

**Issue by mixerrules** [RockinChaos/ItemJoin#6]
So I really don't think this is possible, basically add a thing in the item config that's like "link:" and this will make it where when u right click it will open the link

**Comment by RockinChaos** [comment]
This is very possible. It's just a manner of figuring out how to do so. I'll look into it :)

**Comment by RockinChaos** [comment]
This has been added as of ItemJoin v2.7 and works as such

      commands:
        - 'message: URL'

message: private messages the player and you can send the url through there. You can add any custom message that you want!

**I plan to release ItemJoin v2.7 tomorrow so look out for it!**
