### ISSUE TITLE
On book not work item flags

### ISSUE THREAD

**Issue by olget** [RockinChaos/ItemJoin#60]
On book not work item flags

**Comment by RockinChaos** [comment]
I need more information than that,
Such as
1.) any errors in console?
2.) what item flags are you using?
3.) Please post your config,en-lang, and items.yml in separate pastebin.com and send me the links.
4.) what version of craftbukkit / spigot are you using?

**Comment by RockinChaos** [comment]
Hey, I am still looking forward to a reply from you, I hope I can resolve your problem!
