### ISSUE TITLE
Bug with Paper item join kick

### ISSUE THREAD

**Issue by LixiUnivers** [RockinChaos/ItemJoin#602]
### Server Version

Paper 1.20.4

### Resource Version

ItemJoin v6.0.7

### Dump Information

https://ci.craftationgaming.com/dump/?id=ategumahaq

### Describe The Bug

I've set up an item where when you click on it, it sends a message in the chat in color. Before, I used spigot, and this problem didn't occur, but with paper it kicks me under this reason: “Illegal characters in chat”.

### Expected Behavior

I'd like the problem to be solved, I think it's coming from colored messages, I'd really like an accounting with Paper.

### Steps To Reproduce

Execute a command on a item, with a chat color message.

### Additional Info

+ The problem is on message with :  
interact:
      - 'say &8test!'

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Confirmed and fixed in the latest snapshot. Was just paper doing unnecessary paper things as usual.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by LixiUnivers** [comment]
> Confirmed and fixed in the latest snapshot. Was just paper doing unnecessary paper things as usual.
> 
> Link; https://ci.craftationgaming.com/downloads **Remember to remove your old ItemJoin.jar file**
> 
> Let me know!~

It's work! Thanxs

**Comment by RockinChaos** [comment]
The official release is now available.
Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=557378
