### ISSUE TITLE
Itemflag count-lock does not work on arrows

### ISSUE THREAD

**Issue by Antal1609** [RockinChaos/ItemJoin#603]
### Server Version

Paper version 1.21.1-40-master@2fdb2e9

### Resource Version

ItemJoin-6.0.8-SNAPSHOT-b1019

### Dump Information

 https://ci.craftationgaming.com/dump?id=uyusegihad

### Describe The Bug

Itemflag count-lock does no longer work on arrows. When you use a bow to shoot the arrow it shoots and the item in your inventory vanishes.

This is problematic for the teleport itemflag on arrows.

### Expected Behavior

The arrow with the itemflag count-lock does not vanish from the inventory when shooted by a bow.

### Steps To Reproduce

1. Open Minecraft
2. Shoot bow

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Confirmed.. yikes apparently in 1.20.5/1.20.6;
- `EntityShootBowEvent#setConsumeItem is not currently functional (default behaviour is retained).` (MD_5)
So it appears it is an issue on spigot end for whatever reason.

I made some changes to implement my own method and it seems to be working well on my end.
- If you have multiple arrows it simply adds +1 back to the count when shot.
- If you have no arrows remaining the arrow item is re-given as defined in your items.yml.

You can see these changes in the latest snapshot.
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
