### ISSUE TITLE
Please Add Support for 1.21.1/1.21

### ISSUE THREAD

**Issue by Abasing** [RockinChaos/ItemJoin#607]
### Describe The Feature

Exieelnt Plugin but now doesn't work on Paper 1.21.1

### Expected Solution

I would love to use this on latest version!

### Describe Alternatives Considered

I tried latest version and changed API in plugin.yml but still didn't worked

### Additional Context

[22:56:50 ERROR]: [ItemJoin_ERROR] Detected a unsupported version of Minecraft!
[22:56:50 ERROR]: [ItemJoin_ERROR] Attempting to run in NMS compatibility mode...
[22:56:50 ERROR]: [ItemJoin_ERROR] Things may not work as expected, please check for plugin updates.

### Checklist

- [X] I have read the wiki to make sure my request has not already been implemented.
- [ ] I ticked all of these boxes without actually reading them.
- [x] I have checked that my feature request is unique and another request does not exist.

**Comment by RockinChaos** [comment]
Please see the giant bold text on the plugin page.
![image](https://github.com/user-attachments/assets/fee4fc58-c70d-4e98-a581-5fe26528e89c)


The API version has nothing to do with compatibility, there were massive changes made in 1.21 by spigot which has taken a while to resolve issue for 1.21+ and > 1.20.6.

As stated on the plugin page the release will be submitted for approval either today or tomorrow. If you want to help test out the snapshot for any bugs you can feel free to get it here;
https://ci-dev.craftationgaming.com/job/ItemJoin/lastSuccessfulBuild
