### ISSUE TITLE
ChestCommands customed command for opening menu's bug

### ISSUE THREAD

**Issue by BeastPsycho** [RockinChaos/ItemJoin#61]
There are a ChestCommands customed command for opening menu's bug!
When do you set a join item for execute a custom command for opening a chestcommand GUI, this is not working:

I tried with...
commands:
   -'player: options'
   -'options'

Can you fix it? So much thanks

**Comment by RockinChaos** [comment]
I see this a lot, I wish I could tell you this is an easy bug fix on our end but its not. This is a bug with ChestCommands.

The best way I can explain it is the custom commands that are registered from his plugin are not real. They are ghost commands that are registered after ALL of your plugins are done loading. Therefor we cannot grab the command or communicate with it in any way.

The easy solution though is to use ChestCommands RAW commands.
You would want to use /cc open <file>
So it would be like this;
commands:
-'player: cc open options'

or

commands:
-'cc open options'

These are all the raw commands supported by all us developers
https://dev.bukkit.org/bukkit-plugins/chest-commands/pages/tutorial/commands-and-permissions/

As long as its not a custom command you created within ChestCommands, it will work. 
If this has or has not resolved your problems please let me know.

**Comment by altrisi** [comment]
I recommend doing another thing:
>
>commands:
>-'console: cc open <menu name> %player%'

Because using this, player isn't going to see the ChestCommands message for opening the menu.
