### ISSUE TITLE
I can move items in the inventory while in block-movement mode: true

### ISSUE THREAD

**Issue by cadafinnX** [RockinChaos/ItemJoin#612]
### Server Version

paperSpigot 1.12.1

### Resource Version

v6.1.0-RELEASE-b1031

### Dump Information

https://ci.craftationgaming.com/dump?id=cudaqoxuku

### Describe The Bug

I don't know why I can move items from the inventory having block-movement: true mode, do I need to know how can I make the item unmovable in the inventory?

Code:

items-Version: 8

# General options that apply to the custom items' functionality.
items-Delay: 2
items-Overwrite: false
items-Spamming: false
items-RestrictCount: false

# This is the section where the custom items created will be stored.
# All created items should be saved under the 'items' section for each 'custom-item' subsection.
items:
  Brujula-Selector:
    name: '&c&l&k!!&1Selector Modalidades&c&l&k!!'
    id: 345
    slot: 0
    lore:
      - '&7Click Derecho para activar'
    commands:
      - command: 'console: fly %player%'
    commands-sound: BLOCK_NOTE_BLOCK_PLING
    give-at-respawn: false
    first-join-only: false
    block-movement: true
    allow-drop: false
    enable-worlds: lobby

### Expected Behavior

the item cannot be moved in the inventory

### Steps To Reproduce

E button
Move item
should not be selected to move

### Additional Info

block-movement: true

It is supposed that when it is true the item should not be moved from the inventory but even so if I can with or without an operator I can move it, it should not happen

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
So where are you getting these config options from for your item?

These have never existed and do not exist in the wiki;
```
    give-at-respawn: false
    first-join-only: false
    block-movement: true
    allow-drop: false
``

This *have* existed but no longer exist as a new structure is used;
```
    commands:
      - command: 'console: fly %player%'
```

Depending on how you want things set up you would likely want your command to be;
```
interact: 
  - 'console: fly %player%
```

as for your other options they would likely be;
```
itemflags: self-drops, death-drops, inventory-modify, item-store
triggers: join, world-switch
```

Please read the wiki for the options that would suit you; [Item Commands](https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#establishing-itemcommands), [ItemFlags](https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#defining-an-items-itemflags), [Triggers](https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#defining-an-items-triggers).

**Comment by cadafinnX** [comment]
The old codes I found in the AJNEB97 video, unfortunately I didn't find tutorials for the new version of ItemJoin only the old one that is already dead, but thanks for helping me and solving the problem.
