### ISSUE TITLE
[ItemJoin_ERROR] {DependAPI} [2] Unsupported SkinsRestorer version detected, disabling SkinsRestorer support.

### ISSUE THREAD

**Issue by cadafinnX** [RockinChaos/ItemJoin#616]
### Server Version

paperSpigot 1.12.1

### Resource Version

v6.1.0-RELEASE-b1031

### Dump Information

https://ci.craftationgaming.com/dump/?id=sotememobu

### Describe The Bug

![Captura de pantalla 2024-11-20 205029](https://github.com/user-attachments/assets/b3587a40-fbf9-4c9f-8373-fe3f7f12e432)

### Expected Behavior

esperaba que la cabeza del jugador sea igual a su skin premium o que la skin del jugador si no son premium "No se si eso funcione". como puedo hacer que el plugin skinRestorer sea compatible con itemjoin y solucionar el error de DEPEND API, por que estoy usando una network un proxy mejor dicho llamado velocity.

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/76857a8b-d6e3-4887-84d6-afbf93d40e89)

### Additional Info

![image](https://github.com/user-attachments/assets/35358c65-8999-442f-b617-fd7ec613c967)
![image](https://github.com/user-attachments/assets/845454bb-468a-4f46-ad34-854795286f52)
![image](https://github.com/user-attachments/assets/a0e708db-7a01-462e-9a87-98818a89e26c)

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
![image](https://github.com/user-attachments/assets/5d46af93-801c-4604-8914-91d1018fb63b)

Already resolved in the snapshots, feel free to use it or wait for the official release.
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**
