### ISSUE TITLE
Incompatibile with chestcommand (?)

### ISSUE THREAD

**Issue by Cri16228** [RockinChaos/ItemJoin#65]
Hi. I have a problem, i have configured itemjoin like this:
(Here only important setting)
world (worldname):
Item: COMPASS
commands:
   - 'player: menu' (menu to open chest command menu)
But when i click with compass bukkit say "command not found"
How can i fix it? I need itemjoin because i fan set item per world

**Comment by RockinChaos** [comment]
Chest commands is very compatible with ItemJoin, thats why it's on the front page.

You cannot use custom commands because chest commands is some-what buggy.

Use
 cc open menu
As the command.

You can only use the commands shown on the chest commands page

**Comment by RockinChaos** [comment]
Sorry for the crappy response I was not home and at work but I wanted to give to a quick response, here is a more proper response;



I see this a lot, I wish I could tell you this is an easy bug fix on our end but its not. This is a bug with ChestCommands.

The best way I can explain it is the custom commands that are registered from his plugin are not real. They are ghost commands that are registered after ALL of your plugins are done loading. Therefor we cannot grab the command or communicate with it in any way.

The easy solution though is to use ChestCommands RAW commands.
You would want to use /cc open [file]
file would be the what the custom menu is saved as.
So it would be like this;
commands:
-'player: cc open menu'

or

commands:
-'cc open menu'

These are all the raw commands supported by all us developers
https://dev.bukkit.org/bukkit-plugins/chest-commands/pages/tutorial/commands-and-permissions/

As long as its not a custom command you created within ChestCommands, it will work.
If this has or has not resolved your problems please let me know.

**Comment by Cri16228** [comment]
Sorry for my reply now..
I have a new problem, my items.yml http://pastebin.com/iWJh3Hrw
I have a little server without bungeecord but with multiverse-core and when i change world (with "mvtp world_name") my items remain the same of MainLobby. I don't have multiinv, multiverse-intentory or other plugin

**Comment by RockinChaos** [comment]
The items are not meant to magically dissapear when switching worlds, you have to set clear-on-world-changed to true in the items.yml

**Comment by Cri16228** [comment]
Ops.. thanks

**Comment by RockinChaos** [comment]
It's all good, if you are looking to only remove ItemJoin items this will be available in v3.7. Currently you can only remove all Inventory items.

**Comment by Cri16228** [comment]
3.7? but [here](https://dev.bukkit.org/bukkit-plugins/itemjoin/files/) i can see only the version 3.6

**Comment by RockinChaos** [comment]
this **### will** be available in v3.7, as you can see its not released yet I am currently developing it. There is no ETA atm but it should be out within a few days if everything goes smoothly.

**Comment by Cri16228** [comment]
Oh thanks 
I wait for the new versione

**Comment by RockinChaos** [comment]
ItemJoin v3.7 has been released and you can get it here;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115467

Thank you for opening a ticket and if you still need help feel free to re-open this issue and comment back here.
