### ISSUE TITLE
Teleporting to one world in specific causes error

### ISSUE THREAD

**Issue by SioWolf** [RockinChaos/ItemJoin#66]
Here is the error: http://pastebin.com/JcL9fU2V

I don't know what information to give, since it doesn't really tell me whats going wrong... this world, like all other worlds, is in Multiverse, and loads fine for the player. It has no issues with any other plugins. 

This world is a plotsquared world but:

xcreative is a creative world too so its not the gamemode

spawn has a custom world generator too so its not the generator

all other settings that I can think of were the same.

Plugin version: v3.6
Multiverse version:  2.5.0-SNAPSHOT-b722
Server version: Paper-826

**Comment by RockinChaos** [comment]
Hmmm interesting, can you send me your items.yml,config and en-lang yml in a pastebin.com and Ill get to bug testing.

**Comment by SioWolf** [comment]
Ok, I can provide that. Do note, however, that no matter what I put in the items.yml it still does this. The only way to make it stop is to make it NOT try to give items at all in that world. I'm noticing that all other worlds are being added to the firstjoin file just fine, but this one isn't appearing in the file.

Items.yml: http://pastebin.com/v8mTRbK5
Config: http://pastebin.com/rwwVx9hw
En=-lang: http://pastebin.com/bHAHNuNe

**Comment by RockinChaos** [comment]
Doh... I was so exhausted I was still testing it trying to figure out how you got an error... lol. Derp. That's good, if you have any more errors feel free to re-open this issue.
