### ISSUE TITLE
PerWorldInventories support

### ISSUE THREAD

**Issue by SioWolf** [RockinChaos/ItemJoin#67]
Plugin does not support PerWorldInventories.

**Comment by RockinChaos** [comment]
*Correction, PerWorldInventories does not support ItemJoin, I am currently trying to get in contact with the developer about this, I will keep you posted.

**Comment by SioWolf** [comment]
Ok, I just came on here to update this myself. It APPEARS to be working right now...

I actually didn't have it installed on my test server, which I wasn't aware of. Now that I do it seems to be working fine. Whats wrong with it that you know of? I was just about to add it to my production server since it seemed to be working.

**Comment by RockinChaos** [comment]
This is an acknowledged bug, It only affects certain people depending on how they setup PWI but I will have possibly a work around for v3.7 (releasing soon). Its quite difficult to get ahold of the PWI dev for proper implementation of ItemJoin.

If you do experience this bug again please report it back here, but there will be a definite work around come v3.7. Took me a bit of time to find it xP

**Comment by RockinChaos** [comment]
ItemJoin v3.7 has been released and you can get it here;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115467

This issue has been fixed as of v3.7 and we now have the option to hook into PerWorldInventory. I hope this resolved your problem.
Thank you for opening a ticket and if you still need help feel free to re-open this issue and comment back here.
