### ISSUE TITLE
Overwrite Current Inventory

### ISSUE THREAD

**Issue by SioWolf** [RockinChaos/ItemJoin#68]
I want to add this plugin to a server with a pre-existing player base. If I use it to give players a starter kit in survival, it will overwrite everyone's current inventories (at least, the slots it is set to use will be overwritten). 

Can you add a setting or flag not to overwrite anything in that slot?

EDIT: Found this option. It was in a different spot in the config then I had already looked through. I must say, this supports the review on Spigot that says theres way too many comments in this config. I get so lost.

EDIT 2: Despite using the "slot: Arbitrary" thing, it is still overwriting the items in the inventory. Will test further.

EDIT 3: Even with PerWorldInventories removed, using the arbitrary thing is not working. The item is not spawning at all.

**Comment by RockinChaos** [comment]
I am doing major bug testing right now and I will get back to you on this asap, if an item is set to Arbitrary its job is to put the item in the next available slot in the players inventory. I will begin testing this shortly.

**Comment by RockinChaos** [comment]
I and the ItemJoin snapshot testers have extensively tested this bug on the Arbitrary slot, it is working perfectly fine on our end, it does not overwrite the inventory and is working as intended. Are you sure you configured ItemJoin correctly?

Are you using v3.6?
Can you please send your items.yml in a pastebin.com

**Comment by RockinChaos** [comment]
ItemJoin v3.7 has been released and you can get it here;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115467

Thank you for opening a ticket and if you still need help feel free to re-open this issue and comment back here.
