### ISSUE TITLE
To much lag ;(

### ISSUE THREAD

**Issue by llaurenss** [RockinChaos/ItemJoin#69]
I had to downgrade to version 3.4 because all the above versions are lagging my server very hard.

version 3.4:
[https://puu.sh/rnlPI.png](https://puu.sh/rnlPI.png)

version 3.7:
[https://puu.sh/rnlRv.png](https://puu.sh/rnlRv.png)

**Comment by RockinChaos** [comment]
I will continue to look into this but there is no changes between v3.4 and v3.7's core code. So I do not know why there is a lag reduction. Ill post back when I get more information.

**Comment by RockinChaos** [comment]
This should be fixed as of v3.8 and it has been uploaded. You can pick it up here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=118664

**Comment by llaurenss** [comment]
Sadly I'm still having lag https://puu.sh/rIPF7.png

items.yml
`items-Version: 5

Global-Settings:
  Prevention:
    prevent-pickups: false 
    AllowOPBypass: false
    CreativeBypass: true
  Clear-On:
    clear-on-join: true
    clear-on-world-change: true
    clear-only-itemjoin-on-join: false
    clear-only-itemjoin-on-world-change: false
    AllowOPBypass: false
  First-Join:
    FirstJoin-Mode-Enabled: false
  Get-Items:
    ItemJoin-Specific-Items: true
    Global-Items: false
    Delay: 2

world-list:
  - spawn
  - speedbuild
  - buildffa

spawn:
  items:
    Ranked-item: 
      id: 276 
      slot: 0
      name: '&aJoin Ranked' 
      data-value: 0 
      count: 1 
      lore: 
      commands: 
        - 'console: uc clear %player%'
        - 'stopemote'
        - 'ranked'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK, PHYSICAL
      commands-cooldown: 1 
      itemflags: 
        - 'unbreakable'
        - 'placement'
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
    BuildFFA-item: 
      id: 327
      slot: 4
      name: '&cBuildFFA' 
      data-value: 0 
      count: 1 
      lore: 
      commands: 
        - 'warp buildffa'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK, PHYSICAL
      commands-cooldown: 1 
      itemflags: 
        - 'unbreakable'
        - 'placement'
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
    Leave-item: 
      id: 351
      slot: 1
      name: '&cLeave Queue' 
      data-value: 1
      count: 1 
      lore: 
      commands: 
        - 'battle leave'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK, PHYSICAL
      itemflags: 
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
    KitEditor-item: 
      id: 340
      slot: 3
      name: '&cKit Editor' 
      data-value: 0
      count: 1 
      commands-cooldown: 1
      lore: 
      commands: 
        - 'savekit'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK, PHYSICAL
      itemflags: 
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
    Cosmetics-item: 
      id: 130
      slot: 8
      name: '&cCosmetics' 
      data-value: 0
      count: 1 
      lore: 
      commands: 
        - 'console: cc open Gadgets %player%'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      commands-cooldown: 1 
      itemflags: 
        - 'unbreakable'
        - 'placement'
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
    Radio-item: 
      id: 25
      slot: 7
      name: '&cRadio' 
      data-value: 0
      count: 1 
      lore: 
      commands: 
        - 'radio'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      commands-cooldown: 1 
      itemflags:
        - 'unbreakable'
        - 'placement'
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
    Speedbuild-item: 
      id: 98
      slot: 5
      name: '&cSpeedbuild' 
      data-value: 0
      count: 1 
      lore: 
      commands: 
        - 'warp speedbuild'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      itemflags: 
        - 'unbreakable'
        - 'placement'
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
buildffa:
  items:
    Kit-itemBuild: 
      id: 267
      slot: 0
      name: '&cGet Kit' 
      data-value: 0
      count: 1 
      lore: 
      commands: 
        - 'pvpkit BuildUHC'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      itemflags: 
        - 'unbreakable'
        - 'placement'
        - 'respawn'
        - 'cancel-events'
        - 'world-changed'
        - 'AllowOpBypass'
    Spawn-itemBuild: 
      id: 330
      slot: 1
      name: '&cBack to Spawn' 
      data-value: 0
      count: 1 
      lore: 
      commands: 
        - 'warp spawn'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      itemflags: 
        - 'unbreakable'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
        - 'CreativeBypass'
speedbuild:
  items:
    Blocks-item: 
      id: 41
      slot: 0
      name: '&cGet blocks' 
      data-value: 0
      count: 1 
      lore: 
      commands: 
        - 'console: give %player% 1'
      commands-cooldown: 1
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      itemflags: 
        - 'unbreakable'
        - 'placement'
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
        - 'CreativeBypass'
    Speedbuildspawn-item: 
      id: 330
      slot: 8
      name: '&cBack to Spawn' 
      data-value: 0
      count: 1 
      lore: 
      commands: 
        - 'warp spawn'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      itemflags: 
        - 'unbreakable'
        - 'placement'
        - 'inventory-modify'
        - 'cancel-events'
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
        - 'CreativeBypass'`

**Comment by RockinChaos** [comment]
I'm going to try force compiling with Java 7 this time along with a few bug fixes and cut the code down a bit more for v3.9, but other than that if it still causes lag that will be something I will have to take into consideration when developing v4.0.

Can I ask, what version of java is installed on your system? If you can get the exact version that would be great but if you can't just tell me java 7 or 8.

Mine is Java 8 101. Then on my main system its Java 7 76 with no lag from ItemJoin on each system.
