### ISSUE TITLE
Error with PerWorldPlugins and the Off-Hand Slot

### ISSUE THREAD

**Issue by mathhulk** [RockinChaos/ItemJoin#70]
I get the following error when trying to load ItemJoin and PerWorldPlugins together when a player joins the server.

> 
27.09 19:26:52 [Server] INFO ... 15 more
27.09 19:26:52 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
27.09 19:26:52 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
27.09 19:26:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
27.09 19:26:52 [Server] INFO at sun.reflect.GeneratedMethodAccessor533.invoke(Unknown Source) ~[?:?]
27.09 19:26:52 [Server] INFO at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.clearOnJoin(JoinItem.java:35) ~[?:?]
27.09 19:26:52 [Server] INFO at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.clearItemJoinOnly(JoinItem.java:118) ~[?:?]
27.09 19:26:52 [Server] INFO at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.clearInventory(JoinItem.java:132) ~[?:?]
27.09 19:26:52 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInOffHand()Lorg/bukkit/inventory/ItemStack;
27.09 19:26:52 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.c(AbstractLoginListener.java:91) [ProtocolSupport.jar:?]
27.09 19:26:52 [Server] INFO at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.b(AbstractLoginListener.java:145) [ProtocolSupport.jar:?]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerServerPlugins.jar:?]
27.09 19:26:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.8_latest.jar:git-Spigot-e4d4710-e1ebe52]
27.09 19:26:52 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
27.09 19:26:52 [Server] INFO org.bukkit.event.EventException
27.09 19:26:52 [Server] INFO Could not pass event PlayerJoinEvent to ItemJoin v3.7
27.09 19:26:52 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****

As you can see in the error, it seems to have been caused by ItemJoin not being able to detect the offhand slot method, due to my server being on version 1.8. Could you possibly push a fix for this and add full 1.8 support?

**Comment by RockinChaos** [comment]
Very aware of this issue and it is already fixed for v3.8 and will be released in the coming week.

**Comment by mathhulk** [comment]
Was this an issue with just the off-hand slot?

**Comment by RockinChaos** [comment]
yes, its because I forgot to add the combat checker to the new features I added. So this error only occurs on 1.8 and lower.

**Comment by RockinChaos** [comment]
This is now fixed for v3.8 and it has been uploaded. You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=118664
