### ISSUE TITLE
Cannot get items

### ISSUE THREAD

**Issue by Brickery** [RockinChaos/ItemJoin#77]
I can't receive items through itemjoin using `/itemjoin get <itemName>` or through the first-join mechanic. I have installed the optional dependencies vault and PlaceholderAPI, both of which are enabled in the config.yml.

yaml-online-parser.appspot.com doesn't give me any errors with my items.yml file.

http://pastebin.com/f1Fe0Fp6 (items.yml)

I can see my items Servers and Tutorial through /itemjoin list. I'm running 1.10.2 with ViaVersion and ViaBackwards.

Thanks.

**Comment by RockinChaos** [comment]
I see the two items you have, you are using ItemJoin v3.8 right?
The correct usage should be /itemjoin get Servers and /itemjoin get Tutorial. Tested it myself and it seems to be working.

**Comment by Brickery** [comment]
Ok, I backdated my server to 1.8.8 and it works fine. Still couldn't get it to work on 1.10.2.

**Comment by RockinChaos** [comment]
Hmmm ill do a bit more of testing on this to see if i can reproduce it and let you know if I do. It would be a simple fix.

**Comment by RockinChaos** [comment]
Been doing a bunch of testing on this and I have been getting the items no problem, are you still having this issue occur? Also are you sure your using the right syntax for the commands?

**Comment by Brickery** [comment]
Yeah, it's all fine now, just updated to 1.8.8 (too lazy to test out 1.10.2 but should be fine now :) Sorry for the late reply. Thanks! @RockinChaos
