### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by PixelWolfsNetwork** [RockinChaos/ItemJoin#78]
Hello, i have a feature request, create support for bungeecord, add in config a option to create custom items joins per bungeeworld please!

**Comment by RockinChaos** [comment]
Not sure what you mean, itemjoin can already hook into bungeecord and i think you mean per bungeecord server?

**Comment by PixelWolfsNetwork** [comment]
for example:
-lobby: compass,  bone, chest
-minigamelobby1: compass, chest, clock
-minigamelobby2: chest, green dye, clock

**Comment by RockinChaos** [comment]
Sorry for the late reply I never got the push notification to my phone.
ItemJoin is already capable. It has multiple items per world & server support. 
See the itemjoin wiki https://www.spigotmc.org/wiki/itemjoin/
Or even check out a demo video https://youtu.be/4RrE6z--BsU

If your still having problems please reply here.

**Comment by PixelWolfsNetwork** [comment]
thx dude
