### ISSUE TITLE
Yet another "doesn't work on my server" issue...

### ISSUE THREAD

**Issue by LudusMC** [RockinChaos/ItemJoin#8]
I've recently replaced CustomJoinItems with your plugin  and i have to say that i'm quite impressed (on paper) with the features it has, and i'll have to thank you for making this, but it doesn't seem to be working on my server, and by that i mean, the one item i've put in the items.yml file doesn't appear in the inventory...

No errors pop up in the console, i am running multiverse-core version 2.5-b699, multiverse-inventories version 2.5-b335, PlaceholderAPI version 1.9.0.1

This is my config file:
http://pastebin.com/JynLEESt
This is my items file:
http://pastebin.com/aVW6Er1x

Any help would be appreciated,
Thanks for your time...
Regards,

**Comment by RockinChaos** [comment]
Hmmm interesting... I copied your config and items.yml and it seems to work for me.

Is the world you are trying to get the items on join, called hub? Exactly that. Not Hub or hUB or hUb. its hub? The world name is the name of the folder in your server folder.

http://www.swe-gaming.com/fsx/files/2011-12/081625_minecrafserv.png (shows this) (just a random image I found lol)

If your still having problems if you wouldn't mind can you pastebin your startup log & the player joining the server. Also are you using MineverseChat or what is now called, VentureChat?

**Comment by LudusMC** [comment]
Thank you so much! I didn't know that it was caps sensitive, I've been trying to fix this for 2 days... It works fine now, but one more little issue...
As you can see the item in the items.yml is a book. I'm using ChestCommands to make a GUI for info about the server, the website and such.

I've added a command _`cc open LudusInfo`_ to the item, and when i left click it, it firstly opens the GUI and then the book. Is there a way to cancel the book event?
Also, can that command be ran from  the console? (e.g. _`console: cc open LudusInfo %player%`_)

Again i thank you for the amazing and fast support, keep up the fantastic work, and i'll make sure to give you a 5/5 stars and donate as well! I'm quite impressed by your work!
Regards

**Comment by RockinChaos** [comment]
I will be fixing the case sensitive issue in v2.3. 

Hmm... There is no way to cancel the book event but I think I might have a work around. You could set it to give you a normal BOOK. If you want an author you could add lore such as &7by RockinChaos. Etc. Also If you want the glow effect you could add an enchantment such as smite:1. There are indistinguishable besides the noticeable enchantment on the book.

I will look into seeing if I can cancel any kind of events of that sort if a command is bound. Other than that, currently you can only do work arounds.

For the console executor. Currently there is no way to do that in v2.2. That's actually a really great idea! I will see if I can get it out in v2.3. Currently v2.3 is a LARGE update with a lot of changes

I should be able to easily make it so if commands.contains("console:") or ("player:") it will set the given executor to being ran by console or player.

**Comment by LudusMC** [comment]
Alright, fantastic!
Thanks for your help, happy coding and have a great day/night!
Keep up the amazing work!
Regards

**Comment by RockinChaos** [comment]
Thanks man, It makes me feel so good to hear that. Sometimes I feel developers are under appreciated. It really makes my day to hear you say that. :)

the "console: " and "player: " and undefined options have been added as of ItemJoin **v2.3** and will be released in the next few days.

I am still working on the click commands events especially for books. I will let you know once its finished. Hopefully it will be in v2.

**Comment by LudusMC** [comment]
Not a problem at all man,
Sadly, you are right... Devs are under appreciated, and i'm speaking from experience...

Thank you so much for adding those features, really looking forward to the new version!!!
The least i could have done is make your day. ;P Once the new one comes out, i'll make sure to donate as well! :D

Again, thank you for the time you're devoting to this awesome project!
Regards
