### ISSUE TITLE
Conflict with ItemJoin and Skript and permissions

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#80]
Environment: Spigot 1.11.2, Skript 1.22-dev23, ItemJoin 3.8, and a myriad of other up-to-date plugins. The presenting issue is that Skript misinterprets a permission node under certain conditions.

I have isolated the problem to ItemJoin. Specifically, the issue occurs only if I use the hotbar item set by ItemJoin, which executes **mvtp world**. If I execute **/mvtp world** directly, the permissions are correctly assessed. Please see https://github.com/bensku/Skript/issues/335 for a description of the test scripts.

Here is the minimum plugin set needed to reproduce on my test server, due to dependencies.

> ChestCommands            3.1.4
Essentials               2.0.1-b463
ItemJoin                 3.8
Multiverse-Core          2.5.0-SNAPSHOT-b725
PermissionsEx            1.23.4
PerWorldInventory        1.9.0
Skript                   2.2-dev23
Vault                    1.5.6-b49
WorldEdit                6.1.7-SNAPSHOT;3674-9f24f84
WorldGuard               6.2.1-SNAPSHOT;1701-e019890

I would be happy to provide access to my test server, if useful to isolate and resolve this issue.

**Comment by SlimeDog** [comment]
Possibility: The ItemJoin items executes the command as OP. That would explain the anomaly.

**Comment by SlimeDog** [comment]
items.yml (partial):

> items-Version: 5
Global-Settings:
  Prevention:
    prevent-pickups: false
    AllowOPBypass: false
    CreativeBypass: false
  Clear-On:
    clear-on-join: false
    clear-on-world-change: false
    clear-only-itemjoin-on-join: true
    clear-only-itemjoin-on-world-change: true
    AllowOPBypass: false
  First-Join:
    FirstJoin-Mode-Enabled: false
  Get-Items:
    ItemJoin-Specific-Items: true
    Global-Items: false
    Delay: 2
world_lobby:
  items:
    changeWorld-universe:
      id: PRISMARINE_CRYSTALS
      data-value: 0
      enchantment:
        - 'FIRE_ASPECT:1'
      name: '&bChange world'
      slot: 8
      count: 1
      lore:
        - 'Teleport to another world'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK
      commands:
        - 'chestcommands open mvtpWorld.yml'
      itemflags:
        - 'unbreakable'
        - 'hide-attributes'
        - 'placement'
        - 'inventory-modify'
        - 'count-lock'
        - 'self-drops'
        - 'respawn'
        - 'world-changed'
        - 'hide-durability'

**Comment by SlimeDog** [comment]
Any hints?

**Comment by RockinChaos** [comment]
Sorry I have been busy with a lot of other bug testing and I havent had time to run it with Skript. I am multi tasking the v3.9 bug fixes with the v4.0 release and I am getting caught up in so much stuff. My goal this week is to lock down on v3.9 and get it released I will let you know when I have an update on this.

I have a few other people running a similar setup as you with no problem so I am a bit curious.

**Comment by SlimeDog** [comment]
Thanks for the update. It depends what specifically they are doing with IJ and Skript. I have posited (above) that perhaps IJ is running the commands as OP; that would be one plausible explanation, and it may not affect other users, but since I'm checking a permission, it matters. Of course, it may be caused by something entirely different. 

I would be happy to provide access to my test server, if that would be useful to isolate and resolve the issue.

**Comment by RockinChaos** [comment]
I am finally working on bug testing this, it seems like its going to take me a while as I have no knowledge of Skript and usually my bug testers handled that end of things.

**Comment by SlimeDog** [comment]
Thanks. I provided the necessary scripts, and explanation of the results. The scripts provide all the output required to verify the issue.

While I would be happy to be shown my error, I think the data speak for themselves.

**Comment by SlimeDog** [comment]
I figured it out. The problem was configuration at my end. Please accept my apologies for wasting your time.

**Comment by RockinChaos** [comment]
Its all good, its a learning experience for me.
