### ISSUE TITLE
Constant Maps Error

### ISSUE THREAD

**Issue by airider** [RockinChaos/ItemJoin#81]
Just loaded up a clean version of Bukkit 1.10.2 (I tried this with Spigot as well) ran it and joined the world with MC 1.10.2.  I then put ItemJoin v3.8 into the plugins folder.  The plugin loads fine with the server starting up.  However, once I join, I get this error (attached).  I don't have any custom worlds loaded, only the defaults that craftbukkit created.  I join the servier just fine and the world opens in MC, but no items are in my inventory.  I haven't modified the config.yml, en-lang.yml, or items.yml (but I plan to modified the items once I get this working).  no other plugins are being used.  Need some help if you can provide it.  Thanks!

![screen capture](https://cloud.githubusercontent.com/assets/25273407/22178853/e6cf5926-dff7-11e6-8d6d-9c6eeec1cc8a.png)

**Comment by RockinChaos** [comment]
This wont affect anything on your server. This is because spigot changed how they render maps and I have to find the new calculations for v3.9 so it no longer shows this message. Sadly its not an easy task but it will be fixed.

**Comment by airider** [comment]
Good to hear appreciate the hard work.  What version of Spigot would you recommend to avoid this for now?

**Comment by RockinChaos** [comment]
Thats the problem, they sprung this upon me and I havent been able to find when it changed. It must be a 1.11 update. But its no big deal its just a message that shows up in console, nothing actually happens in game. I think i might have finally located the new code for this.

**Comment by RockinChaos** [comment]
ItemJoin v3.9 has been released and fixes this issue.
You can download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=139837
If you have anymore problems feel free to open another bug report.
