### ISSUE TITLE
Global config option broken

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#83]
Global configuration doesn't work so well. Starting with the global-style _items.yml_

> items-Version: 5
Global-Settings:
  Prevention:
    prevent-pickups: false
    AllowOPBypass: false
    CreativeBypass: false
  Clear-On:
    clear-on-join: false
    clear-on-world-change: false
    clear-only-itemjoin-on-join: true
    clear-only-itemjoin-on-world-change: true
    AllowOPBypass: false
  First-Join:
    FirstJoin-Mode-Enabled: false
  Get-Items:
    ItemJoin-Specific-Items: true
    Global-Items: true
    Delay: 2
world-list:
  world_lobby ##this has - in front, but markdown formatting doesn't like it
  ...
  world_yellowdog_the_end ##this has - in front, but markdown formatting doesn't like it
global:
  items:
    changeWorld-universe:
      id: PRISMARINE_CRYSTALS
      data-value: 0
      enchantment:
        - 'FIRE_ASPECT:1'
      name: '&bChange world'
      slot: 8
      count: 1
      lore:
        - 'Teleport to another world'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK
      commands:
        - 'chestcommands open mvtpWorld.yml'
      itemflags:
        - 'unbreakable'                 #// Makes this item INDESTRUCTABLE! //#
        - 'hide-attributes'             #// Hides ALL attributes, such as firework color, damage the item does, enchantments. (Hides everything from lore except the custom lore). //#
        - 'placement'                   #// Prevents this item from being placed if it is a BLOCK, This item obviously can't be since it is a sword. //#
        - 'inventory-modify'            #// Prevents this item from being moved, stored, or switched to offhand in the players inventory. //#
        - 'cancel-events'               #// Prevents player from opening a chest while this item is in hand or any openable items. //#
        - 'count-lock'                  #// Prevents the player from using all of the item. //#
        - 'self-drops'                  #// Prevents the player from dropping this item, either clicking it out of inventory or using the drop key, usually (q). //#
        - 'respawn'                     #// This item will be given on respawn if a player dies. //#
        - 'world-changed'               #// This item will be given on world changed, Meaning when you enter the world this item is allowed in it will be given. //#
        - 'hide-durability'             #// Hide the durability bar from your item. //#

If I stop the server, change PRISMARINE_CRYSTALS to COMPASS, restart, the compass appears only in the first world I enter. The prismarine_crystals remain in (zero-based) slot 8, but of course they are no longer IJ-relevant.

This should expand (internally) to the equivalent individual listings for all 23 worlds in the (truncate) list. If I resort to the individual worlds version of items.yml, change the 23 instances of PRISMARINE_CRYSTALS to COMPASS, all is well.

If I made a mistake in the global version, please advise.

BTW, starting with 1.11.x, I think item names are lower case. IJ does not recognize them, though.

**Comment by RockinChaos** [comment]
I think you made some mistake somehow because I was able to get this working fine for me. Its a bit hard for me to test your config file because all the spaces are gone.

Are you still having this issue? If it happens again can you please post your items file in pastebin.com

Sorry for the late response I just got to bug testing this.

**Comment by SlimeDog** [comment]
Start with IJ item individually defined per world: [items.yml-individual-WATCH](http://whitedog.straight8.com/drops/items.yml-individual-WATCH). The item is WATCH. It works great, and is currently in production.

Stop the server. Change to items defined globally, with the same item: [items.yml-global-WATCH](http://whitedog.straight8.com/drops/items.yml-global-WATCH). Restart the server. It also works correctly, but...

Stop the server. Change to global item to COMPASS: [items.yml-global-COMPASS](http://whitedog.straight8.com/drops/items.yml-global-COMPASS). Restart the server. Login. In the initial world to which I connect, the item in (0-indexed) slot 8 changes to COMPASS. It is IJ-active; I can use it to mvtp to another world. In the second world, the item in (0-indexed) slot 8 is WATCH, and it is not an IJ item. I can return to the initial world with **/back**, and the IJ item (COMPASS) is active.

**Comment by SlimeDog** [comment]
Latest 3.9.2-pre fixes it. Yay!
