### ISSUE TITLE
Bug or Config problem.

### ISSUE THREAD

**Issue by yetenszi** [RockinChaos/ItemJoin#85]
When i add new items and launch the server it replaces the items.yml with the default one so i never get my items.

**Comment by yetenszi** [comment]
also it doesn't remove the file but just renames it with a bunch of numbers at the end.

**Comment by RockinChaos** [comment]
Defiantly a configuration issue, can you send me your items.yml you are trying to save, as well as the new one that is being generated. Along with your config and en-lang.yml.

Post them in 4 separate pastebin.com links please. Ill find and fix the error you are writing into the items.yml.
