### ISSUE TITLE
Inventory Click

### ISSUE THREAD

**Issue by FineStine** [RockinChaos/ItemJoin#86]
Can you add a feature so we can bind commands to inventory click?
So when I open my inventory and click on the item it will run the command instead of exiting me out of the inventory.

**Comment by RockinChaos** [comment]
Defiantly will look into adding this for v4.0 release.
Btw it exits you out of your inventory only in creative mode and this is to prevent duplicating. If you remove inventory-modify itemflag then that wouldnt happen but you would be allowed to move the items.

**Comment by RockinChaos** [comment]
v4.0 has been released with this feature added!

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950
