### ISSUE TITLE
Feature request: log coloration

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#88]
Please introduce a configuration option to disable formatting codes in log entries. I prefer plain text, no colors or etc. Make the default whatever you feel is most requested, but please give me the option.

**Comment by RockinChaos** [comment]
Officially added to v4.0. I presume this is the output you were wanting;

http://imgur.com/a/I4yHD

the Log-Coloration option has been added to the config.yml and it is enabled by default, but you can switch it to false and all colors outputted by ItemJoin will be stripped of their color codes.

**Comment by SlimeDog** [comment]
Excellent. Thanks.

**Comment by RockinChaos** [comment]
v4.0 has been released with this feature added!

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950
