### ISSUE TITLE
No items

### ISSUE THREAD

**Issue by F0xyYT** [RockinChaos/ItemJoin#9]
Hello goods sir!
I Installed the plugin and configured it my way! But when i join or do suicide,i got no items,can you please help me?

Thank you, F0xy

**Comment by RockinChaos** [comment]
Can you please paste your config and items.yml in   
Pastebin.Com.  also are there any errors on startup? (Server log). Are you using multiverse 2.5 beta?

**Comment by F0xyYT** [comment]
The paste bin: http://pastebin.com/xyZG0DgS
Is multiverse required for your plugin work?
Also no logs at startup but when i try to reload the plugin it says an error in the console :/

**Comment by RockinChaos** [comment]
No it is not required, as of version 2.2 you can opt out of multiverse. Just set it to FALSE in the config.yml and you will be good to go.

Everything items.yml seems fine.

If you want items on suicide == respawn. Set it to true in the config. Same goes for on world change. Such as going to the nether and back.

For the on join. Are you sure you have set the correct worlds in the items.yml and config.yml?
http://www.swe-gaming.com/fsx/files/2011-12/081625_minecrafserv.png (shows this) (just a random image I found lol)

Currently the items.yml worlds are CASE SENSITIVE! This will be changed later so make sure you define it correctly.

**If you are still having issues:**
Do you use MineverseChat or VentureChat?
Can you please post your latest.log (startup log) and the player joining in a pastebin.com

**Comment by RockinChaos** [comment]
Hey, has this issue been solved for you? If you want you can try starting scratch with [ItemJoin v2.3](http://dev.bukkit.org/bukkit-plugins/itemjoin/files/17-item-join-v2-3/) that has been released. It fixes a lot of bugs.

Please let me know if you need any help.
