### ISSUE TITLE
'Duping items'

### ISSUE THREAD

**Issue by kingremco** [RockinChaos/ItemJoin#91]
If you have items, that has the'inventory-modify' flag, located in the inventory (not in the hotbar), you are able to dupe said item when you Shift-Click on them. This make a copy of the item in the first available slot in the hotbar. Oh, this also works when hovering over the items and pressing 1-9 to relocate them.

**Comment by kingremco** [comment]
This was tested on Spigot 1.8.8

**Comment by RockinChaos** [comment]
Is it possible you can get me a screencap or link me to your server so I can test this out? I haven't seen this happen before.

Also a pastebin link to your items.yml and config.yml would be nice too/

**Comment by kingremco** [comment]
screencap: https://im3.ezgif.com/tmp/ezgif-3-b995d1bd40.gif

items.yml: http://pastebin.com/W2NrzAvB
config.yml: http://pastebin.com/P42Q8Qkk

**Comment by RockinChaos** [comment]
Ah... yeah... Sorry to say that its a bug within spigot/cb its self. I spent a while trying to figure this one out.
For the v4.0 recode I am trying to find a work around but its becoming difficult. I will keep you posted as I progress on this.

As for the 1-9 keys I found the issue I made it so you couldnt move them to your cursor but I never made it so you could make it so you cant move them from your cursor to your hotbar. Just had to add a simple reverse switch and its all fixed. Ill try to patch as much as I can and get a v3.9.3 bug fix out soon. I would like to find a temp fix for that creative mode issue tho.

**Comment by RockinChaos** [comment]
Found a resolution and fixed both problems, just waiting on a proper time to update this for you.

**Comment by RockinChaos** [comment]
Sorry for the late update, I have done somewhat of a "hacky" fix as it is a client-sided bug with mojang but it gets the overall job done. I will have to do a recode for v4.0 that involves sending the client packets, that would probably have a better outcome, anyways it has been released and you can get it here;

https://www.spigotmc.org/resources/itemjoin.12661/download?version=152238
