### ISSUE TITLE
Enchanted Golden (Notch) Apples

### ISSUE THREAD

**Issue by airider** [RockinChaos/ItemJoin#92]
Request a new feature.

Desire the ability to add potion effect types to Notch apples which use the PotionEffect and PotionEffectType classes within the spigotAPI.

Details of the classes are listed here:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffect.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html

The PotionEffect Class supports providing Notch apples to players with varying types of potion enchantments.  Request PotionEffect utilize the PotionEffectType type, duration and amplifier options with the class.  (e.g. ABSORPTION:300:3, which provides a notch apple with the ABSORPTION potion, which lasts for 300 ticks (15 seconds), with an absorption level of 3).  Duration can also be converted to seconds directly if desired for ease of use.

The plugin should have the ability to use any/all PotionEffectTypes listed in the API.  This includes the ability to stack multiple potion types together under the same Notch apple within the items.yml.

Notch apples should also be configurable to specific worlds and player permissions.

**Comment by RockinChaos** [comment]
v4.0 has been released with this feature added!

You can click here to download; https://www.spigotmc.org/resources/itemjoin.12661/download?version=168950
