### ISSUE TITLE
Items id arn't working

### ISSUE THREAD

**Issue by Tech305** [RockinChaos/ItemJoin#93]
I was trying to make an item that is using a Minecraft Nether_Start or just diamond it shows a purple square like it's not supported or anything i even tried the block id and that didn't work

**Comment by RockinChaos** [comment]
sounds like you are configuring your items.yml incorrectly. Can you post your items.yml in a pastebin.com and link it to me please. 

Also what version of spigot/bukkit and ItemJoin are you using?

**Comment by Tech305** [comment]
link for pastbin: https://pastebin.com/VjKs7k87
==Version Info==
This server is running CraftBukkit version git-Spigot-625bc00-d09304e (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

and it states that I am 3 versions behind but don't know how to update I'm using it for my bungee server

**Comment by Techno3600** [comment]
Latest build on spigot

**Comment by Tech305** [comment]
would i need to change the spigot for each server or update the proxy

**Comment by Tech305** [comment]
how about the YAML code

**Comment by RockinChaos** [comment]
Nothing is wrong with your spigot, its okay to be a couple versions behind

      data-value: 3

Remove that line. Its not DIAMOND:3 its just DIAMOND (as diamond does not have a data value).


See https://www.spigotmc.org/wiki/itemjoin-getting-started/ and read the section _How do you create an item?_ It will better explain this, but simple resolution just remove the data-value line from your diamond item.

**Comment by Tech305** [comment]
okay thanks so much you help alot

**Comment by RockinChaos** [comment]
No problem, thats what I am here for. If you need anything else feel free to open up another isssue :)
