### ISSUE TITLE
Items are not given on world change

### ISSUE THREAD

**Issue by mpivchev** [RockinChaos/ItemJoin#98]
My server is using MultiInv and that is causing ItemJoin to not give items when a player teleports to different worlds. Commands also don't work occasionally.

In case I did something wrong, here is the item config. I tried pretty much everything but it still doesn't work the way it should:
https://pastebin.com/iehAGATq

**Comment by RockinChaos** [comment]
you should be able to adjust the Delay: #ofSeconds. To a point where it will give the items.

**Comment by mpivchev** [comment]
Ok, I removed MultiInv and increased the delay to 5 seconds, yet items are still not given on world change. It only works when the player joins the game.

**Comment by RockinChaos** [comment]
You never added a world-changed to the itemflags thats why you arent getting it on world changed. Just like respawn is added add world-changed to your itemflags

**Comment by mpivchev** [comment]
Ah, such a stupid mistake. Thanks for the help! It works great now.

**Comment by RockinChaos** [comment]
No problem. You can set the delay back to 2 seconds now
