### ISSUE TITLE
I can't make it give the item's in Multi Verse

### ISSUE THREAD

**Issue by CreepTheWolf** [RockinChaos/ItemJoin#99]
I don't know if there is a way to do this or not, but I am unable to make it give the specified items whenever someone joins another world in Multiverse, pls help me;-;.

**Comment by RockinChaos** [comment]
Please send your items.yml in a pastebin.com

I assume you dont have world-changed put into your itemflags.

**Comment by CreepTheWolf** [comment]
wait, you could do that.. ._, nvm, thnks..

**Comment by CreepTheWolf** [comment]
._.

**Comment by CreepTheWolf** [comment]
here it is, tho https://pastebin.com/DKVyqvEx

**Comment by CreepTheWolf** [comment]
Also, I am putting the "SkyWarsSpawn" (that's the name of the multiverse world) into the enabled worlds or whatever, but it isn't working

**Comment by CreepTheWolf** [comment]
(Srry for so many replies, lol) I just have to say, your Customer support is on point

**Comment by CreepTheWolf** [comment]
umm, nvm, I spelled it "SkyWatsSpawn" in the items.yml, oops. I am good at English

**Comment by RockinChaos** [comment]
It looks like it should work, I fixed the spelling mistake
https://pastebin.com/BFcPbYr9

Let me know if it works.

**Comment by RockinChaos** [comment]
Its been a while since I have heard from you, are you still having this issue?
